### ISSUE TITLE
[UI] 經驗單篇的解鎖進入點

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/GoodJobShare#1006]
[單篇-阻擋](https://hopk8t.axshare.com/#id=iz4xi8&p=%E5%96%AE%E7%AF%87_-_%E9%98%BB%E6%93%8B&g=1)
[單篇-解鎖成功](https://hopk8t.axshare.com/#id=76hjm3&p=%E5%96%AE%E7%AF%87_-_%E8%A7%A3%E9%8E%96%E6%88%90%E5%8A%9F&g=1)

**Comment by barry800414** [comment]
使用者進到面試、工作心得頁面，可以檢查現在是否解鎖

**Comment by peteranny** [comment]
Schema https://goodjoblife.atlassian.net/wiki/spaces/GJ/pages/4521993/GoodJob+Design+Doc?fbclid=IwAR00FrJrGq1uZJbOG7bIJZQ3GnuNkkq1f4GGDKyWp-ZS63WN6GQ0B88bsi0
