### ISSUE TITLE
[UI] 薪資工時的解鎖進入點

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/GoodJobShare#1007]
### UX
[Blocked](https://hopk8t.axshare.com/#id=a56e1j&p=blocked&g=1)
[Popup](https://hopk8t.axshare.com/#id=7ghj24&p=blocked_-_popup&g=1)

### UI
[Blocked](https://www.sketch.com/s/4238b387-3057-4a39-9dca-65d936899c69/a/EL81A0R)

**Comment by barry800414** [comment]
Probably has been done

**Comment by peteranny** [comment]
Should be addressed by https://github.com/goodjoblife/GoodJobShare/pull/1079

https://user-images.githubusercontent.com/7566586/230417875-5c2ca7b1-39bd-4fc0-9bd9-9d4deacb5dc6.mov
