### ISSUE TITLE
[UI] 解鎖方案頁面

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/GoodJobShare#1008]
[Routing](https://hackmd.io/khxI9FJCSW-1QG8mUo7fTA#Client-Side-Routing)

[解鎖全站資料方式](https://hopk8t.axshare.com/#id=5btjfq&p=%E8%A7%A3%E9%8E%96%E5%85%A8%E7%AB%99%E8%B3%87%E6%96%99%E6%96%B9%E5%BC%8F&g=1)

**Comment by peteranny** [comment]
https://github.com/goodjoblife/GoodJobShare/issues/1016
