### ISSUE TITLE
[UI] 我的目前方案頁面

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/GoodJobShare#1010]
[Routing](https://hackmd.io/khxI9FJCSW-1QG8mUo7fTA#Client-Side-Routing)

[目前方案 (login)](https://hopk8t.axshare.com/#id=7cfjwo&p=%E7%9B%AE%E5%89%8D%E6%96%B9%E6%A1%88__login__%E6%9C%89%E4%BB%98%E8%B2%BB&g=1)
[目前方案 (login) 沒付費 - 沒解鎖](https://hopk8t.axshare.com/#id=mpd9yw&p=%E7%9B%AE%E5%89%8D%E6%96%B9%E6%A1%88__login__%E6%B2%92%E4%BB%98%E8%B2%BB_-_%E6%B2%92%E8%A7%A3%E9%8E%96&g=1)
[目前方案 (login) 沒付費 - 有解鎖](https://hopk8t.axshare.com/#id=tx2ab6&p=%E7%9B%AE%E5%89%8D%E6%96%B9%E6%A1%88__login__%E6%B2%92%E4%BB%98%E8%B2%BB_-_%E6%9C%89%E8%A7%A3%E9%8E%96&g=1)

**Comment by wutingy** [comment]
我發現我這個 UI 還沒有畫，今天補上了！
- [目前方案 有付費](https://www.sketch.com/s/4238b387-3057-4a39-9dca-65d936899c69/a/pYY8zqZ)
- [目前方案 沒付費 - 沒解鎖](https://www.sketch.com/s/4238b387-3057-4a39-9dca-65d936899c69/a/qbb8Jrn)
- [目前方案 沒付費 - 有留言解鎖](https://www.sketch.com/s/4238b387-3057-4a39-9dca-65d936899c69/a/zyylAGy)
- [方案紀錄](https://www.sketch.com/s/4238b387-3057-4a39-9dca-65d936899c69/a/Oee0z8G)
