### ISSUE TITLE
[Optional][UI] 我的方案紀錄頁面

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/GoodJobShare#1011]
[Routing](https://hackmd.io/khxI9FJCSW-1QG8mUo7fTA#Client-Side-Routing)

[方案紀錄](https://hopk8t.axshare.com/#id=48uf8n&p=%E6%96%B9%E6%A1%88%E7%B4%80%E9%8C%84&g=1)

**Comment by barry800414** [comment]
done by https://github.com/goodjoblife/GoodJobShare/pull/1154
