### ISSUE TITLE
[UI] 訂單狀態確認頁面

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/GoodJobShare#1013]
[Routing](https://hackmd.io/khxI9FJCSW-1QG8mUo7fTA#Client-Side-Routing)

[付費結果 - 確認中](https://hopk8t.axshare.com/#id=lxhx2f&p=%E4%BB%98%E8%B2%BB_-_3d&g=1)
[付費結果 - 成功](https://hopk8t.axshare.com/#id=v3eqwr&p=%E4%BB%98%E8%B2%BB%E7%B5%90%E6%9E%9C_-_%E6%88%90%E5%8A%9F__3d_and_no_3d_&g=1)
[付費結果 - 失敗](https://hopk8t.axshare.com/#id=ixggiu&p=%E4%BB%98%E8%B2%BB%E7%B5%90%E6%9E%9C_-_%E5%A4%B1%E6%95%97__3d_and_no_3d_&g=1)可以顯示確認中、付款成功、付款失敗

**Comment by peteranny** [comment]
UI https://github.com/goodjoblife/GoodJobShare/issues/1016
