### ISSUE TITLE
Migrate /me/permissions/search to graphql

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/GoodJobShare#1014]
https://api-dev.goodjob.life/graphql?fbclid=IwAR2yTiBz730QTfuPjddw_TIAZP-A2kKBlbTpk2KT0_TBiHxSOj6Y-GZZtek

**Comment by barry800414** [comment]
will be solved by https://github.com/goodjoblife/GoodJobShare/pull/1068

**Comment by barry800414** [comment]
Need to wait https://github.com/goodjoblife/WorkTimeSurvey-backend/issues/775
