### ISSUE TITLE
Footer 連結錯誤

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#103]
![screen shot 2017-05-16 at 23 16 43](https://cloud.githubusercontent.com/assets/8353239/26113692/ce76d566-3a8d-11e7-9bde-187813bd50eb.png)

facebook 連結應該連到：`//www.facebook.com/goodjob.life`

請路過的人修一下，謝謝！

**Comment by mark86092** [comment]
I'll fix it
