### ISSUE TITLE
面試經驗表單 footer 資料數量錯誤

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#1030]
目前已經 9 萬多筆，現在仍顯示 2 萬
<img width="723" alt="Screen Shot 2022-11-20 at 12 29 06 AM" src="https://user-images.githubusercontent.com/3805975/202861302-b376664f-fd52-447c-963f-32bee42f74ff.png">

**Comment by peteranny** [comment]
修完好像只有1萬多筆

**Comment by mark86092** [comment]
@peteranny 可以看 stage site

**Comment by barry800414** [comment]
@peteranny 因為這邊本地端我接 www-dev 站的 Backend ，所以只有 1 萬多，Prod 上面實際上是九萬多～
