### ISSUE TITLE
小教室搜尋功能

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/GoodJobShare#105]
之前開會提到過在小教室放搜尋功能，我覺得是很重要的功能，不然上線的小教室會內容很多很雜，若沒有關鍵字搜尋，讓人也有點懶得看

**Comment by mark86092** [comment]
想問這邊的搜尋是指

1) 根據關鍵字找到哪篇小教室嗎？ 2) 根據關鍵字找到哪張圖片？

然後你有技術上的想法嗎？

**Comment by peteranny** [comment]
我理想是2，但2需要行銷組的支援才能完成（圖片下tag）。

1是做得到，但是1有幾種方法可行：

1. 為每個小教室增加keyword欄位來搜尋，這一樣要行銷組的支援，缺點是沒列出來的keyword就搜不到
2. 直接拿內文來搜尋，可以用最粗略的indexOf來搜就好，這是可以直接撰寫的，缺點是這需要直接載入所有小教室的內容，如果搜尋是放在小教室目錄的話，那就喪失了小教室目錄只放meta的意義（因為要載入所有小教室的內容才能搜尋）

我覺得如果小教室近期要先上的話，可以先用2，之後1好了再換回1，因為我覺得小教室上線馬上就有搜尋功能真的滿好的

**Comment by mark86092** [comment]
這個方向基本上不會從前端著手，畢竟後端拿到所有的資料是比較輕易的

不過我想問，以內文的搜尋來說，google bot 爬到的搜尋不能滿足你說的需求嗎？就是，要特別做的搜尋應該是有什麼目的

**Comment by peteranny** [comment]
我認為這樣可以導來網站的流量停留的機率高一些，站內搜尋我認為是我在瀏覽我們小教室時直覺缺少的東西

**Comment by peteranny** [comment]
或是要有hash tag可以讓人在站內快速抓重點

**Comment by mark86092** [comment]
那我把這個議題放到組長會一群討論

1. 是否要站內搜尋（不過基於開發時程，這很難現在做）
2. hash tag，顯示一些關鍵字列表出來 （這個應該短時間內可以加上）

**Comment by mark86092** [comment]
這個也看起來是 1 的一個解法 https://cse.google.com/cse/?hl=zh-TW

**Comment by peteranny** [comment]
隨便寫了一個demo branch：`labor-rights-search-demo`，這是我大概想像的樣子

**Comment by mark86092** [comment]
我知道你想做的事情，
不過搜尋這件事不能只客戶端把所有文章爬一遍做子字串比對（萬一有 20 篇怎麼辦），這個就看大家認為是否需要來決定要不要開發還有找解決方案

不過你能補充一下：
> 上線的小教室會內容很多很雜，若沒有關鍵字搜尋

關鍵字搜尋怎麼幫助小教室較清楚而不雜？

**Comment by peteranny** [comment]
我寫的demo沒有別的意思，只是自己簡單實作一下看跟想像的有沒有差很多，也比較具體

小教室內容確實很多，應該有人(我)會有需求想要找哪一方面的勞動知識來看，就算不搜尋也要有hashtag

另外我覺得小教室是相較數量固定的資料集，就算是20篇我也覺得還好， 不過我講這個不是說我堅持要在客戶端，我只是表達我覺得在客戶端沒有那麼不可行而已

**Comment by mark86092** [comment]
ok，了解了，禮拜六會開一下會確認這件事要做的時間點

**Comment by barry800414** [comment]
有搜尋引擎當然會比沒有好，不過我的想法是Priority會排在後面一些 （作為enhancement），我們先把更重要的基本功能完成。
