### ISSUE TITLE
[UI] Handle 付款時的後端回傳的錯誤

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#1066]
Reference: https://docs.tappaysdk.com/tutorial/zh/reference.html#test-card

**Comment by barry800414** [comment]
ref: https://github.com/goodjoblife/WorkTimeSurvey-backend/issues/827

**Comment by barry800414** [comment]
ref: https://github.com/goodjoblife/WorkTimeSurvey-backend/issues/826

**Comment by mark86092** [comment]
Tappay 有另一種可能，當卡片不支援 3D 驗證，後端根據格式

```graphql
mutation checkoutSubscriptionWithPrime {
  paymentRecord: PaymentRecord!
  paymentUrl: String!
}
```

將會有 `paymentUrl = ""` 的情況發生，前端發現 `""` 時，需要自行 redirect 到後續的頁面

**Comment by peteranny** [comment]
> Tappay 已知有兩種錯誤：
> 
> 
> 
> ```json
> 
> {
> 
>   "status": 10005,
> 
>   "msg": "Bank system error",
> 
>   "bank_result_code": "10005"
> 
> }
> 
> ```
> 
> 
> 
> 或
> 
> 
> 
> ```json
> 
> {
> 
>   "status": 10003,
> 
>   "msg": "Card error, please ask for issuer",
> 
>   "bank_result_code": "10003"
> 
> }
> 
> ```
> 
> 
> 
> 不管是 Bank System Error 或是 Card Error，或是不預期的錯誤，後端會一律回底下的回答
> 
> 
> 
> ```json
> 
> {
> 
>   "errors": [
> 
>     "message": "Transaction fail"
> 
>   ]
> 
> }
> 
> ```

我們只回字串嗎？要不要多數字代碼

**Comment by mark86092** [comment]
之前回傳的 Graphql 只有 message 比較靠譜可以拿，看了 https://github.com/graphql/graphql-spec/blob/main/spec/Section%207%20--%20Response.md#errors 寫的，基本上也是靠 message

除非有特別用意，不然我覺得不需要特別給 code，必竟都是同樣的錯誤訊息

**Comment by barry800414** [comment]
@mark86092 @peteranny 

我剛試著看 tappay official doc 裡面提到的 error code 
https://docs.tappaysdk.com/tutorial/en/reference.html#what-is-it232

我在想是否可以 
1. 915, 10003, ... 10015 這一系列的錯誤，我們後端都有 handle 
2. 後端的 PaymentRecord 多一個欄位，儲存 tappay 回給我們的錯誤到資料庫。這麼做的用意是之後發現查找問題。
```graphql
{
    id: ID!
    public_id: String!  
   // ...other PaymentRecord fields
   tappay_error: {
      error_code: Int
      message: String
   }
}
```

3. 後端一律回 (這個沒有改變)
```json
{
  "errors": [
    "message": "Transaction fail"
  ]
}
```

4. 前端一率顯示 https://www.sketch.com/s/4238b387-3057-4a39-9dca-65d936899c69/a/jgR3n19

**Comment by mark86092** [comment]
> https://github.com/goodjoblife/GoodJobShare/issues/1066#issuecomment-1488793414
對喔

**Comment by mark86092** [comment]
```graphql
type CheckoutSubscriptionWithPrimePayload {
    paymentRecord: PaymentRecord!
    "for 3-D Secure"
    paymentUrl: String

    "如果有任何錯誤"
    error: {
          message: "Transaction fail"
    }
}
```
