### ISSUE TITLE
[Optional] 使用者可以看到自己的訂閱歷史紀錄

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#1071]

**Comment by wutingy** [comment]
[方案紀錄](https://www.sketch.com/s/4238b387-3057-4a39-9dca-65d936899c69/a/Oee0z8G)

**Comment by peteranny** [comment]
@barry800414 這個需要route path：
「我的方案」目前是 `/me/subscriptions`
「方案紀錄」有沒有建議的path？例如要配合後端之類的。沒有的話可以定成 `/me/history`。

**Comment by barry800414** [comment]
- 我的方案: `/me/subscriptions/current`
- 方案紀錄: `/me/subscriptions`

這樣如何？
