### ISSUE TITLE
付費制通知信 email html

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#1092]
mockup:
https://hopk8t.axshare.com/#id=p6f9vb&p=%E6%9C%89%E6%9C%89%E6%95%88%E8%B3%87%E6%96%99%E8%80%85&g=1

製作成 email friendly 的 html

**Comment by wutingy** [comment]
https://newsleopard.com/nonprofit-organization-plan/
不知道你們有沒有考慮串我們公司的 API?  每個月有 2 萬封的免費額度

**Comment by wutingy** [comment]
好處是可以看開信點擊的報表，也有 automation funnel 可以串上 trigger 系列信件。但是這一封信應該是群發給 user 就好，只差要不要看到達、開信、點擊這些數據

**Comment by wutingy** [comment]
@barry800414 寄了一封到你的 gmail

**Comment by barry800414** [comment]
沒有 enable display image 的狀況（請看圖片內文字）
![IMG_2441](https://user-images.githubusercontent.com/3805975/235956248-d2a2034d-10cf-4aee-9684-fbaa9ef8f71c.png)
![IMG_2440](https://user-images.githubusercontent.com/3805975/235956237-5901ea23-079a-4f4a-9c07-35a5ac723ecf.png)

**Comment by barry800414** [comment]
@wutingy 有 enable display image 的情況（請看圖片內文字）
![IMG_2437](https://user-images.githubusercontent.com/3805975/235957755-2149a5e3-2c93-4ff3-abec-586ff5825a52.png)
![IMG_2438](https://user-images.githubusercontent.com/3805975/235957763-a883ea55-2ebf-4391-aba7-675b934effd3.png)
![IMG_2443](https://user-images.githubusercontent.com/3805975/235957764-8d7a897a-dd49-4fc8-84fa-6b94bb9cb49c.png)

**Comment by barry800414** [comment]
> https://newsleopard.com/nonprofit-organization-plan/ 不知道你們有沒有考慮串我們公司的 API? 每個月有 2 萬封的免費額度

我們這個是一次性的，可能會發十幾萬封，我 prefer 用 AWS SES 
也問問 @mark86092 的想法

**Comment by wutingy** [comment]
如果是一次性的，用 AWS OK, 但是要確認線路是好的（不然很容易進到垃圾信件匣）

**Comment by mark86092** [comment]
SES 很久之前有串過，不過我看 free quota 也不多，一次 10萬封其實蠻驚人的

**Comment by wutingy** [comment]
有辦法分開名單發嗎？一次十萬如果之前都沒在寄信，感覺就蠻容易被擋的...

**Comment by mark86092** [comment]
應該要，或許可以以最後上線時間來決定優先

**Comment by barry800414** [comment]
分開名單發是指？ 譬如說每隔一天發一波這樣嗎？

**Comment by wutingy** [comment]
恩...我可以問問我專業的發信同事，看怎樣比較不會被擋信（？

**Comment by wutingy** [comment]
或是可以考慮這個 API 可以一次發，十萬封是 **2,200 NT$**
大量發送建議是設定好數位簽章，比較不會被退信
https://newsleopard.com/surenotify/pricing/

**Comment by wutingy** [comment]
[gj.html.zip](https://github.com/goodjoblife/GoodJobShare/files/11441648/gj.html.zip)

**Comment by wutingy** [comment]
已上傳 HTML～～圖片可以再 replace 成我們自己 host 的，或是不 replace 也行（我是用公司的後台拉的，所以是公司的 host 與轉）
