### ISSUE TITLE
信用卡填寫區塊，頻繁遇到沒有正常讀取，無法輸入的情況

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#1095]
這是我重刷六次頁面以來，第三次遇到這個問題
信用卡區域的 input 在這個狀態下（沒有顯示 ****)，完全無法輸入

![Screenshot 2023-05-04 at 12 15 53 AM](https://user-images.githubusercontent.com/3805975/235977123-682aa7f1-7064-4478-a75e-cb4fa45a8bec.png)

**Comment by peteranny** [comment]
剛測試，簡單重現方式：
1. 在未登入情況下
2. 進到付款頁面
3. 使用下方的登入紐
4. 登入成功之後會發現無法輸入信用卡

PS. 順帶一提，登入有點慢
PS2. 如果是已登入情況下，在付款頁面直接重整就能輸入信用卡


https://user-images.githubusercontent.com/7566586/236076533-fcb6e6c3-a068-48b0-9a4c-ff4a29708d30.mov

**Comment by mark86092** [comment]
還沒登入時，進到這頁：https://www-dev.goodjob.life/buy?skuId=plan_30_days

會看到這些：
<img width="933" alt="image" src="https://user-images.githubusercontent.com/1908007/236097391-529a064b-2902-4057-a4b1-890d0dd5cd0f.png">

init tappay sdk 是不是遇到什麼問題？
