### ISSUE TITLE
面試經驗、工作經驗填寫頁

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#11]
### Design
[Invision](https://projects.invisionapp.com/d/main#/console/10208710/219769094/preview)
切換到 comment mode 可以看到黃色的留言是給開發者看的。

### Description
- 欄位的驗證（參考後端 api）
- 公司名稱、職稱需要 auto complete 給使用者選
- 此頁面只需考慮 1024px 以上的螢幕大小
- test 撰寫

### Backlog
- 送出資料他一個 preview 頁面，再 comfirm 送出（backlog）#13
- unfocus 時要暫存資料

**Comment by wutingy** [comment]
補上設計：
[成功送出](https://projects.invisionapp.com/d/main#/console/10208710/228150768/preview)
[錯誤訊息](https://projects.invisionapp.com/d/main#/console/10208710/228150682/preview)
[fb驗證送出狀態](https://projects.invisionapp.com/d/main#/console/10208710/228135789/preview)
（可以參考現在網站）

modal style 與之前的相同：
https://github.com/goodjoblife/WorkTimeSurvey/blob/master/src/css/components/modal/_modal.pcss

**Comment by mark86092** [comment]
拆成 #122, #123
