### ISSUE TITLE
面試/工作經驗填寫頁 section title 預設選項

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#110]
### Checklist (edited by mark86092)

- [x] 討論與確認選項
- [ ] 程式碼修改選項
- [x] 選項對應的 placeholder（行銷組）

待討論、確認
![screen shot 2017-05-26 at 20 44 05](https://cloud.githubusercontent.com/assets/8353239/26494996/1e4d9c3c-4254-11e7-94aa-fb708460bc5e.png)

開個 issue 提醒大家

**Comment by mark86092** [comment]
收到

**Comment by barry800414** [comment]
這個部分主要是我負責提案，再跟組長群討論喔！

**Comment by mark86092** [comment]
@mark86092 補上討論的選項結果

**Comment by mark86092** [comment]
工作經驗的預設選項

- 實際工作內容
- 工時狀況
- 薪資福利
- 公司管理方式
- 獲得的成長
- 給管理者的建議

面試經驗的預設選項

- 面試方式
- 面試官專業程度
- 整體心得
- 給公司的建議

**Comment by mark86092** [comment]
@WendellLiu 有不清楚的地方可以問我

**Comment by WendellLiu** [comment]
想問  這裡的選項，是按鈕中的「選項」與自動產出的標題一模一樣這些字嗎？

**Comment by wutingy** [comment]
@WendellLiu 是的，補個圖
![screen shot 2017-06-15 at 09 58 43](https://user-images.githubusercontent.com/8353239/27161973-4a8f3532-51b1-11e7-8f3d-41c8a1afeab6.png)

![screen shot 2017-06-15 at 10 00 27](https://user-images.githubusercontent.com/8353239/27162023-7ac5da44-51b1-11e7-9c10-02b6930eb519.png)

「寫寫你實際上的工作內容... …」這個 placeholder，會依據不同的標題，有不同的文字說明，這個要等行銷組生文案。

**Comment by WendellLiu** [comment]
got it!

**Comment by mark86092** [comment]
@wutingy 工作經驗 那時候有討論兩個多的選項沒列在這（升遷制度、整體心得），可能為需要設計支援

**Comment by wutingy** [comment]
![screen shot 2017-06-15 at 10 58 58](https://user-images.githubusercontent.com/8353239/27163403-acd9f2d8-51b9-11e7-9b43-9baa6a163243.png)

@mark86092 畫出來後發現一定會變成兩行，覺得就讓他出現會比較合適，你覺得如何？

**Comment by mark86092** [comment]
ok呀

Tin <notifications@github.com> 於 2017年6月15日 週四 11:00 寫道：

**Comment by WendellLiu** [comment]
我這裡修改好了，目前待placeholder 文案出爐即可。

**Comment by WendellLiu** [comment]
@barry800414 @mark86092 @wutingy 
這裡有定案了嗎？

**Comment by mark86092** [comment]
今天晚上會討論後定案～

**Comment by wutingy** [comment]
@WendellLiu 
https://docs.google.com/document/d/17yCxktqAODm-YdtlopC7vGef1jqo8UOJzM7KRNGuYhQ/edit

**Comment by WendellLiu** [comment]
@wutingy 
少了一個「面試官專業程度」～

**Comment by mark86092** [comment]
@WendellLiu 那個選項被拔掉了

**Comment by WendellLiu** [comment]
OK

**Comment by WendellLiu** [comment]
@mark86092 @wutingy 那就是以這份文件為主囉

**Comment by mark86092** [comment]
是的！麻煩你了

**Comment by WendellLiu** [comment]
可能來不及改了再上，但我發現有顏文字有個問題，是如果被斷行效果會很差，看要不要再考慮一下。

**Comment by mark86092** [comment]
你估計大概什麼時後，我看一下我這邊的時程

**Comment by WendellLiu** [comment]
我算是做完了，再花一點時間確認有沒有問題。其實可以之後再改也行，總之只是剛好斷行的話看起來蠻奇怪的 ＸＤ

**Comment by barry800414** [comment]
有顏文字如果遇斷行有問題，就先拔掉。先讓文字上，這個不上，內部成員也無法給親朋好友寫

**Comment by WendellLiu** [comment]
@barry800414 
1. 都拔
2. 我看頻率高的拔（但有漏網之魚就是有可能的事情）

**Comment by WendellLiu** [comment]
給公司的建議 的提示字

例如：「希望公司大會可以從每週改成每月一次 (´ཀ`) 」！！！」「希望公司可以開放在辦公室吃早餐 ( ; _ ; )/~~」

越長越容易發生，這個就是常發生的。

**Comment by WendellLiu** [comment]
短一點就比較容易在同一行。

**Comment by barry800414** [comment]
@WendellLiu   看頻率高的拔

而就算真的斷行其實也沒關係
主要內文才是重點

**Comment by mark86092** [comment]
如果因為寬度不同，我覺得先不要顏文字是ok的，

這個修正請晏成先改沒關係，我會隨後發布

**Comment by mark86092** [comment]
再請大家預覽看看，有文字之後可以再跟著修小細節

**Comment by WendellLiu** [comment]
好，我先採 @barry800414 說的，會把我上面提到的那一項的顏文字拔掉。
事實上之後改code 裡面的資料即可。

然後，我會直接改上面那份文件，以求我們的資訊同步。（會備份一次在下面）

**Comment by mark86092** [comment]
好！這個好貼心

**Comment by WendellLiu** [comment]
done!
