### ISSUE TITLE
填寫薪資、工時的時候，擇一填寫有問題

### ISSUE THREAD

**Issue by LittleWhiteYA** [goodjoblife/GoodJobShare#1103]
填寫薪資、工時的時候，雖然顯示擇一填寫，但填完工時之後還是需要填寫薪資

<img width="862" alt="image" src="https://github.com/goodjoblife/GoodJobShare/assets/11289529/05c79430-bb93-43c7-a9d5-0ebc2f5b48b7">

**Comment by peteranny** [comment]
Note: 實際平均工時填寫8的時候不會重現，要寫40的時候才會重現
