### ISSUE TITLE
購買完成後沒有回到原頁面

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#1124]
## 預期行為
- 面試/工作心得單篇頁 (/experiences/:id) -> 購買成功 -> 回到原本該篇 (/experiences/:id)
- 公司/職稱頁 (companies/:name/* or /job-titles/:name/*) -> 購買成功 -> 回到原本公司/職稱頁

**Comment by WendellLiu** [comment]
Verified on dev sitr
