### ISSUE TITLE
面試工作經驗 檢舉功能

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#114]
[mockup](https://app.moqups.com/barry800414@gmail.com/hateILpCZW/view/page/a9823052e)

順序建議：不實 > 人身攻擊 > 廣告 > 其他

**待組長會議討論**

**Comment by mark86092** [comment]
檢舉實際實作會是6月後，近期會跟 @barry800414 確認上次會議得到的點，然後再一次討論

**Comment by wutingy** [comment]
會是 7/1 提交之後嗎？nice...

**Comment by mark86092** [comment]
對...不然太多東西要上了
