### ISSUE TITLE
登入後第一次進到我的方案頁面，資料數量不正確

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#1147]
![4XApwUoDSC](https://github.com/goodjoblife/GoodJobShare/assets/3805975/224f65d9-591f-4dc7-9218-7693da465c4f)

**Comment by WendellLiu** [comment]
background:
這個數字是兩個數字的加總，而失敗時是僅會有一個有資料，或是都沒有。

root cause:
實際上沒有在這個頁面fetch 兩個數字需要的資料，會成功時是倚靠TypeForm 這個元件內的運作去拿到的，雖然還不清楚什麼原因（由於不會每次出問題），但這樣仰賴另一個元件本身就很怪，所以比較好的方式是讓該頁面自己去fetch ，或者讓fetching 與query 綁定。
