### ISSUE TITLE
薪資工時表單改為一頁一題式

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#1195]
### 為什麼重要
1. "薪水"的整體搜尋量比面試高，不論是網路整體搜尋量、或是 goodjob 網站進站的點擊量都是
2. 實驗結果顯示一頁一題式比整頁式轉換率更高

### 需求細節
- UX mockup: (TODO)
- UI: (TODO)
- 希望保留現有薪資表單程式碼，因為我要做 A/B testing

### 參考
- 過去曾經的 PR: https://github.com/goodjoblife/GoodJobShare/pull/886
- Parent issue: https://github.com/goodjoblife/GoodJobShare/issues/957

**Comment by peteranny** [comment]
[Figma](https://www.figma.com/file/okGUQmeosjVn2hMRBNrx75/Goodjob?type=design&node-id=208%3A9068&mode=design&t=ORcB40JsBjBrYtxS-1)

**Comment by mark86092** [comment]
Done
