### ISSUE TITLE
【工作經驗填寫頁】

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#123]
Checklist:

- [x] Component 完成
- [x] 表單驗證
- [x] API 串接
- [x] 登入整合 (#125, #148)
- [x] 公司欄位 Autocomplete (#120)
- [x] 面試/工作經驗填寫頁 section title 預設選項 #110
- [x] 面試經驗/工作經驗 標題自動產生 #131
- [x] 表單送出後的回饋以及頁面跳轉 #147
- [x] 相關職務工作經驗 排除空值 #146
- [x] 面試整體滿意度的 title #140
- [x] 手機版

**Comment by WendellLiu** [comment]
@mark86092 @wutingy 
今天評估，如果要星期三作為deadline ，手機版應該來不及做完。
如果是必要的就只能麻煩誰先幫忙了。

**Comment by wutingy** [comment]
沒問題，我之後會直接蓋一個色塊跟人說「不支援」～

**Comment by mark86092** [comment]
OK, 手機版來不及就麻煩 @wutingy 蓋不支援的版

**Comment by WendellLiu** [comment]
@wutingy 我有在試著解決mobile 的排版，我看你似乎大部分都是以`@media (max-width: 550px)` 作為界線，我也以此來排版囉？

**Comment by wutingy** [comment]
斷點可以參考：https://github.com/goodjoblife/GoodJobShare/blob/master/src/components/common/variables.module.css#L49

通常會用到：
- 1024 平板
- 850 平板直的
- 550 手機版

**Comment by wutingy** [comment]
另外，建議你的外框可以包一個 <Wrapper size="s" />
