### ISSUE TITLE
Safari「給我們回饋」側邊欄沒有全部顯現

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/GoodJobShare#1235]
Browser: Safari

https://www-dev.goodjob.life

![Screenshot 2024-03-28 at 10 18 18 AM](https://github.com/goodjoblife/GoodJobShare/assets/7566586/78377922-7ab3-4e47-8537-2fcd09760d0f)

估計是因為container的寬度不知為何算錯了

![Screenshot 2024-03-28 at 10 24 04 AM](https://github.com/goodjoblife/GoodJobShare/assets/7566586/fb25d465-9839-42c3-aea0-d2c37cf6f15c)

**Comment by YongChenSu** [comment]
修正於以下 PR
https://github.com/goodjoblife/GoodJobShare/pull/1237
