### ISSUE TITLE
[前端] 經驗頁的公司名稱(title, 麵包屑的第五層) 都顯示 Original Company name (user input)

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/GoodJobShare#1245]
## deps

- [x] https://github.com/goodjoblife/WorkTimeSurvey-backend/issues/955

**Comment by barry800414** [comment]
麵包屑的第五層不要了
https://goodjoblife.atlassian.net/wiki/spaces/GJ/pages/58982455/PRD#5.-%E5%96%AE%E7%AF%87%E9%9D%A2%E8%A9%A6%E3%80%81%E5%B7%A5%E4%BD%9C%E5%BF%83%E5%BE%97%E9%A0%81%E9%9D%A2
