### ISSUE TITLE
[前端] 搜尋頁要改用 dataCount 的欄位

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/GoodJobShare#1247]
https://goodjoblife.atlassian.net/wiki/spaces/GJ/pages/44793857/Design+doc#API-schema

**Comment by mark86092** [comment]
搜尋頁要"改用" dataCount 的欄位，這邊的改用是指，原先從

```
salary_work_time_statistics {
    count
}
```

取值，應該要改用 dataCount，並且刪除 salary_work_time_statistics 的用法
