### ISSUE TITLE
面試/工作經驗填寫頁 登入整合

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#125]
### 使用情境

1. 當使用者還未登入 FB 時，填寫頁的表單在送出時要讓使用者 login
2. 當使用者已經登入 FB，就可以送出填寫的資料（已完成）

### 可能會遇到的問題

這部分涉及到 (1) FB 登入的狀態轉換，(2) 透過 FB SDK 觸發 FB 登入視窗與 callback

@WendellLiu 需要跟你討論這部分要怎麼處理比較好

**Comment by WendellLiu** [comment]
我沒有真正用過FB 登入，所以不太清楚登入後的callback 介面會是什麼樣子？
在沒有登入時，送出的按鈕會導去SDK 觸發的登入畫面應該沒有疑慮。
登入後回來是會重刷嗎？如果會就是把資料暫存起來，再載入。

不過這也只是我粗略的想法，不曉得有沒有什麼跟SDK 登入行為不符的？
