### ISSUE TITLE
[前端] 自動完成下拉選單顯示統一編號

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#1272]
https://goodjoblife.atlassian.net/wiki/spaces/GJ/pages/58982455/PRD#1.-%E6%90%9C%E7%B4%A2%E6%A1%86%E8%87%AA%E5%8B%95%E5%AE%8C%E6%88%90

**Comment by peteranny** [comment]
UI看起來要增加統編，但 search_companies 看起來沒有統編
```
type Company {
name: String!
dataCount: Int!
experienceCount: Int!
salaryWorkTimeCount: Int!
businessNumber: String
salary_work_times: [SalaryWorkTime!]!
work_experiences(...): [WorkExperience!]!
interview_experiences(...): [InterviewExperience!]!
salary_work_time_statistics: SalaryWorkTimeStatistics!
work_experience_statistics: WorkExperienceStatistics!
interview_experience_statistics: InterviewExperienceStatistics!
}
```

**Comment by mark86092** [comment]
@peteranny businessNumber 是統編 (nullable)

**Comment by mark86092** [comment]
Done

**Comment by peteranny** [comment]
發現還有個 top nav 的 autocomplete 還沒好~ 先 reopen

**Comment by mark86092** [comment]
Done!

**Comment by mark86092** [comment]
還是沒有，https://www-dev.goodjob.life/share/work-experiences

<img width="980" alt="image" src="https://github.com/goodjoblife/GoodJobShare/assets/1908007/7a6f5da6-7309-4929-80e8-f69596cce6e4">
