### ISSUE TITLE
[前端] 表單 interface 調整

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#1281]
表單 graphql interface 調整

```diff
input CreateInterviewExperienceInput {
  company: CompanyInput!
  ...
}

input CreateWorkExperienceInput {
  company: CompanyInput!
  ...
}

input CompanyInput {
-  id: String
+  id: String  # interface 不變，但後端邏輯改變，沒有 breaking change
  query: String!
}
```

```diff
POST /workings
- * company_id
- * company (Optional String)
+ * company (Required String)
```

參見：
https://goodjoblife.atlassian.net/wiki/spaces/GJ/pages/44793857/Design+doc

## deps
- [x] https://github.com/goodjoblife/WorkTimeSurvey-backend/issues/951

**Comment by mark86092** [comment]
@peteranny 由於後端解析表單傳送過來的 Company 的方式有變，連帶造成薪資表單用到的這隻 `POST /workings` 有變化

需要麻煩你幫忙確認前端的 薪資表單 都有送 company 欄位（以前是 optional）

**Comment by peteranny** [comment]
> @peteranny 由於後端解析表單傳送過來的 Company 的方式有變，連帶造成薪資工時表單用到的這隻 `POST /workings` 有變化
> 
> 需要麻煩你幫忙確認前端的 薪資工時表單 都有送 company 欄位（以前是 optional）

剛檢查，前端一直都會送 company name，應該沒有只送統一編號的例子

**Comment by mark86092** [comment]
@peteranny 感謝！
