### ISSUE TITLE
[前端][M1] 工作心得列表卡片修改

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#1283]
指的是這個元件

![Image](https://github.com/goodjoblife/GoodJobShare/assets/3805975/e12631ad-5347-4ec8-a641-af684f1104d7)

- 顯示整體評價
- 需考慮 backward compatibility，舊版工作心得仍然要可以正常顯示

UX Mockup: https://hopk8t.axshare.com/#id=zhogbr&p=%E8%A9%95%E5%83%B9%E7%9B%B8%E9%97%9C%E5%85%83%E4%BB%B6_m1&g=1
PRD: https://goodjoblife.atlassian.net/wiki/spaces/GJ/pages/59506690/PRD

**Comment by peteranny** [comment]
https://github.com/goodjoblife/GoodJobShare/issues/1302

**Comment by mark86092** [comment]
https://www-dev.goodjob.life/job-titles/%E5%89%8D%E7%AB%AF

<img width="1467" alt="image" src="https://github.com/user-attachments/assets/587fdf0b-3f28-4207-b42c-67c8964ebd46">

職稱頁面的工作心得應該要顯示 整體評價 (如圖應為 1.5分, 2.5分)

**Comment by mark86092** [comment]
@barry800414 Please help check
@YongChenSu I could not find related PR about above comment, please help check whether it is done or not

**Comment by barry800414** [comment]
I think done by #1354

**Comment by mark86092** [comment]
@barry800414 https://github.com/goodjoblife/GoodJobShare/issues/1283#issuecomment-2312744290

**Comment by YongChenSu** [comment]
Done by #1436
