### ISSUE TITLE
面試經驗/工作經驗 標題自動產生

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#131]
當使用者填上公司名稱時，eg "GoodJob"，則會自動產生 "標題" 在 input (`<input value=xxx>`)

GoodJob 面試經驗分享
GoodJob 工作經驗分享

使用者可以再修改標題或是不改

**Comment by mark86092** [comment]
這裡的標題是指：

![image](https://user-images.githubusercontent.com/1908007/27162594-b98a960e-51b4-11e7-996e-cc998cc27da1.png)

**Comment by WendellLiu** [comment]
@mark86092 這個也交給你關了，感謝！

**Comment by mark86092** [comment]
@WendellLiu 感謝提醒，Done
