### ISSUE TITLE
[前端] 頂部搜尋 的 AutoComplete 加上 debounce

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#1329]
參見 #1319

![Image](https://github.com/goodjoblife/GoodJobShare/assets/1908007/cbf8142b-d202-4663-b8c0-43b7f84906fd)

@LittleWhiteYA 建議 搜尋 的 AutoComplete 可以加上 debounce

## Deps

- [ ] https://github.com/goodjoblife/WorkTimeSurvey-backend/issues/1008

**Comment by peteranny** [comment]
已經有 debounce 了

https://github.com/goodjoblife/GoodJobShare/blob/master/src/components/common/form/TextInput/SearchTextInput.js#L29
