### ISSUE TITLE
[公司名稱整合] 面試經驗表單 公司 input 自動完成表單排版錯誤

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#1331]
## Expected Result
<img width="340" alt="Screenshot 2024-06-17 at 7 46 19 PM" src="https://github.com/goodjoblife/GoodJobShare/assets/3805975/9759423f-0298-4152-a8e9-cee643a838db">

## Actual Result
<img width="368" alt="Screenshot 2024-06-17 at 7 48 51 PM" src="https://github.com/goodjoblife/GoodJobShare/assets/3805975/a261cfaa-c227-4b99-a8ae-11be59bf5f72">

我試著 inspect 一下 css 原因是有個 `flex-direction: column`

**Comment by peteranny** [comment]
這不是排版錯誤，因為大多數情況他會換行在統編的數字，所以我故意弄成垂直
但如果確認這樣換行不會奇怪的話，我可以拿掉垂直排版的部分

![截圖 2024-06-17 晚上8 57 12](https://github.com/goodjoblife/GoodJobShare/assets/7566586/30852cb2-b2fd-4bdb-8e47-2a8745e0b6a1)

**Comment by barry800414** [comment]
瞭解！ 我覺得可以問問 @RnioRnio 的想法
