### ISSUE TITLE
[公司名稱合併] 面試、工作心得、薪資表單，公司 input 欄位，未能查找到沒有資料的公司名稱

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#1341]
## Expected result
在面試、工作心得、薪資表單，若輸入一間公司名稱，有在台灣公司資料裡面，但該公司在 goodjob 還沒有任何資料，自動完成的選單仍然應該要出現該選項

## Actual result
實際上並沒有出現

## How to reproduce 
搜尋 `久巨科技有限公司` ，這間公司有在台灣公司資料，因此有在 DB 裡面建檔

## Root cause
表單的自動完成，在 call graphql api `search_companies` 時，需要傳入 hasData = False 
目前沒傳，預設值是 hasData = True ，因此只有 goodjob 有資料的公司才會被回傳

**Comment by mark86092** [comment]
`src/components/common/form/TextInput/SearchTextInput.js`

<img width="1163" alt="image" src="https://github.com/goodjoblife/GoodJobShare/assets/1908007/38d99e81-f972-41a1-9ec6-c0091ddb943a">

這個地方的搜尋匡也會用到
