### ISSUE TITLE
一頁一題式表單 按下 tab 不預期的跳動

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#1358]
1 先打開 
<img width="1198" alt="image" src="https://github.com/goodjoblife/GoodJobShare/assets/1908007/fea5aac9-4c57-44d3-88ec-71b74f24a725">

2 點擊輸入匡

3 按下 tab

會進到職稱，但沒有上一題可以按...
<img width="833" alt="image" src="https://github.com/goodjoblife/GoodJobShare/assets/1908007/ca17d335-508b-4345-938d-2a2bea910b42">

4 繼續按下 tab

更怪的畫面
<img width="829" alt="image" src="https://github.com/goodjoblife/GoodJobShare/assets/1908007/065b06ae-c45e-43b9-ba47-b2fdbc08d12c">

**Comment by barry800414** [comment]
在想會有這個問題，有可能是因為 input 都放在同個 form 裡面，而 browser 為了考慮輔助使用的情境 (accessibility），讓使用者用 tab 也可以操作

正面的解法是瞭解譬如說視障者，單純用鍵盤操作，要怎麼回上一步。然後把這些邏輯 handle 好（note. 有可能就無法一步一步做 validation & 阻擋，而是最後送出時再說明錯誤訊息）

我認為短期解先擋 tab 沒問題，不過長期確實考量 accessibility 這個情境會更好

我印象 @WendellLiu 後來有投入相關的專案，也許 @WendellLiu 可以給我們一些 input
