### ISSUE TITLE
GraphqlError: [ER0008] Submit interview failed 面試年份需在10年內

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#1365]
這個錯誤是從 rollbar 上看到的，發生次數並不多（過去 30 天只有 1 次）
相當於後端有這個限制，但前端沒有擋住
either 是要後端放寬，或是前端加上檢查邏輯

我認為可以前端加上檢查邏輯，因為說真的 10 年前的面試經驗可能已經不太具參考性，且除非有紀錄，不然應該已經忘得差不多

**Comment by mark86092** [comment]
> 過去 30 天只有 1 次

roll 應該晚上才 deploy https://github.com/goodjoblife/goodjob-deploy-ci/pull/347

所以是不是才 deploy 就看到了

**Comment by mark86092** [comment]
Duplicated with #1401, this issue can be closed
