### ISSUE TITLE
[前端][M1] 工作心得單篇頁面接 API

### ISSUE THREAD

**Issue by YongChenSu** [goodjoblife/GoodJobShare#1374]
已完成「工作心得列表卡片」、「工作心得單篇頁面」的 Desktop UI 介面，但尚串接 API

Todo: `averageSectionRating` 須接 api
後端 `averageSectionRating` 相關的 code: https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/1029/files#diff-efc1675187620595b0844197a25c35eac9b6df752f9182e5cffddee6f27a8489R179

PRD: https://goodjoblife.atlassian.net/wiki/spaces/GJ/pages/59506690/PRD

**Comment by barry800414** [comment]
![Screenshot 2024-08-10 at 9 50 10 PM](https://github.com/user-attachments/assets/a2b5f056-3e8a-489e-9324-ac1d49281c17) 

1. 面試經驗跟評價的卡片裡面的 👍 icon 大小不太一致
[Figma](https://www.figma.com/design/okGUQmeosjVn2hMRBNrx75/Goodjob?node-id=0-5752&t=l2ALv76k0RMF0X3U-0) 裡面的應該是一致的

2. 評價卡片的 👍 ，沒有與面試經驗卡片的 👍 一樣向右對齊

**Comment by barry800414** [comment]
@YongChenSu 

![Screenshot 2024-08-10 at 9 53 50 PM](https://github.com/user-attachments/assets/7e851c28-59f0-49b6-97e6-a3a5613b8471)

手機版的排版，看起來有點跑版

**Comment by peteranny** [comment]
> 
> 手機版的排版，看起來有點跑版
> 
> 

#1376

**Comment by barry800414** [comment]
Done by #1413
