### ISSUE TITLE
[UI Design] 回報(檢舉)功能優化 

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#1378]
PRD: https://goodjoblife.atlassian.net/wiki/spaces/GJ/pages/81133569/PRD

**Comment by wutingy** [comment]
![Image](https://github.com/user-attachments/assets/45664eb6-85fb-4799-9e0b-db26ce6636f8)

**Comment by wutingy** [comment]
回報請參考：[出圖說明](https://www.figma.com/design/okGUQmeosjVn2hMRBNrx75/Goodjob?node-id=994-18660&t=hEXXfzsBt7Xt1Xiu-1)，三角形我出 svg

![Image](https://github.com/user-attachments/assets/d98ee466-15f0-451e-8993-88a2712938c7)


## svg
![Image](https://github.com/user-attachments/assets/f430505d-d066-4815-a698-37fd2abb1beb)

**Comment by wutingy** [comment]
@barry800414 這我畫完了，請 reveiw

**Comment by wutingy** [comment]
![Image](https://github.com/user-attachments/assets/1f6ea15b-6127-468a-98a5-82710e9537aa)

**Comment by barry800414** [comment]
Hi @wutingy 感謝妳！
我想問有點擊回報按鈕後，跳出來的 modal 的 UI 嗎？
