### ISSUE TITLE
【面試經驗分享頁】 試用回報＆詢問

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#138]
比較急著修正的部分（建議7/1前修正）：
- [ ] 薪資的部分會有預設值，如果沒有改動的話，會送出月薪 0 元。應該要視為未填。
- [ ] “面試整體滿意度”的title不見了，只剩五個按讚的手指。
- [ ] 經驗分享時按＋的提示項目修正。 
![2017-06-17 12 21 56](https://user-images.githubusercontent.com/3805975/27250070-9e58cd48-5357-11e7-8e70-8cfa4f65a6e6.png)
（指的是這邊）
- [ ] 送出資料後，沒有跳出modal或跳轉到單篇顯示頁。
- [ ] 表單如果有填寫錯誤的部分，不會有提醒。

比較不急著修正的部分：
- [ ] 面試地區的排序，可不可以按照地理位置北->西->南->東。這好像是比較常見的做法。
- [ ] 職稱的部分，還沒有接自動完成
- [ ] 經驗分享的標題未自動產生
- [ ] 可不可以在頁面的某個部份提示 紅色*的為必填，沒有的為選填 @wutingy

**Comment by mark86092** [comment]
我拆成 issue 後這邊會關掉，這張列表不好維護

**Comment by barry800414** [comment]
ＯＫ
