### ISSUE TITLE
[UI Design][M1.5] 公司頁面 rating 總分

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#1391]
PRD: https://goodjoblife.atlassian.net/wiki/spaces/GJ/pages/59506690/PRD#Milestone-1.5-%E9%9C%80%E6%B1%82%E8%AA%AA%E6%98%8E

**Comment by wutingy** [comment]
補上 電腦版、手機版 UI 在文件中，請 review @barry800414

**Comment by barry800414** [comment]
Thank you @wutingy 
We reviewed it and no problem.
