### ISSUE TITLE
【工作經驗分享頁】試用回報＆詢問

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#141]
有一些是兩頁會共用的，我就不再列一次。

比較急著修正的部分（建議7/1前修正）：
- [ ] 表單如果有欄位填寫錯誤，不會跳錯誤訊息
- [ ] 上傳工作經驗分享後，不會顯示modal或跳轉到該篇經驗分享
- [ ] `你會推薦此工作嗎？` 底下的按鈕無法按一次取消

**Comment by mark86092** [comment]
已整理成 issue，故 close
