### ISSUE TITLE
 FB通知

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#1411]
你的應用程式「 GoodJob 」目前使用的圖形 APIv14.0 將在 17 September, 2024. 終止為期 2 年的服務。為確保轉換順利，請將所有呼叫移轉至圖形 APIv15.0 或更新版本

**Comment by mark86092** [comment]
Login, 後端都是 Graph API

不過的確版本 前端 v19, 後端 v17，所以還不用擔心

**Comment by barry800414** [comment]
Sorry I missed out backend part, yes, it's v17. 
I think we can close the ticket ?

**Comment by mark86092** [comment]
OK, close
