### ISSUE TITLE
跑版

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#1433]
https://www.goodjob.life/companies/%E7%BE%A4%E5%89%B5%E5%85%89%E9%9B%BB%E8%82%A1%E4%BB%BD%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/interview-experiences?p=2

![Screenshot_20240830_091514_Chrome](https://github.com/user-attachments/assets/17de9f08-b6da-4aad-88b4-0523fe3202c2)

Samsung S23, 網站未登入時看到

**Comment by mark86092** [comment]
主要是 薪資 與 讚 的地方太寬

**Comment by barry800414** [comment]
@mark86092 這個在 dev branch 已經修復
https://www-dev.goodjob.life/job-titles/%E8%BB%9F%E9%AB%94%E5%B7%A5%E7%A8%8B%E5%B8%AB/interview-experiences
![Screenshot 2024-08-30 at 7 49 54 PM](https://github.com/user-attachments/assets/24fe1969-d0b6-4686-b672-91e73bf327b6)
