### ISSUE TITLE
相關職務工作經驗 排除空值

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/GoodJobShare#146]
目前寫法， **相關職務工作經驗** 預設值為null。
但送出api 時若未填寫，仍會送出，此時api 會回錯（應為數字）。

該欄位若為空值，需排除，而非直接以null 送出。

**Comment by mark86092** [comment]
發現這個選單選了一個數字之後，就不能取消

**Comment by mark86092** [comment]
Done
