### ISSUE TITLE
Brave 瀏覽器無法正常上傳表單

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#1465]
Source:
- Reported by user via facebook fan page

Statistics: 
- Brave browser Daily Actively User: 30 million  (global)
- All internet users: 5.5 billion 
- Roughly 0.5% of users are using it, maybe in Taiwan the percentage is higher
- We are not able to measure it by google analytics because Brave browser will block it.

**Comment by barry800414** [comment]
Brave 瀏覽器，測試 www-dev.goodjob.life，可以 google 登入（會顯示我的名字，也能看到我過去留的資料）
但面試表單最後 submit button 沒有反應，沒有任何 request 送出，console log 也沒有新訊息
原本就有的訊息：
![Screenshot 2024-12-22 at 11 03 43 PM](https://github.com/user-attachments/assets/b45a233c-b79c-4be2-8e66-872fcd7d28f5)

Local 端跑起來印 console 訊息 debug ，根本原因是 `GAUtils.js` 這一行會解不出來，也不會錯誤
```
window.gtag('get', ga_measurement_id, 'client_id', field =>
       resolve(field),
);
```

**Comment by peteranny** [comment]
> Local 端跑起來印 console 訊息 debug ，根本原因是 `GAUtils.js` 這一行會解不出來，也不會錯誤
> 

會不會跟 #1466 有關
