### ISSUE TITLE
小教室列表頁、單頁

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#15]
### Design
[list](https://projects.invisionapp.com/d/main#/console/10208710/223088072/preview)
[single](https://projects.invisionapp.com/d/main#/console/10208710/223088071/preview)

### Contentful
- 用通用的 email create 一個新的帳號（google login is ok），大家都用同一個帳密登入
- 主要是要先研究 [contentful](https://www.contentful.com/) 怎麼上資料、get 資料，並實作看看。下次開會可以再跟 Tin 討論

**Comment by peteranny** [comment]
- [ ] 已實際串過 Contentful，會把我目前的串法提出來討論是否需要修改
- [ ] 要再研究 textarea 如何讓行銷組使用
- [ ] 討論是否把小教室存在 state（有上一篇/下一篇的問題&API一次就會全抓下來）
- [ ] 是，一次全部抓到 store
- [ ] 圖片
- [ ] 圖片先放一個 placeholder
- [ ] loading?
- [ ] loading state，放一個 ‘loading’ text，Tin 會再補上 style
- [ ] error msg 同上
- [ ] title，description，預設值為 h1，後台適度塞寫給機器人
- [ ] 例如：施亭小教室就可以挖欄位，title & description & og image，
- [ ] 預設為小教室標題，在 <Helmet />裡面定義，`$title || $h1`，如果 title 是 undefined 的話，就用 h1。

**Comment by mark86092** [comment]
關於 contentful 的 API，有找到幾個不錯的

1. https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/select-operator

可以選擇 field，在列表的時候選擇部分欄位就可

2. https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/order

可以排序，按造指定的欄位排序

**Comment by mark86092** [comment]
@peteranny 這邊我有個想法：

既然 contentful api 可以選擇要拿到的欄位，

1. 小教室列表頁只需要 getEntries 的每篇 id, title, coverImage 這三個欄位（一次下載多篇的 content 欄位是很大的負擔）
2. 小教室單篇頁只需要
    1. getEntries 的每篇 id
    2. getEntry(當篇id)

其實我一直沒理解為什麼 LaborRightsSingle, LaborRightsMenu 要共用 state 與 小教室items

1 的部分雖然只需要下載一次資料，但是大多數的 content 的欄位卻不需要用到

**Comment by peteranny** [comment]
我研究一下

**Comment by peteranny** [comment]
我可以改成每頁只下載那一頁的content

但是
> 為什麼 LaborRightsSingle, LaborRightsMenu 要共用 state 與 小教室items
這句話是說小教室不需要放在state嗎

**Comment by peteranny** [comment]
我可以改成每一頁都只下載那一頁的content
但是這一句

>為什麼 LaborRightsSingle, LaborRightsMenu 要共用 state 與 小教室items

是什麼意思，是說兩個state不需要共用嗎
之前彥齊說不需要存map，只要存抓下來的list就好，彥齊是這個意思嗎

**Comment by mark86092** [comment]
這樣說，底下是現在的儲存法(case 1)
```
state --> {
    laborRights: {
        xxxx
    }
}
```
`LaborRightsSingle`, `LaborRightsMenu` 會共用 `state.laborRights`，其中的 xxx 是你內部的資料結構

這是 case 2，

```
state --> {
    LaborRightsMenu: {
        xxxx
    },
    LaborRightsSingle: {
        yyyy
    }
}
```

而選擇用 case1 而不是 case2 的考量是什麼？

會這樣問是想知道，當 LaborRightsMenu 與 LaborRightsSingle 所需要的 state 不同時，case1 似乎不好處理

**Comment by mark86092** [comment]
補充：這裡的問題其實不涉及到底是用 Map 或 List 存放你的小教室物件

@peteranny 我把細節補在上面＾＾

**Comment by peteranny** [comment]
原本的寫法共用的比較多，是因為我是全部小教室一起抓

不過如果我要改成單篇只抓單篇的資料，那麼分開做state就比較好

我已經決定再重寫成單篇就抓單篇，所以我就改分開吧。

**Comment by mark86092** [comment]
沒問題！

**Comment by peteranny** [comment]
我想了一下，還是覺得共用比較直覺耶，你說

>當 LaborRightsMenu 與 LaborRightsSingle 所需要的 state 不同時，case1 似乎不好處理

他們其實都是需要相同的state，也就是需要
1. fetch 所有小教室 (id+title+coverUrl)
2. (若是單篇小教室) fetch 該篇小教室

因此我還是會使用目前的資料結構

**Comment by wutingy** [comment]
Done
