### ISSUE TITLE
面試/工作經驗填寫頁 按鈕無法按一次取消

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#151]
你會推薦此工作嗎？ 的按鈕無法取消

![image](https://user-images.githubusercontent.com/1908007/27254866-46c894f6-53c4-11e7-825b-a2da80cdb129.png)

**Comment by WendellLiu** [comment]
todo: 順便加上icon

**Comment by mark86092** [comment]
Done
