### ISSUE TITLE
面試問題上傳或顯示 bug 

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#170]
剛剛在試寫面試經驗分享，讓我比較好截圖做g0v slides，發現bug
在測試站www-stage上，時間 2017.06.26 21:50 

填寫時填寫四題
![2017-06-26 9 48 34](https://user-images.githubusercontent.com/3805975/27542329-7bce3d9e-5ab9-11e7-9b30-b7636403a54d.png)

顯示只有顯示一題
![2017-06-26 9 50 16](https://user-images.githubusercontent.com/3805975/27542330-7c402698-5ab9-11e7-8a00-d07cf6d9de32.png)

**Comment by mark86092** [comment]
@WendellLiu 關於送出的部分
@chejen 關於 QA section 串 API 的部分

你們如果時間允許，麻煩看一下是否跟這個 bug 有關

**Comment by chejen** [comment]
我看了一下，API 的確只回傳了一組 QA 回來而已

2017-06-26 23:10 GMT+08:00 Yen-chi Chen <notifications@github.com>:

**Comment by WendellLiu** [comment]
是我這邊，api doc 中，interview_qas.question 與interview_qas.answer 都是字數要大於0
所以我這邊會把不過的濾掉。

確實沒有提示的情況就濾掉是有點奇怪的，或是想想UI 行為怎麼要比較合理？
但感覺上，依照這頁的這個範例，如果只填「題目」確實也應該是合理的資訊，那就是api doc 把answer 的部分限制拿掉，我再移除對應的排除規則。

**Comment by mark86092** [comment]
@WendellLiu @chejen OK, 將會去確認 api 那邊的問題

**Comment by mark86092** [comment]
@WendellLiu 會讓後端先修正這個問題！參見引用的 issue

**Comment by mark86092** [comment]
@WendellLiu 看一下新改的 api，這樣ＯＫ嗎？ https://github.com/goodjoblife/WorkTimeSurvey-backend/issues/364#issuecomment-311312075

**Comment by WendellLiu** [comment]
沒問題，ＯＫ！

**Comment by WendellLiu** [comment]
我改好了，不過需要測試機也修改完才能測。

測好再送ＰＲ。

**Comment by mark86092** [comment]
@WendellLiu 後端 Done，文件也更新： https://goodjoblife.github.io/WorkTimeSurvey-backend/master/

**Comment by mark86092** [comment]
@barry800414 可以的話試試看，沒問題麻煩 close issue
