### ISSUE TITLE
標題的字數長度限制是否太短

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#189]
目前我們的經驗分享標題是根據公司名稱自動產生，並讓使用者可以修改
想到一個問題，如果今天公司名稱本來就很長，加上`面試經驗分享`或`工作經驗分享`這幾個字後，可能就已經超過 25 字了，使用者往下拉就發現字超過了，這樣會不會有點奇怪？

可能的解法：
1. 後端放寬字數限制，改為最長 Ｎ 個字     @wutingy 覺得標題最多幾個字呢？
2. 不改，讓使用者看到提示後，自行刪字到 25 字以下
3. 不要自動產生標題，讓使用者自己打 （好處是避免大家的標題都長的很像，壞處是讓使用者覺得麻煩）
4. 自動產生標題的時候，移除掉 `股份有限公司` 之類的尾綴
或其他？

不一定要只選一個，可以並進。

**Comment by mark86092** [comment]
我想要1，不想要限制太複雜

**Comment by barry800414** [comment]
@wutingy  介面上有沒有什麼考量，標題的字數不要太多之類的嗎？

**Comment by wutingy** [comment]
我覺得 1.，字數太多介面上不太會有影響，頂多就是太難閱讀。
剛研究各內容平台，覺得限定 50 個字蠻合理的。
或是都不限。

**Comment by barry800414** [comment]
OK，那後端改成限制 1~50 字。
