### ISSUE TITLE
應該為大拇指 icon + 文字

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#198]
<img width="364" alt="screen shot 2017-07-20 at 11 57 38 am" src="https://user-images.githubusercontent.com/8353239/28399953-d3d734b4-6d42-11e7-8bc5-c23752d7b38e.png">

應該是之前 icon 還沒出，可以與填寫頁的 component 共用，再麻煩補上囉。

**Comment by wutingy** [comment]
補上設計圖
<img width="298" alt="screen shot 2017-07-20 at 12 06 48 pm" src="https://user-images.githubusercontent.com/8353239/28400163-ecfe4b20-6d43-11e7-8080-603f91863fa0.png">

**Comment by chejen** [comment]
後面的「良好」，是 1~5 都有對應的文字嗎?

**Comment by wutingy** [comment]
對～對應文字有寫在 overallRatingDialogMap 裡面

**Comment by mark86092** [comment]
close by #213
