### ISSUE TITLE
table style

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#204]
https://github.com/goodjoblife/WorkTimeSurvey/tree/master/src/css/components/table

舊官網的 table style 要完整的搬移到新官網 common/table 裡面。
包含 rwd style（重要）

**Comment by wutingy** [comment]
@peteranny 想問你有沒有時間做這個？組長會議表定 7/30 之前要完成，我來不及（還有其他的頁面）

**Comment by peteranny** [comment]
我試試看，我晚上回家看

**Comment by peteranny** [comment]
原本想說連`WorkingHourBlock`的動畫&一些style一起調，但發現這邊和舊版的架構很不同，不確定怎麼調，所以就暫時先放棄，如果這邊也需要幫忙的話我可以再看看怎麼弄
