### ISSUE TITLE
【經驗單篇】按讚問題

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#205]
在已經按讚過的頁面，重新整理，按讚會有錯誤

![screen shot 2017-07-21 at 5 44 53 pm](https://user-images.githubusercontent.com/8353239/28458479-6ea1de46-6e3c-11e7-9fea-c62d45c253ee.png)

**Comment by WendellLiu** [comment]
應該是因為重新整理後，登入狀態變成「未登入」，因此就被禁止like 了。

**Comment by WendellLiu** [comment]
這引出一個問題：是不是重新整理後就該剔除token ，前端這邊應該跟我當初存在 `sessionStorgae` 有關 Orz

**Comment by mark86092** [comment]
這個問題是因為：

SSR
--> 頁面產生（無法拿到 token，是未登入狀態的經驗，所以 redux 是沒有這個使用者按讚的資訊）
--> FB init 後得到登入
--> 未重新拿取是否按讚的資訊（這裡是 bug 所在，應該要重新取得按讚資訊）

**Comment by WendellLiu** [comment]
@mark86092 這個bug 應該就是要，在按下「讚」的當下，再重新拿取是否按讚的資訊囉？

**Comment by mark86092** [comment]
這個我是打算看到 prop 的登入狀態改變，就重新拿取按讚資訊

不意外今天會修看看

**Comment by WendellLiu** [comment]
OK, 那我找找其他bug 看看。
