### ISSUE TITLE
面試時間檢驗問題

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/GoodJobShare#210]
問題：選擇面試時間的月份，選了八月之後，再選回「請選擇」，按下送出後卻說有錯誤無法送出
預期：應該要提示要填寫完月份

問題：如果沒有先選一個再選回去的動作，結果他是會正常提示的
預期：應該要回到invalid 的狀態

**Comment by WendellLiu** [comment]
@peteranny 不曉得這樣有沒有誤解的你敘述（我有稍微整理，並且化為兩個）

**Comment by mark86092** [comment]
@peteranny 確認有解決後，麻煩 close issue
