### ISSUE TITLE
分享面試經驗後的面試經驗頁面的「返回列表」卻是回到填寫頁

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/GoodJobShare#224]
在分享面試經驗之後送出成功，會跳轉到該面試經驗頁，該頁最下方有個「返回列表」，但按下去其實只是回到上一頁，在這個例子就變成填寫頁。然而這裡預期應該是到真正的列表，所以這邊在使用者經驗上來說會扣分

![2017-07-25 10 58 06](https://user-images.githubusercontent.com/7566586/28578780-47234d38-718d-11e7-951e-9f08de44daf1.png)

**Comment by mark86092** [comment]
這個返回列表：目前可以直接回到列表頁面做修正

**Comment by WendellLiu** [comment]
update: 

簡單的方式就是寫死，讓他固定到 `/experiences/search` ，但這樣會失去goBack 可以回原位、原狀態的能力。

希望獲得上一頁的path 應該就能判斷，但查後似乎無法直接辦到（真意外），所以繼續先往這邊查，真的不行再看大家的意見了。

**Comment by mark86092** [comment]
不知道有沒有辦法透過 router 得到

**Comment by WendellLiu** [comment]
目前看起來真的很意外地沒辦法直接得到上一頁的location 資訊 ＸＤ

**Comment by WendellLiu** [comment]
@mark86092 想到比較不舒適但能完美解的方式，就是帶上query string 來判斷。
以這個case ，最小幅度的帶入就是在/experience/search 連進去的地方帶入一個 `back=1` ，用這個來判斷要goBack() 還是push 固定路徑；至於其他地方相對都不該用goBack() ，那就不需要動。

**Comment by WendellLiu** [comment]
update:

結果我發現有個問題是 `ExperienceBlock` 除了在列表中，還會在LandingPage 使用，這樣就沒辦法有效的判斷是在列表還是LandingPage 進入了...
（但這樣從填寫頁進去倒是可以解決，就是變成從LandingPage 那邊也會回到LandingPage 而不是列表）

**Comment by wutingy** [comment]
新增一個 props 為 to 呢？從 ExperienceBlock 那層決定要不要帶 query，我希望都可以回到列表。

**Comment by WendellLiu** [comment]
剛洗澡一個靈光一線修正了，從 `ExperienceBlock` 帶 `backable` （是你的意思嗎？），然後只有從ExperienceDetail 那邊render 才會帶backable=true 進去。
