### ISSUE TITLE
搜尋頁的 UX

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#234]
這個不急這次上，可以再討論。
問題：現在看到找到 1 筆相關資料，但是加上薪資工時其實不止 1 筆，會覺得有點奇怪

![screen shot 2017-07-26 at 11 29 21 pm](https://user-images.githubusercontent.com/8353239/28742627-905a7f08-7467-11e7-86e6-bb1bc513db48.png)

### 期望
- 右側：`搜尋“日月光”：找到 N 筆面試工作經驗，N 筆薪資工時`
- 左側：label 後面加上資料筆數 `(2)`
- 沒有資料的話 disabled 該 checkbox（現在是只要有搜尋東西就 enabled）

**Comment by barry800414** [comment]
剛開了一個issue #236 關於搜尋頁 SEO 優化，跟這一篇應該會有關。
