### ISSUE TITLE
搜尋頁 SEO 優化

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#236]
目前搜尋頁的部分，在使用者打字並搜尋後，網址並不會變更，這對SEO不利。
假設使用者以公司查詢資訊，我們可以把這一頁想成 `這一間公司的資訊整合頁`，包含了薪資、工時、面試經驗以及工作經驗。如果是以職稱搜尋，也是想成 `這一個職稱的資訊整合頁`。

根據之前來教我們如何SEO投影片內容的建議。 如果要改進 SEO，可以採取以下的措施：
- [x] 以公司或職稱搜尋後，會有獨立的網址 e.g. /experiences?company=goodjob 。 搜尋後的頁面也要做 server-side rendering
- [x] 搜尋後，出現 h1, h2 等標題等級的文字，直接寫 `OOO 公司的工時、薪資、面試經驗、工作經驗資訊`。搜尋後的頁面，標題為 `OOO 公司的工時、薪資、面試經驗、工作經驗資訊`。
- [ ] 搜尋的結果建議要分頁，且每一頁的內容盡可能固定，相對穩定的結構有利於爬蟲解析。 `待確認`

這個尚需討論，非上線前 TODO

**Comment by chejen** [comment]
目前 open 的 #236 (這個跟 #132 是不是同一件事? 上個月其實有討論到精進 SEO 這項 task，但還沒討論出網址的規則) 跟 #234 ，以及 closed 的 #198，這 3 個都是搜尋或是單篇顯示的頁面，我來調整。但現在未 merge 的 PR 中，有幾個是正在精進這兩個頁面的，所以我應該會等相關 PR merge 後再傳修改的程式上來。

**Comment by barry800414** [comment]
跟 #132 很相關，應該說 SEO的前提就是要有 unique 的網址
不過 @chejen 這件事真的不急，我覺得可能要到九月份g0v計畫結束後，我們才有辦法做。
接下來還有 檢舉、個人管理頁、關鍵字＆文章推薦的部分要在八月底完成。
