### ISSUE TITLE
同意使用者條款的勾勾旁文字，未有超連結，未加上發文留言規則

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#237]
我指的是面試、工作經驗填寫表單下方，以及留言區，打勾勾同意使用者條款的文字，沒有超連結，也未加上發文留言規則
![2017-07-30 12 14 51](https://user-images.githubusercontent.com/3805975/28746307-33a374f4-74bc-11e7-91a1-f01493ecd0d9.png)
![2017-07-30 12 15 15](https://user-images.githubusercontent.com/3805975/28746309-388574c2-74bc-11e7-87fd-19a65641b0ee.png)

請修改成：
我分享的是真實資訊，並且遵守本站[發文留言規則](https://www.goodjob.life/guidelines)、[使用者條款](https://www.goodjob.life/user-terms)以及中華民國法律

**Comment by mark86092** [comment]
這個我連同 2 個表單、留言、就網站一起檢查

**Comment by WendellLiu** [comment]
「使用者條款」連到 `/user-terms` 。這我送一個ＰＲ

**Comment by barry800414** [comment]
請修改成：
我分享的是真實資訊，並且遵守本站[發文留言規則](https://www.goodjob.life/guidelines)、[使用者條款](https://www.goodjob.life/user-terms)以及中華民國法律
