### ISSUE TITLE
表單文字：為什麼需要 Facebook 帳戶驗證？

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#240]
沒有連結，或連結不可按

![image](https://user-images.githubusercontent.com/1908007/28750388-bd67d68a-751b-11e7-90c9-7a8f1a8581db.png)

**Comment by WendellLiu** [comment]
是沒有連結。忘記這塊了，沒有跟大家要這個，所以是要連到？ /guidelines ?
