### ISSUE TITLE
某些 Modal 在行動裝置跑版

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#258]
![image](https://user-images.githubusercontent.com/1908007/28807404-ed323bfc-76a7-11e7-9035-cb9bf97aba59.png)

**Comment by wutingy** [comment]
這我昨天的 pr 有改到

**Comment by mark86092** [comment]
不過我切過去看還是這樣耶，我再檢查一次

**Comment by mark86092** [comment]
on master in `src/components/common/button/ButtonSubmit.js`
![image](https://user-images.githubusercontent.com/1908007/28810082-5d53b4d0-76ba-11e7-995c-3675cf67cd84.png)

![image](https://user-images.githubusercontent.com/1908007/28810086-64f3b938-76ba-11e7-96f6-55c4d2259f9f.png)

前者的 Modal 有點小問題，我改個比較適當的標題

**Comment by WendellLiu** [comment]
@mark86092 因為那個新加進去，我現在參考 @wutingy 的方式套用。

**Comment by WendellLiu** [comment]
@mark86092 done!

**Comment by mark86092** [comment]
我等等來跑進來看看
