### ISSUE TITLE
填寫完畢的進一步填寫詢問

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#26]
根據 @barry800414  提出的需求，填完表單希望可以問他是否需要填其他兩項，點了「是」的話，就把他剛剛填的資料帶過去。

算是 enhancement。需要設計支援。

**Comment by barry800414** [comment]
這個好像是很久以前有一次在notch cafe討論的內容。主要是填寫不同資料的時候，有一些共用的欄位，乾脆鼓勵他順便填完其他表單，對我們來說是充實資訊。

不過這個，我覺得前端可以考慮是否實作這個功能&開發的先後順序。
