### ISSUE TITLE
單篇經驗顯示頁，內文的斷行會被吃掉

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#262]
原本輸入的時候，是有換行的
但顯示的時候就變這樣，覺得嚴重影響閱讀
![2017-08-01 11 58 42](https://user-images.githubusercontent.com/3805975/28834674-83f84424-7715-11e7-95e6-4bd8f6ae0219.png)

@wutingy

**Comment by wutingy** [comment]
要在存 value 時想辦法將 \n 轉成 <br /> 之類的，render 就不能只 render string 了

**Comment by barry800414** [comment]
react 是有個 `dangerouslySetInnerHTML` ，但就如其名它有危險性，有心人士可以塞 js 的 code在裡面。
一種做法是，把content 先用 `\n` 切開成一個array，然後一個一個 render 出來。

**Comment by mark86092** [comment]
我有看到這個：https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

white-space: nowrap;

> Collapses whitespace as for normal, but suppresses line breaks (text wrapping) within the source.

看起來就是如果給他換行，就會換行

不知道可不可

**Comment by wutingy** [comment]
我來開 ＰＲ
