### ISSUE TITLE
留言的部分如果也有換行，顯示的時候要換行嗎？

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#268]
![2017-08-02 10 51 55](https://user-images.githubusercontent.com/3805975/28879713-72bd42fc-77d5-11e7-8897-d66f9ef5bb1e.png)

目前留言的部分，如果有輸入的時候有換行也不會顯示換行。要顯示嗎？

自己目前想得最佳solution，用 replace 把內文的連續多個換行換成單個換行，然後再用目前本文顯示換行的方式顯示。（本文＆留言都適用）

**Comment by mark86092** [comment]
> 自己目前想得最佳solution，用 replace 把內文的連續多個換行換成單個換行，然後再用目前本文顯示換行的方式顯示。（本文＆留言都適用）

WHY?

**Comment by barry800414** [comment]
因為如果使用者故意打了很多個換行，也直接顯示換行的話，會把畫面拉得很開

**Comment by wutingy** [comment]
先用與內文一樣的處理方法，有時間再處理亂打的。
