### ISSUE TITLE
填寫表格中 “＋” 按鈕使用者可能沒有注意到

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#269]
我看了好幾篇分享，都有個特徵，就是只有一段。
我在想有沒可能使用者沒注意到那個 + 的按鈕可以按，就只打了一段？

我的 proposal :  
1. ＋的按鈕預設為黃色 
2. ＋旁邊顯示"新增段落"
3. 預設的空白段落刪掉

三個都做

**Comment by barry800414** [comment]
使用者（我朋友）feedback:
1. 沒有我特別講的話，沒有發現＋號按鈕
2. 覺得要填寫標題很麻煩
3. 有＋號可以新增的話，為什麼還要第一個都空白的？

**Comment by barry800414** [comment]
剛統計了一下，扣掉我自己留的2篇， 16 篇裡面有 10 篇只有一段。

**Comment by wutingy** [comment]
我也有發現，我提三個修改：
- 自訂段落不要標題
- 新增預定段落的標題可以修改
- 按鈕重新設計（等等出圖）

**Comment by barry800414** [comment]
> 自訂段落不要標題 

這個後端的 API 目前無法 accept ，如果要這樣改，後端要修改

我的想法是，不要有預設段落，直接有個明顯的 新增段落 按鈕讓使用者去按

**Comment by wutingy** [comment]
A. 我認為改為標題非必填會比較好，因為使用者會覺得，上面已經有標題了，為什麼還要填一次標題？或許他就只有一段話想說。

B. 讓使用者自己按新增段落是可以，但是就是會有點煩。因為他點開新增段落，還要看一堆字，想辦法理解那些段落會長怎樣，是一個障礙。

**Comment by wutingy** [comment]
然後我覺得大家都是用手機填，手機的流程要再順過，我先改「按鈕明顯」這個點，其他的繼續討論。

**Comment by barry800414** [comment]
OK！ 我也覺得 "按鈕明顯" 這件事要先做，剛剛再問了兩個朋友，他們也沒有發現orz。
我想問這個有可能今晚上去嗎？

另外：
> A. 我認為改為標題非必填會比較好，因為使用者會覺得，上面已經有標題了，為什麼還要填一次標題？或許他就只有一段話想說。

這個我同意！ 不過，後端上面會有兩種選擇：
1. 只有第一段不需要寫標題
2. 每一段都不用寫標題

需要做個決定。
