### ISSUE TITLE
autocomplete 優化

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#274]
可以在 focus 時先給幾個選項，讓使用者知道有 autocomplete 嗎？因為他需要一點時間才會出來

**Comment by WendellLiu** [comment]
想問詳細一點：

因為你的敘述感覺有兩個問題，依照目前的狀況在起始狀態時，onFocus 沒有東西是因為沒有跟後端要資料。看是要再一個依據「某邏輯」（例如最常用項目）的api ，讓我在空白時request 還是如何。

而「一點時間才出來」這件好像跟起始onFocus 無關，這是作debounce 的效果，為了不要過度request api。

所以我不確定你想解決的是，過長的debounce time 還是在沒有文字時也要有些選項可選？

**Comment by wutingy** [comment]
是「在沒有文字時也要有些選項可選」。

因為希望使用者可以馬上理解這是可以 autocomplete 的欄位，舊的官網是使用「最近留下的」資料來做，我覺得蠻清楚的。

**Comment by WendellLiu** [comment]
如果這樣的話，那我再確認一下之前的api 再接上即可。

**Comment by mark86092** [comment]
@WendellLiu @wutingy  我想 address 另外的問題，我開在別的 issue，比較長的東西要寫
