### ISSUE TITLE
編輯資料頁面

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#278]
因為是列表頁，設計上只顯示文章標題即可，不需要其他資訊。
黃色留言請看過，有問題可以留言在 invision 或是這邊。

[個人頁面](https://projects.invisionapp.com/d/main#/console/10208710/248409546/preview)
[個人頁面](https://projects.invisionapp.com/d/main#/console/10208710/248411086/preview)
[編輯留言](https://projects.invisionapp.com/d/main#/console/10208710/248410221/preview)

- 編輯留言不一定要這次做，只是先想好流程。
- 「面試・工作經驗」「薪時」編輯畫面，我想直接使用留資料的畫面（標題改一下），但是因為「薪時」頁面還沒移到 react，想說先提供隱藏功能就好？

**Comment by barry800414** [comment]
`編輯留言不一定要這次做，只是先想好流程。`   => 後端這次還沒做這個功能，想說之後再做。
`「面試・工作經驗」「薪時」編輯畫面，我想直接使用留資料的畫面（標題改一下），但是因為「薪時」頁面還沒移到 react，想說先提供隱藏功能就好？`  => 對的，先提供隱藏功能即可，不過介面是不是還沒出？

另外，經驗分享編輯的功能，我記得我們說先不做、先做隱藏的功能？

**Comment by wutingy** [comment]
> 經驗分享編輯的功能，我記得我們說先不做、先做隱藏的功能？

ok，我忘了 會議記錄是寫都有。

> 不過介面是不是還沒出？

介面出了啊，有隱藏的按鈕。
