### ISSUE TITLE
單篇文章分享 func

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#281]
<img width="522" alt="screen shot 2017-08-20 at 2 51 46 pm" src="https://user-images.githubusercontent.com/8353239/29492720-2c3620d4-85b7-11e7-90d4-c4b47be2abe3.png">

**Comment by mark86092** [comment]
這個小教室有出過，有圖案的話，功能可以拿過來

**Comment by barry800414** [comment]
@wutingy 這個你可以出個圖給我嗎？
