### ISSUE TITLE
Style Guide 當中的 className

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#29]
https://projects.invisionapp.com/d/main#/console/10208710/225568940/preview

https://projects.invisionapp.com/d/main#/console/10208710/225568941/preview

https://projects.invisionapp.com/d/main#/console/10208710/225568942/preview

這幾個部分我覺得蠻常用的，需要先實做出來共用

**Comment by wutingy** [comment]
補充：
worktime 的 font 在這邊，可以參考其架構。
不過我覺得不用寫 mixin，用 class 定義就好。

**Comment by mark86092** [comment]
Done
