### ISSUE TITLE
頁面上是不是沒有進入 /me 的頁面？

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#296]
我在 #294  commit 2810dc3a43ba0895712e2a133f2031e865599ca3 上測的
介面上找不到地方可以進去 /me 的頁面

**Comment by chejen** [comment]
這個我在發 PR 的時候是有在想要不要加，但因為 issue #285 有列這個，不確定是不是有要統一作設計還是怎樣，如果我可以獨自先加上個人頁面的連結的話，我晚點加上去。

**Comment by mark86092** [comment]
@chejen 這個我來發吧

**Comment by wutingy** [comment]
hey  #285 這個我會負責，我排今天來做！（sorry 有點晚了

**Comment by wutingy** [comment]
done
