### ISSUE TITLE
單篇經驗頁面 需要提示已經隱藏/找不到

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#297]
我把這一篇面試經驗隱藏起來，再貼網址進來，發現沒有提示的字樣。

![2017-09-06 9 27 38](https://user-images.githubusercontent.com/3805975/30114391-4e21f182-934a-11e7-9bbc-8bfc035d8d71.png)

**Comment by chejen** [comment]
預期應該是要顯示什麼，本篇已被隱藏之類的嗎?

**Comment by mark86092** [comment]
@chejen 這個希望可以在 API query 拿不到 experiences （404）的時候，提示本篇已被隱藏或找不到

**Comment by barry800414** [comment]
@chejen  我剛彥齊有討論，後端這邊回 404 的時候也會有 error message，可以從 error message判定是被隱藏的狀態。

然後我目前想要顯示的文字是 `本篇文章已經被原作者隱藏，目前無法查看`

**Comment by mark86092** [comment]
@barry800414 @chejen 後端再補上會是什麼 error message

**Comment by chejen** [comment]
got it

**Comment by barry800414** [comment]
@chejen 不好意思，更正一下。如果文章被作者隱藏，會回傳 status code 403 。
就麻煩你顯示一下  `本篇文章已經被原作者隱藏，目前無法查看`  了！

**Comment by chejen** [comment]
ok ~~ 不過我在 local 測試，直接輸入單篇的 url 的話，server 會有 promiseRejection 的 error，進不去該頁面，@barry800414 測試的時候不會嗎?

**Comment by mark86092** [comment]
@chejen 沒錯，所以可以的話，catch 這個 error，判斷是 403 後做相對應的 state 處理

**Comment by chejen** [comment]
A都，我的疑問其實是，即使有 error，但看 @barry800414 的截圖，他是有進到畫面的；但我的 error 造成我連畫面都進不去 @@  ... 沒關係，我再測一下好了，搞不好是我的環境被玩壞了

**Comment by mark86092** [comment]
喔喔，我猜他的情況應該是 link 進去（但我不知道怎麼進去的），不過你的狀況是會發生的沒錯（透過  SSR, 拿到 Promise reject，需要處理）

**Comment by chejen** [comment]
#299 已作相關調整
