### ISSUE TITLE
介面上的修正

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#309]
目標是增加到分享頁的流量

### First Priority
- [x] /share 那一頁加上文案
- [x] 加強 share button （Header: 改成 ”立即分享“，手機版移出來）
- [x] 小教室位置調換  /labor-rights ：留下資料區塊往上移、電腦版固定在左邊

### Second Priority
- [x] /time_and_salary 頁，橫幅廣告「你已經看了 100 筆了，該留了拔 ><」「要關站了，罷拖罷拖！」、放好笑的訊息、苦情牌（hover 出現小白錄音）
- [x] /experiences 頁，左邊加 Banner，搜尋插橫幅廣告
- [ ] 團隊成員分享在專案內的經驗（另外寫死）

### Third Priority
- [x] 可能可以用的 element: 跟使用者對話 （最近在線人數、資料數、我們的目標）
- [x] 募資條：先瞄準經驗分享
- [ ] 關於我們可以變成募資（資料）的page 
- [ ] /experiences/:id 你可能也想看上方加廣告 banner

設計會整理，再跟行銷組要文案。

**Comment by wutingy** [comment]
[文案1](https://invis.io/TYAAY1QR4#/257018208_company-V1) 有左、中、下三個區塊。
文案2
[文案2](https://invis.io/TYAAY1QR4#/257020635_working-V1) 中間
[文案3](https://projects.invisionapp.com/d/main#/console/10208710/257036456/preview) 中間

**Comment by barry800414** [comment]
@wutingy  有連結的我都回覆了！  謝謝妳！！
不過我想問，單篇小教室頁的Call to action，是在這次修改範圍內嗎？

**Comment by wutingy** [comment]
@barry800414 對，我補上：[小教室單頁](https://projects.invisionapp.com/d/#/console/10208710/257210454/preview)，不過這個 fixed 左側的要算一下位置，做起來有點麻煩就是了～

**Comment by b99504085** [comment]
我剛看完文字的部分了，我覺得沒甚麼要改的~~
募資方面的文字我自己是寫了一點，但是不知道能擺哪，覺得原本的也很好
-
邀請你參與我們的五百筆募資計畫
分享你的眼界，讓彼此找到更好的工作
-
你的每筆資料，都至關重要
