### ISSUE TITLE
/share 文案

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#310]
![screen shot 2017-09-19 at 4 31 40 pm](https://user-images.githubusercontent.com/8353239/30582953-1d769192-9d58-11e7-83dd-329b3134f36f.png)
**to: Wei-chu, 耘樟**
新增的文案有 A, B, C, D 四處，如要修正請直接留言在下面，謝謝！

**Comment by b99504085** [comment]
我先分享對這版本的看法:
1.一堆顏文字表情真的有俏皮到XD
2.A區域應該可以每個問句單獨一行?
3.C區域，冤枉的"枉"

**Comment by peteranny** [comment]
我想建議下面三個用第一人稱寫～

1. 我的公司常加班、薪水又少，我可以分享好讓別人別踩雷！
2. 我對找工作的面試有點經驗，我可以分享，減少大家走冤枉路！
3. 我想推薦我的公司、或是我想爆公司的料！

**Comment by wutingy** [comment]
麻煩再請 @barry800414 做最後文案確認，謝謝！

希望這週可以上去～

**Comment by barry800414** [comment]
我的理解是
    A
B C D 
這樣分區

1. A 區每一句話斷行會比較好
2. A區文案的標題建議改成 `我有話想說！`
3. C區 "冤枉" 路
4. 要不要用第一人稱我覺得都可以！

**Comment by barry800414** [comment]
@wutingy 我要直接給你確定的文案，還是妳決定即可？

**Comment by wutingy** [comment]
收到～我覺得一下你一下我有點錯亂，
都可以的話就統一以「第三人稱」的方式囉，謝謝價壓的回饋。

看起來是小改，那我發 PR 給你～
