### ISSUE TITLE
因應 route 改變的設計需求

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#312]
- pagination design (scroll, fixed)
- 更改 h1
- 設計「薪資工時」連結的呈現方式（在上方）

**Comment by barry800414** [comment]
@wutingy  我剛想到，我們忘記討論薪資工時分頁的地方...
這部分也是要做的對嗎？

**Comment by mark86092** [comment]
@barry800414 這塊可能也跟 @peteranny 目前改寫的有關

**Comment by wutingy** [comment]
我會再把設計補上，有問題需要討論再 call 大家

**Comment by wutingy** [comment]
面試、工作經驗：[設計](https://projects.invisionapp.com/d/main#/console/10208710/257018208/preview)
順便偷渡了募資條看看～

薪資工時：設計（not done）

**Comment by barry800414** [comment]
@wutingy  我把 feedbacks 都留在 invision 了！
插圖都好可愛！！  整個很喜歡！ （題外話：昨天報導者的記者一直說我們介面很好看、好用！）

另外，我截個圖給 @mark86092 
![2017-10-06 11 34 34](https://user-images.githubusercontent.com/3805975/31285929-3cbfebf2-aa82-11e7-82f0-f2e78f711450.png)

面試、工作經驗的部分，目前 @wutingy 設計是用上一頁/下一頁的按鈕的方式，想確認 SEO 應該沒問題？

**Comment by barry800414** [comment]
TODO:
  - [ ] 經驗分享查詢頁，未設關鍵字的時候，要移除拉到底的 infinite scroll
  - [ ] 經驗分享頁的頁碼要串資料

**Comment by wutingy** [comment]
@barry800414 這是設計的 issue 已經完成了，我先關掉，todo 你再另外開
