### ISSUE TITLE
Proposed routing

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#313]
1. 列表

```
/experiences/latest --> 最新
/experiences/hot --> 熱門 (不知道要用什麼英文)
```
    
2. 搜尋

```
/experiences/search?job-title=aaa
/experiences/search?company=aaa
```

* 過濾器

```
?type=interview,work
?p=1 (start from 0 / 1 ?) [預設值為第1頁]
```

**Comment by mark86092** [comment]
@WendellLiu Routing draft, please give recommendation

**Comment by WendellLiu** [comment]
我比較擔心的是搜尋，因為這樣會變成兩個都可以輸入，那情況好像不是目前可接受的。

```
/experiences/search?keyword=aaa&keyword_type=job-title
/experiences/search?keyword=aaa&keyword_type=company
```

這樣可以好一點，雖然比較囉唆

**Comment by WendellLiu** [comment]
其他目前沒意見，`hot` 應該也行（稍微查一下），雖然感覺有更潮流的用法，但暫時先這樣也無妨。

**Comment by mark86092** [comment]
```
/experiences/search?keyword=aaa&keyword_type=job-title
/experiences/search?keyword=aaa&keyword_type=company
```

這個ＯＫ

hot 我在想用 featured 這詞呢？主要是強調我們有在主打這些經驗

**Comment by WendellLiu** [comment]
好像可以，但意味有點不同，感覺可以跟其他人討論這部分。

**Comment by mark86092** [comment]
> 但意味有點不同，感覺可以跟其他人討論這部分。

yes, 問問 @barry800414 的意見

**Comment by barry800414** [comment]
1. 熱門的英文，可以用 `popular` ，搜尋的參數也是用 popular 
2. page 建議從 1 開始，因為頁碼上會用 1, 2, 3, 4 ..，從 1 開始比較直覺

**Comment by WendellLiu** [comment]
popular + 1

**Comment by mark86092** [comment]
> 頁數就從1 開始吧

當 p = 1 時，需考量重複的頁面（p=1 或無 p）：
1) redirect 回沒有 p 的參數
2) 產生 canonical link 時將 p 移除

我 prefer 2 > 1

popular + 1

**Comment by barry800414** [comment]
3. 我反而建議用這個：
```
/experiences/search?job-title=aaa
/experiences/search?company=aaa
```
網址比較短又明確，如果使用者打 `/experiences/search?job-title=aaa&company=bbb` 那就跳 404 或挑一個去搜就好，這個不會是一般使用者會使用到的狀況，而是有點工程背景的人才會這樣改。

如果真的要用兩個參數，希望可以簡短一點：
`/experiences/search?q=aaa&type=job-title`
`/experiences/search?q=aaa&type=company`

q 是 query word, type 是搜尋種類

**Comment by barry800414** [comment]
@mark86092 

> 產生 canonical link 時將 p 移除

這邊我有點沒懂，是什麼意思？

**Comment by mark86092** [comment]
@barry800414 

eg:

若頁面是 `/experiences/latest?p=1` or `/experiences/latest` 那，canonical link 都是 `/experiences/latest`

**Comment by WendellLiu** [comment]
@barry800414 

不過其實我的看法是，一般來說不會有人去打網址，所以其實還好。
主要是給搜尋引擎跟我們自己的進入點用。

**Comment by WendellLiu** [comment]
@mark86092 

我不懂的是，為何要只能有一種而不是都行。

**Comment by barry800414** [comment]
@mark86092  

> 若頁面是 /experiences/latest?p=1 or /experiences/latest 那，canonical link 都是 /experiences/latest

覺得好啊


@WendellLiu 
> 不過其實我的看法是，一般來說不會有人去打網址，所以其實還好。
> 主要是給搜尋引擎跟我們自己的進入點用。

你的意思是，分成 keyword & keyword_type 兩種參數，對搜尋引擎來說比較好嗎？
還是你的意思是，用一個參數或兩個參數都可以？

**Comment by WendellLiu** [comment]
@barry800414 
我的意思是，萬不得已我也不想用兩種，就太囉唆。但那可能只是一個感覺，對於實質上我上面提的兩點，其實都沒差別吧。

**Comment by mark86092** [comment]
我是理解成：對於不同網址實際上頁面內容一樣，會想要讓搜尋引擎去知道其實那兩頁是一樣的（by canonical link），所以當有人 reference 到不同網址時，可以算在一起的檢索效果

https://support.google.com/webmasters/answer/139066?hl=zh-Hant

這邊是建議這樣做，我主要也是參考這個

**Comment by mark86092** [comment]
> 不過其實我的看法是，一般來說不會有人去打網址，所以其實還好。

yes 我覺得網址都還ＯＫ，這兩種我都覺得很清楚

**Comment by WendellLiu** [comment]
@barry800414 
因為有一個重點是，實作上query 要導向404 比較麻煩，所以我會覺得query string 應該怎麼打都是有內容的（頂多有些硬打的qs 是無效用的），但如果因為打了什麼qs 則404 感覺比較奇怪。

**Comment by mark86092** [comment]
> 實作上query 要導向404 比較麻煩

幫補充：在 SSR 方面，可以因為"路由"找不到而產生 404, 301 ... ，不過 query 這個就沒辦法了

**Comment by WendellLiu** [comment]
@mark86092 
對這就是我說的意思，路由基本規則，query 的地位就是比較低。

**Comment by WendellLiu** [comment]
所以當然可以硬寫在react code 中，但就比較硬寫。

**Comment by barry800414** [comment]
> 實作上query 要導向404 比較麻煩

咦，會比較不好寫嗎？
拿到參數後檢查 query 是不是 `job-title`, `company` 兩個都給，是的話 document.location =  404 頁面的 route 即可？ 
或者是就吃其中一個參數（e.g. company 優先），我也覺得ＯＫ，主要是我覺得網址能夠簡潔一點比較好。


用這個還有一個好處是，未來如果有某個公司的某個職稱的資料頁面，就兩個都給就可以擴充了
```
/experiences/search?job-title=aaa
/experiences/search?company=aaa
```

**Comment by WendellLiu** [comment]
@barry800414 
不好寫是說在routing 設定上沒辦法直接做到，而是要有個container 去監聽的感覺。

**Comment by barry800414** [comment]
我總結一下：

1. 列表

```
/experiences/latest --> 最新
/experiences/popular --> 熱門 
```
    
2. 搜尋

Option 1 :
```
/experiences/search?job-title=aaa
/experiences/search?company=aaa
```


Option 2 :
```
/experiences/search?keyword=aaa&keyword_type=job-title
/experiences/search?keyword=aaa&keyword_type=company
```

韋銘 prefer option1 ，但 option 2 也可以，只是希望參數名稱可以改為 q & type
晏成 prefer option2 

* 過濾器

```
?type=interview,work
?p=1 (start from 1) [預設值為第1頁]   //p=1 時 canonical link 為沒有 ?p=1 的連結
```

**Comment by barry800414** [comment]
這樣關於搜尋的route 設計，兩種選擇我覺得都可以，不過如果是上述的 option 2，會希望參數名稱可以短一點。 

以上是我的 feedback，但還是直接給 @mark86092 @WendellLiu 你們決定即可！

**Comment by WendellLiu** [comment]
q 我覺得沒問題，我是怕type 以後會重複，但也沒問題。

**Comment by mark86092** [comment]
> 咦，會比較不好寫嗎？
> 拿到參數後檢查 query 是不是 job-title, company 兩個都給，是的話 document.location = 404 頁面的 route 即可？

其實我覺得可以拋出另外的 issue 來解決遇到 302/404 的時候, SSR 與 client 要怎麼處理：

1) Route mismatch 404 （目前 SSR 會看到正常的 NotFound Page，送出 200, 沒送出 404）
2) API fetch 404（目前各 component 獨自處理，SSR 沒送出 404）
3) Component 觸發 redirect (都未處理)

回應 @barry800414 提到的，拿到參數檢查 query 我隨意猜測應該是在 componentDidMount 的時候觸發 router state 改變，然後達到 redirect 的效果，也就是寫在 react 的 component 中

**Comment by WendellLiu** [comment]
先對原題做個結論好了。

1. 列表
```
/experiences/latest --> 最新
/experiences/popular --> 熱門 
```
2. 搜尋

```
/experiences/search?q=aaa&type=job-title
/experiences/search?q=aaa&type=company
```

3. 過濾器

```
?type=interview,work
?p=1 (start from 1) [預設值為第1頁]   // p=1 時 canonical link 為沒有 ?p=1 的連結
```

@mark86092 @barry800414 
這個版本應該是有共識了？

**Comment by WendellLiu** [comment]
@barry800414 @mark86092 
抱歉，突然看到一個問題，昨天沒注意到：

這三個其中的`列表`，為何是
```
/experiences/latest --> 最新
/experiences/popular --> 熱門 
```

這樣意思是不會再有 `/experiences/search` 這個path 了嗎？
這個項目需要跟其他不一樣，不使用qs 達到效果，有什麼目的嗎？

**Comment by mark86092** [comment]
我如果沒記錯的話，原本的頁面有幾個行為：

1. 不搜尋任何 company, job-title，但是有排序的差別 (由新到舊 or 熱門)
2. 搜尋某些關鍵字（company or job-title），這時候排序固定為（由新到舊）

所以

```
/experiences/latest --> 最新
/experiences/popular --> 熱門 
```

我是想指不搜尋任何東西（company/job-title 都不指定），特別針對排序方式不同而取名的，算是 shortcut

**Comment by WendellLiu** [comment]
但因為沒有不照「最新」也不照「熱門」的這種狀態，除非就是要把 `/experiences/search` 給拿掉，否則這樣混用還蠻奇怪的。

**Comment by mark86092** [comment]
@WendellLiu 你心中想的路由是什麼樣？

**Comment by WendellLiu** [comment]
`/experiences/search?sort=latest`
`/experiences/search?sort= popular`

**Comment by barry800414** [comment]
其實我覺得晏成提的：
```
/experiences/search?sort=latest
/experiences/search?sort= popular
```
也滿好的！ 其實跟薪資工時那邊很像

**Comment by barry800414** [comment]
@mark86092  這個可以 close 了？

**Comment by mark86092** [comment]
Done
