### ISSUE TITLE
小教室 banner 插入

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#319]
@peteranny 我先 assign 給你，因為這幾頁之前是你負責，有疑問再討論喔。
[首頁設計](https://projects.invisionapp.com/d/main#/console/10208710/257036456/preview)
[內頁設計](https://projects.invisionapp.com/d/main#/console/10208710/257210454/preview)
[首頁出圖](https://image.goodjob.life/banners/banner3_2x.jpg)
內頁的 banner 在另外一頁有做好了，直接引用即可。path: `ExperienceSearch/Banners/Banner1`
內頁想要做成固定在左邊，可能會有點麻煩，有時間再做即可，[參考效果](https://theinitium.com/article/20171020-strangers-syriaguest/)。

另外，眼睛的圖片連結在[這裡](https://image.goodjob.life/banners/eyes.png)
![screen shot 2017-10-20 at 3 38 36 pm](https://user-images.githubusercontent.com/8353239/31810023-d5429d76-b53f-11e7-8d0e-46dcb24cade7.png)

謝謝！

**Comment by barry800414** [comment]
PR: #320  #323
