### ISSUE TITLE
關於廣告 banner 或 progress bar 的連結

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#321]
想討論一下，目前所有要塞進去的廣告 banner ＆ progress bar 的連結，要連到哪一個地方？

1. /share： 意即三個選項的頁面
2. 固定 /share/work-experience 或 /share/interview，比例可以分配一下
3. /share/work-experience 或 /share/interview 程式上隨機一個

我是 prefer 3，因為現在的目的是導到面試或工作經驗表單頁，廣告的文案上也都有寫，其實沒有必要再跳 /share 間接抵達。
不過，直接就進到 /share/work-experience 或 /share/interview，沒有任何文案的話，確實也有可能離開率就很高，所以是想說，表單頁上面加一段短短的文案，鼓勵使用者去填寫，應該會好一些。

如果是大家同意 3 的話，不需要要現在就這樣改。建議是目前都先導到 /share ，下一波修改再改。

**Comment by mark86092** [comment]
@barry800414 討論的時候有提到，跳到 `/share` (opt 1) 可能會讓使用者要選好幾次的觀感

所以還是 random 跳一個，或是目前主打 工作經驗，就到工作經驗的填寫頁去

**Comment by peteranny** [comment]
直接跳經驗有點大@@ 不過可以觀察一下跳出率，說不定點進去的人都願意寫也不一定

**Comment by chejen** [comment]
覺得 3 OK，可以試試看

**Comment by WendellLiu** [comment]
3 可以！

**Comment by barry800414** [comment]
補充一下數據，這個是 /share 前後一頁的比例，意即從哪邊進到 /share ，進到 /share 後下一頁到哪邊
![2017-10-23 8 44 24](https://user-images.githubusercontent.com/3805975/31889609-0ce70144-b7c6-11e7-88b1-e1ff61c4cb7d.png)

可以看得出來到薪資/首頁的比例佔了將近一半，進到面試/工作經驗表單的，總共只有 25%。
所以想要試試看 3 。

**Comment by barry800414** [comment]
@wutingy  你覺得呢？

1. 現在先導到 /share ，之後再隨機導到面試及工作經驗表單頁
2. 現在先導到 /share ，之後再隨機導到面試及工作經驗表單頁，並且在表單加一小段文案
3. 現在就隨機導到面試及工作經驗表單頁，再觀察表單頁離開率

**Comment by wutingy** [comment]
覺得 3 可以！

**Comment by mark86092** [comment]
那就

1. header 上方的進度條 UI 需要修正連結
2. Banner 需要修正連結
3. 偽小教室廣告修正連結

這幾個地方要改了
