### ISSUE TITLE
薪時查詢頁面TODO

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/GoodJobShare#336]
- [x] 每n筆資料顯示一個callToAction
- [x] 隱藏前1%極端資料
- [ ] 將 /time-and-salary/latest --> 這種頁面加上頁碼的功能 #329 
- [x] 公司名稱與職稱的欄位，有連結可以做關鍵字查詢

**Comment by mark86092** [comment]
還有將 /time-and-salary/latest --> 這種頁面加上頁碼的功能

**Comment by mark86092** [comment]
補：
![image](https://user-images.githubusercontent.com/1908007/32893486-a131d660-cb14-11e7-85d1-40dcde498ad2.png)

公司名稱與職稱的欄位，有連結可以做關鍵字查詢
