### ISSUE TITLE
導入 Immutable 的微調

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#34]
`src/index.js` 當中，L11，
```
const store = configureStore();
```

當我們進行 server side rendering 時，這個地方會被改成

```
const store = configureStore(preloadedState);
```

其中 `preloadedState` 就是從 Server 端帶過來的 state 經過解析後放入

所以這樣會遇到一個問題：

1. Server 端帶過來的物件是一個 Json 物件，必須經過轉換符合 state 的格式

所以，**state 的格式是 Server 端資訊拼裝成 Client 初始 state 的關鍵**

目前的 State 格式

```
State --> Object
{
  counter: Immutable Map,
  experienceSearch: Immutable Map,
  routing: Object,
}
```

最大的問題就是：

Server 端帶過來的物件必須轉換成兩種型別，其中 routing 是 Object，其它都是 Immutable

**Comment by mark86092** [comment]
解法一：PR #35，state 是一個完全的 immutable

解法二：
```
const __data = SERVER 端的資料 (Object)

const preloadedState = {}
__data.map((key) => {
  if (key === "routing") {
    preloadedState[key] = _data[key];
  } else {
    preloadedState[key] = Immutable.fromJS(_data[key]);
  }
})
```

**Comment by WendellLiu** [comment]
我自己覺得解法二比較好一些，每個地方都用state.get(key) 形式的改動感覺比較大。

**Comment by mark86092** [comment]
對，我今天想想得到解法二就可以處理了

**Comment by mark86092** [comment]
於 PR #33 用解法二解決了
