### ISSUE TITLE
PR 說明的樣板

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#340]
最近 review 的時候，偶爾會碰到不清楚 PR 實作了哪些功能、或是不知道測試有哪些前置作業（e.g. local 端需要改一些地方才能跑。)
所以我是想說，我們要不要用 PR 的樣板呢？   github 有功能可以讓我們開 PR的時候，自動出現樣板 

[如何新增 PR template](https://github.com/blog/2111-issue-and-pull-request-templates)
每個人 follow 這個樣板，把 PR 的解釋寫的清楚一點，讓其人他在 review 上可以更順利。

以下的樣板是我從 hahow 那邊改來的！

### 樣板

```
Close #  <!-- 當 PR merge，github 會自動幫你關 issue --> 

## 這個 PR 是？ <!-- 必填 -->

<!-- 請簡單說明這個 PR 做了什麼 -->

## 有哪些 dependency？  <!-- 選填，沒有就刪掉 -->

- Front-end PR：<!-- 這個 PR 需要先等其它前端 PR merge 之後才能 merge -->
- Back-end PR：<!-- 這個 PR 需要 checkout 這個 back-end 才能 work -->

## Screenshots  <!-- 選填，沒有就刪掉 -->

<!-- 可以的話，請提供畫面截圖，如果是 GIF 的話更好 -->

## 有什麼背景知識是我需要知道的？  <!-- 選填，沒有就刪掉 -->

<!-- 如果有 Paper、InVision 或使用的 3rd-party library or service，請附上文件連結 -->

## 我應該從何看起？  <!-- 選填，沒有就刪掉 -->

<!-- 這個 PR 要怎麼 review 才會比較好懂 (e.g. by commit 看，或先看哪些檔案) -->
<!-- 介紹一下你為什麼要這麼寫，思路是什麼？ -->

## Questions:  <!-- 選填，沒有就刪掉 -->

- 我需要更新 Packages 嗎？ No <!-- Yes / No -->
- 有哪些文件需要被更新嗎？ No <!-- 文件的連結 -->

## 我應該如何手動測試？ <!-- 必填 -->

- [ ] <!-- 提供一些前置作業需要輸入的指令 -->
- [ ] <!-- 提供一個 Demo URL Link -->
- [ ] <!-- 列出給 Reviewer 的 Step By Step Checklist -->
```

### 樣板範例
Close #12345

## 這個 PR 是？
新增 PR 的樣板，讓日後開 PR 的人有參考的依據，以利其他人 review，加速開發

## 有哪些 dependency？

- Front-end PR：#54321
- Back-end PR：https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/543

## Screenshots

![2017-11-02 10 13 12](https://user-images.githubusercontent.com/3805975/32330419-0cadffcc-c01b-11e7-8e9e-94a3771c7cb6.png)
可以用 [Recordit](http://recordit.co/) 這個軟體做螢幕錄影，輸出成 gif，很方便，免費。

## 有什麼背景知識是我需要知道的？

[如何新增 PR template](https://github.com/blog/2111-issue-and-pull-request-templates)

## 我應該從何看起？

照 commit 看，或者是先看 xxx.js 

## Questions:

- 我需要更新 Packages 嗎？ No
- 有哪些文件需要被更新嗎？ No

## 我應該如何手動測試？

- [ ] npm run xxx
- [ ] http://localhost:3001/share/time-and-salary
- [ ] 測試 ooo 功能

**Comment by mark86092** [comment]
@barry800414 這個樣板應該是適用 New Feature PR，當是 Small bugfix 的時候，應該可以跳過？

`rm -rf /` --> 這個範例有點可怕

我記得可以在 repo 放上 Template，當開新 PR 會帶入 https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

**Comment by barry800414** [comment]
> @barry800414 這個樣板應該是適用 New Feature PR，當是 Small bugfix 的時候，應該可以跳過
我有分必填、選填，如果是修小 bug，就寫 `這個 PR 是？`, `我應該如何手動測試？` 這兩項就好

> rm -rf / --> 這個範例有點可怕
這我開玩笑隨便寫的啦

> 我記得可以在 repo 放上 Template，當開新 PR 會帶入 https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

我知道，範例裡面有放 link，我這邊是想先討論確定，再開PR

**Comment by chejen** [comment]
我覺得 @barry800414 的提議不錯，應該可以減少 reviewer 的進入障礙。另外我覺得像 https://github.com/eslint/eslint/blob/9169258f7e7939652a5dfdaa3e6219d2ad9b37a4/docs/developer-guide/contributing/pull-requests.md#step2 裡面用的 `Tag` 也可以參考看看，他們本來是用把每一個 commit messages 分類成 `Fix/Update/New/Breaking/Docs/Build/Upgrade/Chore` 等類別，我們也許可以減化成自己的版本，然後用在 PR 上 (這樣之後 PR 被 merge 後，變成 dev 或 master 的 commit messages 也許也會友善一點?)

**Comment by mark86092** [comment]
@chejen 不錯的提議，

在進板或是修正 merge conflict 的時候，這樣的確比較好找 commit 的用途（雖然 merge PR 我常手動修 commit message)

至於什麼分類需要討論看看

**Comment by peteranny** [comment]
可

**Comment by WendellLiu** [comment]
同意！

**Comment by mark86092** [comment]
可以送 PR 了～～

**Comment by barry800414** [comment]
> https://github.com/eslint/eslint/blob/9169258f7e7939652a5dfdaa3e6219d2ad9b37a4/docs/developer-guide/contributing/pull-requests.md#step2 裡面用的 Tag 也可以參考看看，他們本來是用把每一個 commit messages 分類成 Fix/Update/New/Breaking/Docs/Build/Upgrade/Chore 等類別，我們也許可以減化成自己的版本，然後用在 PR 上 (這樣之後 PR 被 merge 後，變成 dev 或 master 的 commit messages 也許也會友善一點?)

@chejen 我覺得這個很不錯，可以讓 commit message 更有語意。不曉得可不可以麻煩你另外開個 issue討論呢？
