### ISSUE TITLE
經驗分享查詢頁，分頁旁的資料數量錯誤

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#348]
![2017-11-14 12 14 42](https://user-images.githubusercontent.com/3805975/32735857-da6f5b28-c8d0-11e7-9333-a6bf1a46468d.png)

**Comment by mark86092** [comment]
PR 335 有說分頁會再寫，所以那個數量應該沒處理過的

**Comment by barry800414** [comment]
瞭解！ 不過我 issue 先開著，怕忘記，解完再 close 
ref: #335
