### ISSUE TITLE
離職時間欄位驗證問題

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#349]
選擇已離職的時候，會跳出離職時間年月的選項，把它改成 `- 請選擇 -` form validation 不會 scroll 到相對應的位置，也不會有紅框

**Comment by mark86092** [comment]
不知道是否修正了，有的話再 open

**Comment by barry800414** [comment]
這個還沒修，是會影響填寫的 bug，我先打開喔

**Comment by barry800414** [comment]
沒有這個問題了
