### ISSUE TITLE
helmet data 不能用 push 

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#356]
意外發現一個 bug 
不能用這樣的方式去改 helmet 所需的 data 
```
const data = HELMET_DATA.EXPERIENCE_SEARCH;
data.meta.push(
      { name: 'description', content: description },
      { property: 'og:description', content: description },
    );
```

會真的 append 越來越多 `{ name: 'description', content: description }` `{ property: 'og:description', content: description }` 

先修這個 bug 再把經驗分享頁 helmet 做好

**Comment by mark86092** [comment]
竟然忘了千萬不要對原本資料做操作 ><"

**Comment by mark86092** [comment]
麻煩送到 master
