### ISSUE TITLE
檢舉功能的介面流程修改

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#370]
[invision 1](https://projects.invisionapp.com/d/main#/console/10208710/268576939/preview)
[invision 2](https://projects.invisionapp.com/d/main#/console/10208710/268576951/preview)
[invision 3](https://projects.invisionapp.com/d/main#/console/10208710/248481848/preview)

**Comment by mark86092** [comment]
這個 "我要檢舉" 的按鈕在 invision3 看起來是沒有定下流程的

我這裡就採取這樣：

1. 按下  "我要檢舉" 的按鈕會關閉 "檢舉列表" 的 modal
2. 打開 "檢舉此篇文章" 的 modal（如圖）
3. 使用者按下取消/送出，都會關閉 modal，回到頁面
4. 如果使用者按下的是送出，需要重新 fetch 資料


![image](https://user-images.githubusercontent.com/1908007/33796960-e907d52a-dd39-11e7-8e12-cdbbe7d7d855.png)

**Comment by barry800414** [comment]
對！
不好意思我不太會用按下某個區域跳到另一頁的功能，最近有空的話學一下ＱＱ

**Comment by mark86092** [comment]
主要是跟本來的流程有衝突，所以我就把我想到的先寫下來，這樣比較不會忘記
