### ISSUE TITLE
使用者編輯自己的經驗分享

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#371]
- [ ] 個人頁面加上編輯按鈕
- [ ] 檢查該使用者是否有權限編輯該篇經驗分享。若沒有，則顯示權限不足的錯誤訊息。 （方法待補）
- [ ] 若有權限，讓使用者修改自己的面試 / 工作經驗。 可直接使用現成的 component 實作。
- [ ] 送出修改時要做跟填寫時一樣的 validation 
- [ ] 送出修改要打 PATCH API  (待補）
- [ ] 編輯完後跳到該篇

**Comment by WendellLiu** [comment]
in progress

**Comment by WendellLiu** [comment]
@barry800414 @mark86092 @chejen 
你們覺得，編輯經驗分享還需要有離開先暫存的機制嗎？

**Comment by mark86092** [comment]
@WendellLiu 我覺得不需要

**Comment by chejen** [comment]
我也覺得如果有暫存的話比較怪 ... 感覺比較容易讓人對正在編輯的資料混淆

**Comment by WendellLiu** [comment]
OK, 那我就不做這件事了

**Comment by barry800414** [comment]
覺得不用暫存！

**Comment by WendellLiu** [comment]
@mark86092 
我發現一個問題，來源需求是需要讓不是發文用戶者，不能進來此編輯頁面。

但目前api 沒有回user 相關的資訊，因此無法比對當前使用者是否為發文者。
這當然可以由 `https://api-dev.goodjob.life/me/experiences` 這隻api 的資料來判斷是否該文章id 有沒有在其中，不過好像有點太繞，是不是後端能多給發文者的資訊？

**Comment by WendellLiu** [comment]
@mark86092 

另一個問題：
我發現 `PATCH /experiences/:id` 這隻api 需要status
這點應該算合理，因為要給讓有管道可以修改post status。

但在我那， `GET /experiences/:id` 並沒有回status ，又`PATCH /experiences/:id` 中status 似乎算必填，所以我會不曉得怎麼給定status。

**Comment by mark86092** [comment]
@WendellLiu 統整一下：後端要開一隻 /me/experiences/:id

他有幾個功能：

1. 確保發 query 的 user 是文章擁有者，否則會得到 4xx
2. 這個 API 可以拿到 status、也許會有更多的資訊 --> 這樣前端才能判斷文章狀態、一些 meta data

這樣呢？

**Comment by WendellLiu** [comment]
@mark86092 

這樣的話沒問題。

另一個想確認的，因為api doc 沒有完全透露：`PATCH /experiences/:id` 這api 應該也能更新到除了`status` 以外的資料吧？

**Comment by mark86092** [comment]
oh, 後端是用 PUT，這裡錯了 @barry800414 你的流程要不要修正清楚一點？

**Comment by WendellLiu** [comment]
@mark86092, @barry800414 

現在doc 是
https://goodjoblife.github.io/WorkTimeSurvey-backend/dev/
嗎？

我沒看到該api

如果有另一隻api ，那status 是不是就可以移除，或非必填，這樣也不需要在你前面說的 `/me/experiences/:id` 這api 加上status。

建議這裡可以重新想一下api 的定位。

**Comment by barry800414** [comment]
暫時沒有要做，先關掉
