### ISSUE TITLE
職業行業別分類

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#374]
- [ ] 面試經驗表單加上該選項  [invision](https://invis.io/TYAAY1QR4#/268576180_exp-Work-With-Category)    
- [ ] 工作經驗表單加上該選項
- [ ] 經驗分享查詢頁，左方加上 checkbox 開關  [invision](https://invis.io/TYAAY1QR4#/257018208_company-V1)
- [ ] route 調整

**Comment by mark86092** [comment]
先關閉，有需要再開
