### ISSUE TITLE
經驗查詢頁 連結優化

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#384]
頁面 https://www.goodjob.life/experiences/search 的選單

![image](https://user-images.githubusercontent.com/1908007/33797004-bff12b04-dd3a-11e7-9996-7da6bfac138b.png)

現在基本上是透過 pushRoute 來改變路由

這邊我希望可以優化成 `<Link>` 的形式，有幾個好處

1. 網站爬蟲在爬的時候可以直接取得連結
2. 明確的 html 標籤可以增加 Web Accessibility

@barry800414 @WendellLiu

**Comment by mark86092** [comment]
可以看到 google search 其實爬到很多 薪時的網頁 https://www.google.com.tw/search?q=site%3Agoodjob.life+time-and-salary

**Comment by WendellLiu** [comment]
蠻合理的，之前先順著改完，接下來可以改這塊。

**Comment by WendellLiu** [comment]
另外順帶一提，用「群暉 工時」查詢，會是第一頁，覺得很棒～
