### ISSUE TITLE
分享心得介面調整

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#400]
- 還是一頁
- 心得段落放在一起（參考 usalary）
- 必填（包含推與不推） - 心得 - 「分享更多資訊」（非必填）

**Comment by WendellLiu** [comment]
<img width="906" alt="2018-02-27 8 11 35" src="https://user-images.githubusercontent.com/8898129/36728067-73caf06c-1bfa-11e8-846e-81f35f446360.png">

@wutingy 
新的一塊用哪個Icon 嗎？

**Comment by wutingy** [comment]
@WendellLiu 我本週日前出給你

**Comment by WendellLiu** [comment]
@mark86092  @barry800414 
我記得這裡也要把section 的subtitle 拿掉，並且把內容的部分填上
「
面試心得：
公司氣氛：
......
」

這個預設值，我找了一下上次的會議記錄，應該沒有提到實際要放的文案。
還是有寫在哪嗎？

**Comment by barry800414** [comment]
這個沒有討論到，但應該就是原本的選項，直接列在下面即可

**Comment by wutingy** [comment]
是的，原本的選項即可
