### ISSUE TITLE
部落格『手機版』需要做容易導回官網的按鈕 / 設計～

### ISSUE THREAD

**Issue by yudilai** [goodjoblife/GoodJobShare#403]
**原因**
目前部落格有在臉書或其他平台推播的兩篇文章，不重複瀏覽量分別是6k+ 和2k+  傳散量還可以，但我覺得流量導回官網的效率應該很差，更不用提資料轉換量。

因為看後台分析，有『七到八成』部落格讀者是用手機，今天我用手機開部落格發現，手機無法像電腦介面那樣看到最上面「好工作評論網」的按鈕。代表手機讀者點進文章從頭到尾都沒有直接導回官網的地方，除非拉到最最下面的黑色表格。很有可能他看完文章還是不知道這篇文章跟GJ有關係><

**賴怡的建議**
在手機開啟文章的最上面（slogan和特色圖片之間）和文末（leave a comment的上面）都做連結到官網的按鈕，文末可以是這樣的字樣「看更多薪資、工時、工作評論—>好工作評論網（連結）」
--
文章上方：
![img_0994](https://user-images.githubusercontent.com/36961913/36852501-bb85e0a8-1da6-11e8-8fe1-82996fabecd2.PNG)
文章下方
![img_0993](https://user-images.githubusercontent.com/36961913/36852503-bdd3f3f4-1da6-11e8-8030-961cb4279a2a.PNG)

**Comment by wutingy** [comment]
done
