### ISSUE TITLE
職業別薪資工時大調查 Campaign 頁面

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#419]
已與 @mark86092  @wutingy  討論完，一共有三個 route 的內容要改

###  Campaign 專用薪資工時表單
- route:  `/share/time-and-salary/campaigns/:campaign_name` 
例如： `/share/time-and-salary/campaigns/software-engineer`

![screencapture-goodjob-life-share-time-and-salary-2018-03-29-23_16_43](https://user-images.githubusercontent.com/3805975/38099191-902704de-33ac-11e8-9d3b-55d0af0543dd.png)

打 `POST /workings` 時，會新增三個欄位：
1.  `campaign` ：該 campaign 的 name
2. `about_this_job`：新增的「職場甘苦談」文字欄位
3. `extra_info`：新增的額外欄位，不會對外顯示，單純做促銷活動用（不一定會有）

---

### Campaign 專用薪資工時查詢頁
- route: `/time-and-salary/campaigns/:campaign_name`  
[活動頁面 invision](https://projects.invisionapp.com/d/main#/console/10208710/286471618/preview)

- 打 `GET /workings` 時，要新增一個欄位 `campaign`，作為過濾
 
---

### 原本薪資工時查詢頁修改
- route: `/time-and-salary`
[最新薪資工時頁面 invision](https://projects.invisionapp.com/d/main#/console/10208710/251593028/preview)

**Comment by barry800414** [comment]
@mark86092  @wutingy  你們看看有沒有特別需要修正的部分

**Comment by wutingy** [comment]
沒問題，我覺得有時間的話 banner 也可以改成用 contentful 上傳

**Comment by mark86092** [comment]
`/time-and-salary/campaigns/:campaign_name` 應該只會實作出最新薪資工時的資料？

**Comment by mark86092** [comment]
這裡有幾個要更正的點：

> Campaign 專用薪資工時查詢頁
> route: /time-and-salary/campaigns/:campaign_name
> 活動頁面 invision
> 打 GET /workings 時，要新增一個欄位 campaign，作為過濾

1. 打的 API 是：`/workings/campaigns/:campaign_name`，參考：https://github.com/goodjoblife/WorkTimeSurvey-backend/issues/476
