### ISSUE TITLE
Campaign 頁面設計

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#421]
根據 #419 出設計，麻煩 @barry800414 看過。

### 設計
[最新薪資工時頁面](https://projects.invisionapp.com/d/main#/console/10208710/251593028/preview)
[活動頁面](https://projects.invisionapp.com/d/main#/console/10208710/286471618/preview)

### 補充
不知道為什麼現在官網上的 UI 跟設計的不ㄧ樣，希望這次修正可以將正確的 UI 改上，謝謝！

如果需要的話，style 部分我可以先做，再交給 @peteranny 串接。

**Comment by mark86092** [comment]
@wutingy 現在官網上應該有幾個點不一樣，1) pagination 的部分，這部分沒實作上去 2) 另外的差異(搜尋框、Banner 按鈕) 我再搬移成 https://projects.invisionapp.com/d/main#/console/10208710/257020635/preview

**Comment by peteranny** [comment]
那我先做campaign的路由部分！(與style無關的部分)

**Comment by peteranny** [comment]
剛看了一下，我應該可以連style一起做

**Comment by wutingy** [comment]
要等 @barry800414 確認再做喔！

**Comment by peteranny** [comment]
@mark86092 的意思是說搜尋框&Banner按鈕已經正在搬移了嗎？還是還沒

**Comment by mark86092** [comment]
應該是兩件事，我指的是現在官網跟設計做得不一樣

你要做的是 campaign，要麻煩想想看怎麼去融合本來的頁面 或 新的頁面 componet

**Comment by peteranny** [comment]
那就看怎麼分工，如果是我弄的話，campaign就還是會用舊UI為基底，更新UI的部分會另外發

**Comment by barry800414** [comment]
覺得沒有問題！

我想確認一下

任務Ａ：網站改成符合 https://projects.invisionapp.com/d/main#/console/10208710/257020635/preview 
會由 @mark86092  負責嗎？    還是 @wutingy ？

任務Ｂ： [職業別的頁面](https://projects.invisionapp.com/d/main#/console/10208710/286471618/preview)，會是 @peteranny 負責，要等任務Ａ完成嗎？

**Comment by barry800414** [comment]
我明天丟臉書訊息問你們，跟你們確定分工。

**Comment by barry800414** [comment]
抱歉 @wutingy ，剛剛才想到。
我想確認一下，因為會新增一個文字欄位，我想確認，使用者要怎麼看到？
