### ISSUE TITLE
網站名稱、Slogan 修正

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#430]
網站名稱：`職場透明化運動`
Slogan：`共享工時薪資，求職不再面議！` 可視情況拉長 `匿名分享你的工時、薪資，讓我們求職不再面議`

要修改的地方盤點：
1. - [ ]  Footer  @barry800414
![2018-03-29 10 55 36](https://user-images.githubusercontent.com/3805975/38096118-a5f32ec6-33a4-11e8-93da-a0e433716ba0.png)
`goodjob 職場透明化運動 - 共享工時薪資，求職不再面議！`

2. - [ ] 首頁主 banner @wutingy  
![2018-03-29 10 55 28](https://user-images.githubusercontent.com/3805975/38096117-a5bf272a-33a4-11e8-844f-229b8e987422.png)
改名稱 + Slogan + Call to action button 募資條拿掉

3. - [ ] 募資中區塊 @barry800414
![2018-03-29 10 55 49](https://user-images.githubusercontent.com/3805975/38096119-a6509598-33a4-11e8-847e-a9c060d89223.png)
Title: `職場透明化運動進行中`

4. - [ ] 上方募資條  @barry800414
![2018-03-29 10 56 19](https://user-images.githubusercontent.com/3805975/38096121-a684a630-33a4-11e8-9d3a-99b8af4d86ab.png)
Title: `職場透明化運動進行中`

5. - [ ] 網站 Meta data 修正：包含網站標題、介紹  @barry800414 
og-image: @wutingy 

--- 以下非本站

6. - [ ] 粉專名稱  @barry800414 

7. - [ ] 粉專 Banner   @wutingy 

8. - [ ] 粉專置頂貼文圖 @wutingy 

9. - [ ] 百工寫真的連結 @wutingy

**Comment by barry800414** [comment]
### 討論：
1. 募資條標題？
2. 募資中要不要直接改成薪資工時的資料數，目標設 1 萬筆？

**Comment by wutingy** [comment]
「共享工時薪資，求職不再面議
匿名分享你的工時、薪資，讓我們求職不再面議。」

**Comment by wutingy** [comment]
- 粉專 Banner [連結](//image.goodjob.life/banners/facebook-bn.png)
- og:image = 粉專置頂貼文圖 [連結](//image.goodjob.life/og/default-06-April.jpg)

**Comment by mark86092** [comment]
進 master 了～
