### ISSUE TITLE
工時排行榜的極端資料，收合時沒清空

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/GoodJobShare#439]
點選工時排行榜(依工時排序)，重複展開與收合極端資料，頭一筆資料會一直疊加重複上去。
[https://www.goodjob.life/time-and-salary/work-time-dashboard](https://www.goodjob.life/time-and-salary/work-time-dashboard)

類似問題也發生在估算時薪排行榜
[https://www.goodjob.life/time-and-salary/sort/salary-asc](https://www.goodjob.life/time-and-salary/sort/salary-asc)

但工時排行榜(由低到高)與估算時薪(高到低)沒有問題。

# Demo

![](http://g.recordit.co/PitHNEQjFK.gif)

**Comment by peteranny** [comment]
發現是因為extremeData與一般的data有重覆時，會造成duplicated key，使React沒有辦法順利的去掉extremeData的row。

要看看為什麼extremeData會有與一般data有重覆的key。

**Comment by mark86092** [comment]
我看了一下這個 issue，主因是：後端的 extremeData 與一般 data 有重覆的 key （而前端產生表格非常不直覺）

PR #441 沒辦法解決這邊的 issue
