### ISSUE TITLE
Modal做成可捲動

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/GoodJobShare#440]
目前的modal沒辦法捲動，萬一內容太多，超過視窗，使用者會GG。

![](http://g.recordit.co/RnQUDhtgpn.gif)

**Comment by wutingy** [comment]
好，收到，下週會處理～

**Comment by mark86092** [comment]
Take your time

**Comment by barry800414** [comment]
@wutingy  @mark86092  這個後來有解掉嗎？
似乎沒有看到 PR

**Comment by peteranny** [comment]
我看手機尺寸有卷軸，但PC沒有

**Comment by mark86092** [comment]
Still open
