### ISSUE TITLE
GA page view 未正常搜集資訊

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#449]
https://github.com/goodjoblife/GoodJobShare/commit/9fef7a86316670ce6def4d17f3778dc83b825c3a#diff-9b543e7a3cf09c571ce437f3f8b7b4f9L39  （我標行號了）

原本 router 更新的時候，會在 onUpdate 執行 logPageView
現在換新版之後沒有做（不確定做法是否相同）

**Comment by mark86092** [comment]
原 PR https://github.com/goodjoblife/GoodJobShare/pull/411/files#diff-9b543e7a3cf09c571ce437f3f8b7b4f9L39
