### ISSUE TITLE
貼文隱藏後，google search 結果仍看得到網頁內容

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#451]
有使用者反映，他於 4/14 晚上隱藏這篇貼文，實際上點進去確實看不到內文
https://www.goodjob.life/experiences/5a7531ca347b330004e73a42

但 google 搜尋引擎搜尋到，還是會有暫存的訊息：
![2018-04-17 12 22 29](https://user-images.githubusercontent.com/3805975/38822312-a0a13776-41d5-11e8-9ac0-4c12b53d8f0a.png)

不算很急的 task，但不曉得有沒有方法，可以讓 google 的暫存消失

**Comment by mark86092** [comment]
@barry800414 我回在 slack

**Comment by mark86092** [comment]
已處理
