### ISSUE TITLE
實習資料來源

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#464]
<img width="457" alt="screen shot 2018-04-22 at 9 07 56 am" src="https://user-images.githubusercontent.com/8353239/39090260-b91a37c2-460c-11e8-88ec-06c8880ce273.png">

這塊可不可以不要 merge 到 section 裡？這樣我可以把它放在一個正常一點的位置（右下角 灰字 之類的）

**Comment by mark86092** [comment]
不過現在資料格式裡沒有保留欄位放 ><" 有什麼 idea ?

**Comment by wutingy** [comment]
想想好像還真的蠻麻煩的 🤔

**Comment by mark86092** [comment]
一個很 work around 的方法：

判段 section 的最後是不是這段文字，是的話，採取一些 UI 的動作
