### ISSUE TITLE
Campaign 預設搜尋職缺比對問題

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#471]
https://github.com/goodjoblife/GoodJobShare/blob/2ce095936f6ac7c6427252dabf2faf5ff8da66c9/src/apis/campaignInfoApi.js#L40

 如 code，這個指的是會搜尋等於 "工程師" 或 等於 "engineer"

是不是應該多列幾項(eg. "軟體工程師")比較合理？

**Comment by mark86092** [comment]
> 有可能是模糊搜尋嗎

要寫 Re, 問題是 queryJobTitles 是個陣列，這樣後端負擔很大

本來開規格就是 全文符合，我覺得也夠用了，列舉4~5個應該夠多元

**Comment by barry800414** [comment]
OK，我再補要搜尋的職缺陣列。

**Comment by barry800414** [comment]
已送 PR，再麻煩協助 review 了
