### ISSUE TITLE
Campaign 頁面樣式問題

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#473]
- [x] 1. campaign 表單的介紹需要調整排版
![2018-04-28 12 00 42](https://user-images.githubusercontent.com/3805975/39372657-901cb588-4a77-11e8-817d-59853f513dfe.png)

- [x] 2. 頁尾也需要 
![2018-04-28 12 00 48](https://user-images.githubusercontent.com/3805975/39372658-9046fde8-4a77-11e8-96e1-5720501ba68d.png)

- [ ] 3. 寬度 < 850px 以下跑版
![2018-04-28 12 20 19](https://user-images.githubusercontent.com/3805975/39373381-fcae4f2a-4a79-11e8-9216-95df5b324c66.png)

**Comment by wutingy** [comment]
我下週二會來改

**Comment by wutingy** [comment]
這邊是從後台填的嗎？不要用 `<ol>`
<img width="869" alt="screen shot 2018-05-03 at 9 40 26 pm" src="https://user-images.githubusercontent.com/8353239/39579988-a265f37e-4f1a-11e8-9e82-878e0b14a776.png">

**Comment by mark86092** [comment]
@wutingy 是寫在前端，我送個 commit 改成 `ul`
