### ISSUE TITLE
Campaign 查詢頁 infinity scroll 在讀取到最底端後，還是會一直讀取

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#476]
- [ ] https://www-dev.goodjob.life/time-and-salary/campaigns/software-engineer/latest  頁面的 infinity scroll 拉到底會一直讀取，即使沒有資料還是會一直讀

**Comment by mark86092** [comment]
TimeAndSalary 那邊從以前到現在都是這樣，不是 campaign 的問題。

我是建議簡單的把兩次讀取間格設定一個 threshold 使用體驗會比較好。

不過 #329 這邊要換掉，所以這問題就會不見。
