### ISSUE TITLE
放寬 薪時資訊 填寫的次數限制

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#478]
目前限制次數為 5，其實還蠻容易到達的（如果每幾個月上傳新的資訊）

https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/4bae2a55b89fe6c9083ff55570fbc43babbc25b9/routes/workings/helper.js#L15

```js
function checkAndUpdateQuota(db, author) {
    const collection = db.collection("users");
    const quota = 5;

    const provider = `${author.type}_id`;
```

**Comment by barry800414** [comment]
那你覺得多少合理？
我覺得這不是個問題，真正留多筆資料的使用者並不多，多數都是一樣的資料

**Comment by barry800414** [comment]
@mark86092  這個 issue 有什麼後續的想法嗎？
我是認為不用改，或者是改到上限 10 篇

**Comment by mark86092** [comment]
暫時先不用好了，最近沒想這個問題
