### ISSUE TITLE
Campaign og:image

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#486]
文字：

職業薪資、工時大募集！

**Comment by wutingy** [comment]
我下禮拜二做

**Comment by barry800414** [comment]
可以是個模板替換字嗎？ e.g. `科技業工程師 真實工時、薪資分紅 大調查`
我希望是每個職業別的圖都不一樣，因為這會很大影響使用者是否點擊進來看
只寫個 `職業薪資、工時大募集！`  會不知道跟我有關係

很不希望做很久的頁面因為這很小的細節就掉了很多流量

**Comment by wutingy** [comment]
@barry800414 沒問題～
