### ISSUE TITLE
Campaign / TimeAndSalaryBoard 頁面滑到最後一筆資料時，仍會快速的讀取遠端資料

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#487]
一種要 loding 不 lo 的感覺。

https://www-dev.goodjob.life/time-and-salary/campaigns/software-engineer/latest

**Comment by mark86092** [comment]
See #476 

不過近期有空解，讓它比較順是ＯＫ的

**Comment by wutingy** [comment]
拍謝重複了，如果有空解，那就先不關囉

**Comment by mark86092** [comment]
1. 一個是 `<Loading> /` 的 icon 會因為讀取新資料出現，讀取完消失 --> 看起來像閃爍（對，API 很快完成）
2. 一個是觸發讀取太過頻繁，讀取完，又觸發讀取新資料 --> 閃爍

**Comment by mark86092** [comment]
當 window scroll 到底時，觸發 fetching，會突然插入一個有高度的 `<Loader>`

觸發 fetching 前：
![image](https://user-images.githubusercontent.com/1908007/39832029-b7049532-53f8-11e8-95a9-1ec849e121d1.png)

觸發 fetching 後：
![image](https://user-images.githubusercontent.com/1908007/39831935-7d044d96-53f8-11e8-94bf-0306b11393a3.png)

這段非常短的時間內，Footer 會被突然快速的往下擠，看起來很跳

**Comment by mark86092** [comment]
這個 issue 被我改標題，同時參閱 #508 另外產出的問題
