### ISSUE TITLE
看更多資料問題

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#488]
<img width="684" alt="screen shot 2018-04-28 at 5 03 33 pm" src="https://user-images.githubusercontent.com/8353239/39394621-a0517742-4b06-11e8-95fd-4b4d9a00600d.png">

1. 顯示的地方沒有 style，只少要斷行
2. 沒有填字串應該視為不顯示在前端，顯示出來很奇怪。
3. 用一整個 textarea 裡面一堆字，我擔心大家無法正常填東西，能否考慮將引導文字放在 textare 上方，這樣盼端有沒有填也比較方便。

**Comment by mark86092** [comment]
> 用一整個 textarea 裡面一堆字，我擔心大家無法正常填東西，能否考慮將引導文字放在 textare 上方，這樣盼端有沒有填也比較方便。

是指這邊嗎？

![default](https://user-images.githubusercontent.com/1908007/39398700-00b4f34c-4b44-11e8-8414-e40bf0fe1ff3.png)

**Comment by wutingy** [comment]
@mark86092 昨天與韋銘討論過後，決定不修正填寫的 textarea 方式，不過前端有兩邊要改：

- [ ] 判斷 textarea 與原本的字串ㄧ樣，送出表單時不送該欄位
- [ ] 顯示的地方要把 `\n` 轉成 `<br />`

麻煩看看 @mark86092  或是 @peteranny 有沒有空修。

**Comment by peteranny** [comment]
我可以修

> 判斷 textarea 與原本的字串ㄧ樣，送出表單時不送該欄位

這句看不太懂，不送該欄位的意思是？
