### ISSUE TITLE
實習經驗SearchBar搜尋建議Pill會炸掉

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/GoodJobShare#489]
https://www-dev.goodjob.life/experiences/search

目前按了搜尋Bar底下的`工程`建議Pill，就會炸掉

![](http://g.recordit.co/eQBcpQuhj7.gif)

**Comment by mark86092** [comment]
那個是 dev 環境的關係，當時插入實習資料的時候有缺不該缺的欄位

不過線上的資料不會

**Comment by mark86092** [comment]
當然，寫出比較 robust 的 component 也是可以
