### ISSUE TITLE
薪資工時搜尋頁在以連結直接進入後，資料與排版都出現問題

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/GoodJobShare#493]
若直接進入
`/time-and-salary/job-title/:keyword/work-time-dashboard`
或
`/time-and-salary/company/:keyword/work-time-dashboard`

會發現無論資料或排版都出現問題。
截圖：
![2018-04-29 1 52 36](https://user-images.githubusercontent.com/8898129/39403720-2372b678-4bb5-11e8-9d4d-1ff8b817b513.png)

但若是從`/time-and-salary/` 填入搜尋進入同樣頁面的話，則是正常的。

補上：
事實上進入`/time-and-salary/latest` 就會出現問題了

**Comment by WendellLiu** [comment]
@mark86092 
我會先看一下。

**Comment by mark86092** [comment]
有範例的網址可以直接貼

**Comment by WendellLiu** [comment]
```
warning.js?6327:33 Warning: Did not expect server HTML to contain a <h1> in <div>.
warning.js?6327:33 Warning: The tag <bold> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.
```
目前看來，可能跟server-side rendering 有關，重整後會出現上面的warning ，但是經由搜尋頁進入則不會。

**Comment by mark86092** [comment]
warning 這兩個不會故障說

**Comment by WendellLiu** [comment]
目前看起來，在server-side rendering 這段渲染出現問題。
舉例來說：

在`/time-and-salary/latest` 中觀察component `InfoSalaryModal` ，會出現兩個`InfoSalaryModal`。
其中第一個，會少了component `Modal` 中最外層的`div` ，並且被含Wrapper.m 的div 包裹，而第二個則是正常。

我猜還有很多style 跑掉，也是因為這個原因。
