### ISSUE TITLE
Campaign / 薪時頁面，當 scroll 到底時，旋轉的圓圈讓畫面跳躍

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#508]
當 window scroll 到底時，觸發 fetching，會突然插入一個有高度的 `<Loader>`

觸發 fetching 前：
![image](https://user-images.githubusercontent.com/1908007/39832029-b7049532-53f8-11e8-95a9-1ec849e121d1.png)

觸發 fetching 後：
![image](https://user-images.githubusercontent.com/1908007/39831935-7d044d96-53f8-11e8-94bf-0306b11393a3.png)

這段非常短的時間內，Footer 會被突然快速的往下擠，看起來很跳

**Comment by wutingy** [comment]
把 loader 預設為一直都顯示，只是 `visibility: none, opacity: 0` 這樣會解掉嗎？

**Comment by mark86092** [comment]
那就是在 `<Loader>` 上面包一個可以根據 status 切換 style 的 Component，

感覺可行
