### ISSUE TITLE
小教室 contentful 欄位

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#51]
@barry800414 麻煩用公用的 email 創建帳號。

### 欄位建議：
- SEOTitle (text)
- SEODescription (text)
- title (text)
- description (text)
- content (markdown)
- hidingText (text)

**Comment by wutingy** [comment]
hidingText 為行銷將小教室圖片關鍵字寫出來，在前端會 `display: none` 的欄位。

**Comment by peteranny** [comment]
description應該是markdown

![2017-04-19 2 57 40](https://cloud.githubusercontent.com/assets/7566586/25148075/39ca2766-24ac-11e7-9f36-0b6c0746e187.png)

**Comment by wutingy** [comment]
@peteranny description 我希望為純文字，能簡潔說明該主題就好，不會有圖片 or 連結。

**Comment by mark86092** [comment]
其實 emoji 跟 markdown, text 沒關係ＸＤ它只是 unicode，不過 emoji 在各地方看都長得不一樣

**Comment by mark86092** [comment]
@peteranny 

> description應該是markdown

有什麼理由嗎？

**Comment by peteranny** [comment]
我一直講錯，不是emoji的問題，是一些換行等等用markdown轉成html會比較直觀
如果是multi line的話我大概就要用pre了，也是可以但就有點醜

**Comment by peteranny** [comment]
或者是一樣是送進markdown但是contentful的欄位用一般multi-line
如此一來只會有換行的效果

**Comment by mark86092** [comment]
> 如果是multi line的話我大概就要用pre了，也是可以但就有點醜
> 或者是一樣是送進markdown但是contentful的欄位用一般multi-line
> 如此一來行銷組員只會用到換行的效果

有個好用的 css 設定：`white-space: pre-line`

所以你說的問題應該有解

**Comment by peteranny** [comment]
我覺得這太naive，而且我會覺得description和content的render方法不同很怪
我還是覺得都用markdown成htm碼，但contentful欄位讓行銷組用multi-line撰寫即可

**Comment by peteranny** [comment]
對我來說，description和content本質都是text，但放在網頁上都是網頁的一部分
我是不覺得一定要讓description不能有html tags的道理
就網頁架構會變成description包成一個div，但content是正常的<p>
可是既然都render成網頁的內容了，應該都是<p>才對
之所以要用pre只是為了要禁止他用markdown的話我是覺的沒必要
引導他用一般文字來寫是可以透過contentful介面做到的

**Comment by wutingy** [comment]
原來是為了換行，彥齊那個 css 好像不是這樣用的，就算是下了還是不會換行喔，換行還是需要 <br>。
https://www.w3schools.com/cssref/playit.asp?filename=playcss_white-space&preval=pre-line

@peteranny 我想了一下，description 不要讓他換行，因為我覺得說明文字要簡潔，多行的話就失去了 description 的功能了。你覺得勒？

**Comment by wutingy** [comment]
還有考量到 description 有機會成為列表頁的內容的一部份，還是保持純文字會比較好。

**Comment by peteranny** [comment]
那我就把他當一行來做，然後加粗體囉？

**Comment by mark86092** [comment]
我是在解釋，當給定的文字是有 `\n`（不是`<br>`，而是編輯器按下 enter）， 在一般放到 html 情況下不會換行，在 pre-line 會換行，所以為了換行用 markdown 很怪

**Comment by mark86092** [comment]
我 open 一下，主要是要創立 Model 在公用的帳號

[ ] 建立小教室 Model (彥齊)
[ ] 分發 production accessToken, stage, 和 testing

**Comment by mark86092** [comment]
最後欄位：

SEOTitle (text)
SEODescription (text)
title (text)
description (text)
content (markdown)
hidingText (text)
coverImage (media)
