### ISSUE TITLE
小教室權限機制優化

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#514]
優化小教室權限機制設計

**Comment by barry800414** [comment]
@wutingy 想問妳是否有預計地完成的時候，我可以協助開發！

**Comment by mark86092** [comment]
這個 issue 要解什麼？

**Comment by barry800414** [comment]
這個是之前會議決定要優化小教室頁面權限機制呈現的方式與流程，讓使用者更有意願填寫資訊

**Comment by wutingy** [comment]
預計本週五前完成

**Comment by wutingy** [comment]
@barry800414 就像我們上次討論的，沒有做大修改，就讓它看起來和諧一點，主要是填寫內容清單那邊可以多填一些重點。

如果沒問題的話我再找時間 update 上去。
![screen shot 2018-06-11 at 7 01 34 pm](https://user-images.githubusercontent.com/8353239/41228160-f6bcf168-6da9-11e8-972c-a1af45e0e4ec.png)

**Comment by barry800414** [comment]
@wutingy  覺得沒問題！

然後，標題如果改成：`共享的你資訊，馬上擁有查看完整資訊的權限`

會再更讓人容易接受嗎？
目前的標題，可能一看到就會有點不爽

**Comment by wutingy** [comment]
好，預計下週送 PR

**Comment by barry800414** [comment]
@wutingy  這個 issue 你可以把圖出給我～ 我來寫

**Comment by barry800414** [comment]
到時候網站改版做到這邊再開 issue
