### ISSUE TITLE
做配圖：中學教師專題文章（deadline: 5/27-12:00pm）

### ISSUE THREAD

**Issue by yudilai** [goodjoblife/GoodJobShare#518]
1. 配圖內容
https://drive.google.com/open?id=1bqx04XaQzapPgR2sR4Ot_MR608cCw-ZQ

2. 文章草稿
https://media.goodjob.life/wp-admin/post.php?post=1089&action=edit

3. 倒數第二段「老師談教育」那邊有一連串quotations，我想讓每則quote前面都有quotation mark（現在只有第一則有），不知道怎麼調。麻煩tin進wordpress幫忙調整，3Q :DD

**Comment by wutingy** [comment]
@yudilai  因為本週末我不在台北，所以大概會拖到下週三～四才能做完！

**Comment by wutingy** [comment]
@yudilai 文章已經更新圖片上去囉
