### ISSUE TITLE
網頁會載入到非preloadedState

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/GoodJobShare#52]
剛剛debug好久，我發現有個奇怪的事情
理論上網頁載好的state就是componentDidMount完的state，但我現在網頁會有兩個state...
也就是正確的state之前還有一個state造成`state.laborRights = undefined` (貌似是`state = {}`)

**Comment by mark86092** [comment]
componentDidMount 執行後，你的 state.laborRights 是 undefined，等到 api fetch 完，才有東西

兩個 state 是什麼？有截圖嗎

**Comment by peteranny** [comment]
下面這張是`prevState.laborRights`點開的樣子，如圖`size:0`

![2017-04-17 1 21 23](https://cloud.githubusercontent.com/assets/7566586/25072885/9f6b2cd8-230c-11e7-8676-4172a29d1b17.png)

下面這張是`nextState.laborRights`點開後的樣子，如圖是`size:2` <= 這個我的code正確結果沒錯

![2017-04-17 1 23 29](https://cloud.githubusercontent.com/assets/7566586/25072887/a1475edc-230c-11e7-8f99-0135568f6d81.png)

就我所知道SSR應該是直接就render完整的state了沒錯吧？所以第一個state應該是有問題的
而且就算是這樣，我的code的preloadedState也明明不應該讓`size:0`
preloadedState如下圖所示：

![2017-04-17 1 22 15](https://cloud.githubusercontent.com/assets/7566586/25072874/5ec9a434-230c-11e7-8091-a191c06ac7f5.png)

**Comment by peteranny** [comment]
Safari的console比較清楚

這個是第一個action dispatch，可以看到這個時候就已經laborRights.size = 0了
![2017-04-17 1 47 19](https://cloud.githubusercontent.com/assets/7566586/25073020/dd37f796-230f-11e7-83da-cf6c3ccfc307.png)

這個是第二個action dispatch，這時才回到正常的laborRights.size = 2，但是我明明有寫preloadedState....
![2017-04-17 1 46 55](https://cloud.githubusercontent.com/assets/7566586/25073023/df81e0ca-230f-11e7-9181-4abbbd955ec0.png)

**Comment by mark86092** [comment]
別人的都有 1, 6，你的沒有，所以應該是你的 code 哪裡有出問題

**Comment by peteranny** [comment]
branch `labor-rights-store-error`

**Comment by mark86092** [comment]
我兩個狀況都沒實驗出來，無論是 SSR on/off

BTW, 檢視原始碼可見：

```
window.__data={
  "counter":{"counter":0},
  "experienceSearch":{"sort":"created_at","interview":false,"work":false,"salary":false,"industry":"all","condition":"job_title"},
  "laborRights":{"idList":[],"dataMapById":{}},
  "routing":{"locationBeforeTransitions":{"pathname":"\u002Flabor-rights","search":"","hash":"","action":"POP","key":null,"query":{}}}};
```

所以我看到第一張圖就是：

![image](https://cloud.githubusercontent.com/assets/1908007/25073139/98951008-2312-11e7-8655-f492239fc833.png)

通常 action dispatch 過完一次，state 就會有初始值，counterMap 有 size 1, experienceSearch 有 size 6

你的沒值，大概是你那邊的環境有問題（我這邊 clone 測正常

**Comment by peteranny** [comment]
好的，也許是webpack的問題，我明天再測測看
