### ISSUE TITLE
放大鏡點下去後跳 Modal ，無法取消 Modal

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#527]
重現步驟：
1. 點進：https://www.goodjob.life/time-and-salary/latest
2. 隨便按個放大鏡
3. 結果你就會發現你離不開 Modal 了ＸＤ

![2018-06-03 12 18 00](https://user-images.githubusercontent.com/3805975/40878427-af7c5010-66c3-11e8-89d8-7e23b19962fd.png)

**Comment by mark86092** [comment]
你說的是不是 #440，如果是，應該是過高的 Modal 才會有

**Comment by barry800414** [comment]
我想是同個問題，先關掉這個
