### ISSUE TITLE
安裝Facebook Container的Firefox無法執行FB登入／驗證

### ISSUE THREAD

**Issue by chuck-lee** [goodjoblife/GoodJobShare#528]
### 環境
- Windows 8 + Firefox 60.0.1 (64 bit)
- Firefox 中安裝 [Facebook Container](https://www.mozilla.org/zh-TW/firefox/facebookcontainer/)

### 重現步驟
1. 以連結開啟網頁 https://www.goodjob.life/
2. 點擊右上角＂登入＂

### 預期結果
登入成功

### 實際結果
1. 跳出應該是FB驗證的視窗，但沒有後續行為  
![default](https://user-images.githubusercontent.com/880639/40885310-8a8cf406-6756-11e8-8808-b8c943203534.png)
2. 實際上沒有登入

**Comment by chuck-lee** [comment]
在同一系統中使用  Chrome 66.0.3359.139 可以正常登入。  
因為新版的Firefox有Facebook Container，不知道是不是受這個影響。

**Comment by chuck-lee** [comment]
手機版Firefox也有類似情況，但外顯的行為不同。

#### 環境
Android 8.0.0 + Firefox 60.0.1

### 重現步驟
1. 以連結開啟網頁 https://www.goodjob.life/
2. 點擊右上角選單符號，點選選單內的＂登入＂

### 預期結果
登入成功

### 實際結果
沒有任何回應

#### 其他資訊
1. 用 Windows 8 + Chrome 66.0.3359.139 的**開發人員工具**模擬手機介面，可以正常登入。
2. 用 Windows 8 + Firefox 60.0.1 (64 bit) 的**適應性模式設計**，點選登入會開啟空白新畫面，然後沒有任何動作。

**Comment by barry800414** [comment]
我目前 Mac + Firefox 59.0 
無痕模式下，跟 @mark86092 一樣是 facebook sdk 被 block 掉
不過非無痕的狀態下，是可以使用的

想問 @chuck-lee ，桌機上 firefox 你是開無痕模式嗎？

**Comment by barry800414** [comment]
我用 browserstack 測 Android 8 + Firefox 
也是要無痕模式下才不行
非無痕是可以用的

**Comment by chuck-lee** [comment]
確定沒有開無痕模式，可能是facebook container造成的

**Comment by mark86092** [comment]
了解，因為我們是用 FB SDK 做為登入，所以如果被擋了，的確就是不能用

**Comment by barry800414** [comment]
https://www.ithome.com.tw/news/122111
看起來確實是如此，內文有提到 `採用Facebook Container也有一些後遺症，當使用者要以臉書憑證建立其它網路服務的帳號或登入其它網路服務時可能會失敗。`

**Comment by barry800414** [comment]
這個問題目前我傾向於不解，因為是 facebook container 造成的問題，目前看似無解。
而它的使用率應該還沒有這麼高，在未來我們新增其他登入方式的時候，就可以解了！

**Comment by chuck-lee** [comment]
我想可以在界面上提醒在隱私模式和facebook container下會異常（不確定ublock或privacy badger之類的外掛是不是也會），提供解決方法好像有點長就算了 XD
