### ISSUE TITLE
薪資工時查詢頁網址修改

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#536]
原本的薪資工時查詢頁，網址當初想說為了讓語意上更好懂，把它設計成像這樣的形式
- /time-and-salary/company/:query/work-time-dashboard
- /time-and-salary/company/:query/work-time-asc
...

最近在做產品服務的驗證，其中一塊，就是想要知道使用者下了關鍵字之後，有沒有找到他想要的資訊。
GA 其實是有這個功能的（[說明文件](https://support.google.com/analytics/answer/1012264)、[GA 報表](https://analytics.google.com/analytics/web/?hl=zh-TW&pli=1#/report/content-site-search-pages/a79990667w119195192p124729205/_u.date00=20180501&_u.date01=20180531/)) 

會長這樣：
![2018-06-17 10 18 11](https://user-images.githubusercontent.com/3805975/41508772-6288c350-727c-11e8-9be2-ee0b795ca511.png)

不過他只能用 query string 去判定使用者是不是下了搜尋關鍵字。意思是我們目前薪資工時查詢頁的路徑設計，沒辦法讓 GA 追蹤。

所以這邊是想討論，要不要把薪資工時查詢頁的路徑，改成像經驗分享查詢那樣，主要使用 query string。
這個 issue 沒有急迫性，只是長遠來說如果要追蹤使用的狀況，改過去會比較好。

**Comment by mark86092** [comment]
可以，不過要記得把舊網址對應到新的網址就好
