### ISSUE TITLE
進入網站時 style 會比 dom 後載入

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#540]
前陣子有發現這個問題，麻煩有空再看一下是什麼原因造成的～
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8353239/41807070-739bf77e-76fb-11e8-977f-110c85021ca7.gif)

**Comment by mark86092** [comment]
https://github.com/goodjoblife/GoodJobShare/blob/master/src/helpers/Html.js. 

Css是放在後面的

**Comment by wutingy** [comment]
當初是有什麼考量嗎？因為正常來說應該要放在 `<head>` 裡
