### ISSUE TITLE
薪資工時查詢頁 routing 修改

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#542]
| 參數  | query 參數名稱 |  |
|---|---|---|
| 分頁  | p  | integer（從1開始） |
| 排序依據  | sort  | `created_at`, `estimated_hourly_wage`, `week_work_time` |
| 排序順序 | order | `descending`, `ascending` | 
| 搜尋種類  | s_by | `company`, `job_title` |
| 搜尋關鍵字 | q | string |

沒有下關鍵字： 不會有 `s_by`, `q`
E.g. ?p=1&sort=created_at&order=descending

有下關鍵字： 不會有 `sort`=`created_at`
E.g. ?sort=week_work_time&order=descending&s_by=company&q=ooo_comapny

基本上是跟經驗分享差不多的路徑設計

記得要把原本的 route redirect 到新的 route：

| 原路徑  | 參數 |  
|---|---|
| /time-and-salary/latest | { sort: created_at, order=descending }  |
| /time-and-salary/sort/time-asc | { sort: created_at, order=ascending } |
| /time-and-salary/work-time-dashboard | { sort: week_work_time, order=descending }  |
| /time-and-salary/sort/work-time-asc | { sort: week_work_time, order=ascending }  |
| /time-and-salary/salary-dashboard | { sort: estimated_hourly_wage, order=descending }  |
| /time-and-salary/sort/salary-asc | { sort: estimated_hourly_wage, order=ascending }  | 
| /time-and-salary/company/:keyword/work-time-dashboard | { sort=week_work_time, order=descending, s_by=company, q = keyword } |
| /time-and-salary/company/:keyword/sort/work-time-asc | { sort=week_work_time, order=ascending, s_by=company, q = keyword } |
| /time-and-salary/company/:keyword/salary-dashboard | { sort=estimated_hourly_wage, order=descending, s_by=company, q = keyword } |
| /time-and-salary/company/:keyword/sort/salary-asc | { sort=estimated_hourly_wage, order=ascending, s_by=company, q = keyword } |
| /time-and-salary/job-title/:keyword/work-time-dashboard | { sort=week_work_time, order=descending, s_by=job_title, q = keyword } |
| /time-and-salary/job-title/:keyword/sort/work-time-asc | { sort=week_work_time, order=ascending, s_by=job_title, q = keyword } |
| /time-and-salary/job-title/:keyword/salary-dashboard | { sort=estimated_hourly_wage, order=descending, s_by=job_title, q = keyword } |
| /time-and-salary/job-title/:keyword/sort/salary-asc | { sort=estimated_hourly_wage, order=ascending, s_by=job_title, q = keyword } |

**Comment by mark86092** [comment]
Look good

**Comment by mark86092** [comment]
這個有想要進行嗎？

**Comment by barry800414** [comment]
這個週六會討論到
我會提網站的大改版，如果大家覺得沒問題的話，這個 issue 就不需要了

**Comment by mark86092** [comment]
看起來不需要了
