### ISSUE TITLE
優化工時薪資Detail的呈現

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/GoodJobShare#549]
<img width="489" alt="2018-07-26 9 04 07" src="https://user-images.githubusercontent.com/7566586/43235317-eae3451e-90b2-11e8-9ae1-e78796bfec9a.png">

想建議template的部分是否可以上灰色，讓answer的部分清楚一點

作法可能先naive的用replace的方式?（畢竟大多數人應該是不會改到template）

**Comment by barry800414** [comment]
我們現在應該沒有這個東西了，close it
