### ISSUE TITLE
小教室 需要能讓 SSR 可以取得資料且放入 state

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#55]

**Comment by peteranny** [comment]
我現在找不太到彥齊之前demo的範例，可以問一下在哪裡可以看嗎？
或是可以直接簡答一下：

component的static fetchData是要：
a. 使用this.props的action?
b. 還是直接dispatch action? <-應該是這個？是的話怎麼import

如果簡答很麻煩，直接告訴我範例在哪我自己去看也可以~感謝><

**Comment by mark86092** [comment]
Here: https://github.com/goodjoblife/GoodJobShare/pull/37#issuecomment-293663932

static，所以沒有 this

範例裡面有做出怎麼克服 a, b
