### ISSUE TITLE
網站明確導引使用者去按粉專讚

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#550]
## 導引的地方
- [ ] 首頁 footer 上方
![2018-08-05 11 45 10](https://user-images.githubusercontent.com/3805975/43682413-ba8ea362-98a6-11e8-9ea5-1925849f5c1e.png)

- [ ] 薪資工時查詢頁下方
![2018-08-05 11 45 27](https://user-images.githubusercontent.com/3805975/43682414-bab9d3fc-98a6-11e8-9e68-c6cf5217609d.png)

- [ ] 以公司或職稱搜尋薪資工時結果頁下方
![2018-08-05 11 45 46](https://user-images.githubusercontent.com/3805975/43682415-bae33bac-98a6-11e8-9d1c-d84202fb353b.png)

- [ ] 經驗分享列表下方
![2018-08-05 11 46 01](https://user-images.githubusercontent.com/3805975/43682416-bb0d8e98-98a6-11e8-95c8-2f48c190e69c.png)

- [ ] 經驗分享列表左方
![2018-08-05 11 46 32](https://user-images.githubusercontent.com/3805975/43682417-bb383080-98a6-11e8-896d-fba5d5172d10.png)

- [ ] 單篇經驗分享下方
![2018-08-05 11 46 53](https://user-images.githubusercontent.com/3805975/43682418-bb63e496-98a6-11e8-85da-99b899a1d91d.png)

- [ ] 單篇小教室下方
![2018-08-05 11 47 08](https://user-images.githubusercontent.com/3805975/43682419-bb8f3484-98a6-11e8-85f7-d27ce48c2ef6.png)

- [ ] 小教室列表下方
![2018-08-05 11 54 48](https://user-images.githubusercontent.com/3805975/43682420-bbba9bba-98a6-11e8-9cc9-0f5c803f0d3c.png)

--- 

## 按鈕形式
1. [Facebook Page Plugin](https://developers.facebook.com/docs/plugins/page-plugin/)
![2018-08-05 12 01 17](https://user-images.githubusercontent.com/3805975/43682433-510ec0c4-98a7-11e8-9ddb-e234a5fbb23f.png)

2. [Facebook Like Button](https://developers.facebook.com/docs/plugins/like-button/)
![2018-08-05 12 01 44](https://user-images.githubusercontent.com/3805975/43682434-5f92247e-98a7-11e8-9c56-9d0efb3b422c.png)

---

**Comment by wutingy** [comment]
小教室 cc 授權每一篇的最後其實都有放，這邊要拿掉也是可以。

**Comment by wutingy** [comment]
<img width="1185" alt="screen shot 2018-08-05 at 6 40 22 pm" src="https://user-images.githubusercontent.com/8353239/43685087-12db7300-98df-11e8-97c2-dbdcaa9303c8.png">

**Comment by wutingy** [comment]
<img width="1384" alt="screen shot 2018-08-05 at 6 41 39 pm" src="https://user-images.githubusercontent.com/8353239/43685098-3d5b929a-98df-11e8-96ca-2a942ba53b7e.png">

**Comment by barry800414** [comment]
@wutingy  每個放的地方都要置左嗎？ 
我覺得有些地方好像置中比較好

**Comment by wutingy** [comment]
好像是誒，可以針對不同的頁面做調整。

**Comment by barry800414** [comment]
@wutingy 我送 PR 了 #551 

不過這個：

經驗分享列表左方
![](https://user-images.githubusercontent.com/3805975/43682417-bb383080-98a6-11e8-896d-fba5d5172d10.png)

我懶得做了，覺得夠多地方了
