### ISSUE TITLE
[UX] 點數機制討論

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#582]
[permission block](https://o2geqq.axshare.com/#g=1&p=permission_block)
覺得需要加上使用者已登入、點數足夠的 case，點選文章閱讀跳一個 notify 在左下角， 
讓他知道他看一篇是要收點數的，不然會有隨便點一點，點數就用完了，但也都沒看到什麼的狀況，或是在他得到點數的時候（註冊、分享）流程上能更清楚讓使用者知道如何扣點。

**Comment by wutingy** [comment]
啊....我漏看了到那段，拍謝，所以是不管怎樣都會有一個 block。

不過在他解鎖以前，是否需要想辦法讓他知道有哪些欄位？例如說此文章可能有幾題 QA，有幾個字等等？

**Comment by barry800414** [comment]
@wutingy  覺得有個話會更好，我需要補在 axure 裡面嗎？
還是妳直接畫即可？

**Comment by wutingy** [comment]
@barry800414 文案有空補一下比較好喔
