### ISSUE TITLE
[設計] 發送驗證信畫面

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#584]
- 1.1 [未登入、查看文章沒有權限](https://app.zeplin.io/project/5c316d528cc2d146a73dfc59/dashboard?seid=5c3170ccdeeb876988d7a823)：不管是否曾經註冊登入，只要沒有驗證過的都會在登入完後跳發送驗證信的 modal。
被擋住 > fb登入 > email 認證(send form > loading > done) > 關閉 modal
被擋住 > fb登入 > email 認證 > 到信箱驗證 (見下方 1.2)
- 1.2 [email 認證流程](https://zpl.io/VKK681X)
信箱驗證 > 驗證成功 > 導到文章直接解鎖(右上角跳notify)
信箱驗證 > 驗證失敗
- 2.1 [留資料增加 Email 欄位](https://zpl.io/bld6EWv)：留資料的表單鼓勵使用者留 email，不論是否登入。
留資料有填 Email 欄位 > 發送驗證信 > 驗證成功（導回網站）
 **問題：** 已登入、已驗證的人是否不要 show 該欄位，或是直接帶入他的 email？
- 2.2 [email 認證流程](https://zpl.io/brWP6ee)
信箱驗證 > 驗證成功
信箱驗證 > 驗證失敗
- 3.1 [已登入、未留信箱](https://zpl.io/V0Rp19w)
- 4.1 [已登入、已留信箱未驗證](https://zpl.io/b6jB7Nm)

**Comment by barry800414** [comment]
> 已登入、已驗證的人是否不要 show 該欄位，或是直接帶入他的 email？

覺得可以不用顯示

**Comment by barry800414** [comment]
想問：
1. 如果不是想要解鎖某個內容而註冊，也是走一樣的流程對嗎？ （文案可能稍微不同）
2. 如果是以前已經註冊過，但尚未驗證過信箱，進到主站後，會主動跳 modal 嗎？ 還是只顯上上方橫條？

**Comment by barry800414** [comment]
> 被擋住 > fb登入 > email 認證(send form > loading > done) > 關閉 modal
> 被擋住 > fb登入 > email 認證 > 到信箱驗證 (見下方 1.2)

我不太確定這兩個有什麼差別～

**Comment by wutingy** [comment]
done design
