### ISSUE TITLE
Login Flow Refactoring

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/GoodJobShare#586]
## Current
FB SDK Login --> get FB Token --> save in session storage --> request with FB Token

## Next Version
FB SDK Login --> get FB Token --> call `/auth/facebook` API to validate and get a GoodJob Token --> save in local storage --> request with GoodJob Token

* check if the token exists and if expired, if not logout for user.

**Comment by barry800414** [comment]
這個 issue 已經完成了嗎？

**Comment by WendellLiu** [comment]
Yes 我關了
