### ISSUE TITLE
Modal可否按背景可關閉

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/GoodJobShare#593]
目錢的Modal打開後，要關閉一定要按叉叉
例如「查看檢舉」和「檢舉此篇文章」等Modal

想說是否可以按背景就可以關閉
不過某些情況下Modal不可按背景關閉，例如有post行為的就不行，只有純get的才可以按背景關閉

不知道這樣改合理嗎？

**Comment by wutingy** [comment]
可以！！！

**Comment by peteranny** [comment]
我剛看了一下 react-onclickoutside 主要是用在class component，用在我們的stateless反而麻煩一點，所以我就還是用自己寫的方式了
