### ISSUE TITLE
以公司/職稱搜尋薪資工時頁面 改版

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#600]
#### UI wireframe
- [查詢結果頁](https://o2geqq.axshare.com/#g=1&p=%E6%9F%A5%E8%A9%A2%E5%85%AC%E5%8F%B8%E8%96%AA%E8%B3%87%E5%B7%A5%E6%99%82%E7%B5%90%E6%9E%9C%E9%A0%81)
- [單一公司薪資工時頁](https://o2geqq.axshare.com/#g=1&p=%E5%85%AC%E5%8F%B8%E8%96%AA%E8%B3%87%E5%B7%A5%E6%99%82%E9%A0%81)
- [單一職業薪資工時頁](https://o2geqq.axshare.com/#g=1&p=%E8%81%B7%E6%A5%AD%E8%96%AA%E8%B3%87%E5%B7%A5%E6%99%82%E9%A0%81)

#### UI
因為只是原本的頁面下去改，沒有特別畫 UI，我直接從前端修改 element 示意。需要的話再請 @wutingy  出

下面這張是以公司搜尋薪資工時結果頁
![screencapture-goodjob-life-time-and-salary-company-work-time-dashboard-2019-01-30-07_32_02](https://user-images.githubusercontent.com/3805975/51949167-7cc41480-2466-11e9-966b-446b2c5de56d.png)
下面這張是單一公司薪資工時頁
![screencapture-goodjob-life-time-and-salary-company-work-time-dashboard-2019-01-30-08_07_56](https://user-images.githubusercontent.com/3805975/51949169-7cc41480-2466-11e9-92b9-8d361f66dc57.png)

### Route change

<table>
  <tr>
    <td><strong>舊的 route</strong></td>
    <td><strong>新的 route</strong></td>
  </tr>
  <tr>
    <td colspan="3">以公司名稱搜尋薪資工時頁面</td>
  </tr>
  <tr>
    <td>/time-and-salary/company/<strong>:query</strong>/work-time-dashboard</td>
    <td>/salary-work-times?q=<strong>:query</strong>&s_by=company</td>
  </tr>
  <tr>
    <td>/time-and-salary/company/<strong>:query</strong>/sort/work-time-asc</td>
    <td>同上</td>
  </tr>
  <tr>
    <td>/time-and-salary/company/<strong>:query</strong>/salary-dashboard</td>
    <td>同上</td>
  </tr>
  <tr>
    <td>/time-and-salary/company/<strong>:query</strong>/sort/salary-asc</td>
    <td>同上</td>
  </tr>
<tr>
    <td colspan="3"  >以職稱名稱搜尋薪資工時頁面</td>
  </tr>
  <tr>
    <td>/time-and-salary/job-title/<strong>:query</strong>/work-time-dashboard</td>
    <td>/salary-work-times?q=<strong>:query</strong>&s_by=job_title</td>
  </tr>
  <tr>
    <td>/time-and-salary/job-title/<strong>:query</strong>/sort/work-time-asc</td>
    <td>同上</td>
  </tr>
  <tr>
    <td>/time-and-salary/job-title/<strong>:query</strong>/salary-dashboard</td>
    <td>同上</td>
  </tr>
  <tr>
    <td>/time-and-salary/job-title/<strong>:query</strong>/sort/salary-asc</td>
    <td>同上</td>
  </tr>
<tr>
    <td colspan="3"  >單一公司薪資工時頁</td>
  </tr>
  <tr>
    <td>原本沒有</td>
    <td>/companies/<strong>:companyName</strong>/salary-work-times?p=<strong>:page</strong></td>
  </tr>
<tr>
    <td colspan="3"  >單一職稱薪資工時頁</td>
  </tr>
  <tr>
    <td>原本沒有</td>
    <td>/job-titles/<strong>:jobTitle</strong>/salary-work-times?p=<strong>:page</strong></td>
  </tr>
</table>

附註：
1. query string 的參數命名參照職場經驗搜尋頁，參數都一樣方便 google analytics 追蹤
2. 如果搜尋結果只有一個，直接跳轉到該頁

### 其他
- [ ] 這一頁 API 會改用 GraphQL （by @LittleWhiteYA ），尚未完成。由 @barry800414  出 GraphQL 回傳的假資料，方便前端先開發

**Comment by barry800414** [comment]
@peteranny 這個你如果有空可以先寫，graphql 的部分確定了和你說～

**Comment by peteranny** [comment]
想問 `/companies/:companyName/salary-work-times?p=:page` 使用的API跟query一樣嗎？還是會另一個API？

**Comment by peteranny** [comment]
另外就是，會需要分頁pager的UI

**Comment by barry800414** [comment]
> 想問 `/companies/:companyName/salary-work-times?p=:page` 使用的API跟query一樣嗎？還是會另一個API？

你想問的是跟誰一樣呢～？

之後這些頁面，都會改用 graphQL ，schema 可以參考 https://github.com/goodjoblife/WorkTimeSurvey-backend/issues/518 裡面的 query：
```
type Query {      
    "搜尋公司 (query 與公司名稱僅需前面的字串符合）"
    search_companies(query: String!): [Company!]!         -> 以公司名稱搜尋用
    "取得單間公司（name 與公司名稱需完全符合）"
    company(name: String!): Company!           -> 取得單一公司資料用
      
    "取得職稱列表（query 與職稱僅需前面的字串符合）"
    search_job_titles(query: String!): [JobTitle!]!           -> 以職稱搜尋用
    "取得職稱（query 與職稱僅需完全符合）"
    job_title(name: String!): JobTitle!             -> 取得單一職稱資料用
}
```

**Comment by barry800414** [comment]
> 另外就是，會需要分頁pager的UI 

可以直接用現成的：
<img width="506" alt="2019-02-21 11 53 15" src="https://user-images.githubusercontent.com/3805975/53182167-ea153080-3633-11e9-8326-41c1059d2f0d.png">

**Comment by peteranny** [comment]
另外要問，`/companies/:companyName/salary-work-times?p=:page` 要有分頁
但是 `/salary-work-times?q=**:query**&s_by=company`也是有單一公司可能有很多職位的問題，這邊不分頁就很奇怪，可是可能會很多公司都很多職位，就沒辦法做統一分頁

**Comment by peteranny** [comment]
還有要問：單一職稱工時頁長什麼樣子？？

**Comment by barry800414** [comment]
> 另外要問，`/companies/:companyName/salary-work-times?p=:page` 要有分頁
但是 `/salary-work-times?q=**:query**&s_by=company`也是有單一公司可能有很多職位的問題，這邊不分頁就很奇怪，可是可能會很多公司都很多職位，就沒辦法做統一分頁

`/companies/:companyName/salary-work-times?p=:page` 這個頁面顯示的，是該家公司底下的薪資工時資料，是這一頁：
![screencapture-goodjob-life-time-and-salary-company-work-time-dashboard-2019-01-30-08_07_56](https://user-images.githubusercontent.com/3805975/51949169-7cc41480-2466-11e9-92b9-8d361f66dc57.png)

而 `/salary-work-times?q=**:query**&s_by=company` 是搜尋有哪些公司有薪資工時資料，是以公司的名稱做分組，跟職稱完全無關。也就是這一頁：
![screencapture-goodjob-life-time-and-salary-company-work-time-dashboard-2019-01-30-07_32_02](https://user-images.githubusercontent.com/3805975/51949167-7cc41480-2466-11e9-966b-446b2c5de56d.png)

**Comment by barry800414** [comment]
> 還有要問：單一職稱工時頁長什麼樣子？？

會長的像這樣
![51949169-7cc41480-2466-11e9-92b9-8d361f66dc57](https://user-images.githubusercontent.com/3805975/53286732-c7a72280-37ad-11e9-9c70-10e2156ade26.png)

這樣會太抽象嗎？
還是會希望有明確的介面呢？

**Comment by peteranny** [comment]
@barry800414 
所以是說， `/salary-work-times?q=**:query**&s_by=company` 已經不需要collapse了，而是單純列表，每一項會連結至該項目的那一頁，這樣嗎？

**Comment by barry800414** [comment]
> @barry800414
所以是說， `/salary-work-times?q=**:query**&s_by=company` 已經不需要collapse了，而是單純列表，每一項會連結至該項目的那一頁，這樣嗎？

沒錯！ `/salary-work-times?q=**:query**&s_by=company` 比較像 google 搜尋的結果頁，內容要再點進去看

**Comment by peteranny** [comment]
`/salary-work-times?q=**:query**&s_by=company` 感覺也會需要分頁耶，需要嗎？

**Comment by barry800414** [comment]
我自己覺得不用，除非他打”公司”，不然應該長度不致於太長。有出什麼問題再做分頁吧！

**Comment by peteranny** [comment]
我搜尋職稱`工程師`就超多，多到瀏覽器要炸掉...

**Comment by barry800414** [comment]
`工程師`確實很多，不過，想問瀏覽器 lag 的原因是什麼？
因為這個頁面，應該只出現 職稱＋資料數量

**Comment by peteranny** [comment]
我電腦比較慢啦，我只是要表達真的很多，不過如果你覺得還好那就先不管這個

**Comment by barry800414** [comment]
麻煩你先做，我跟 @LittleWhiteYA  溝通做分頁

**Comment by barry800414** [comment]
剩下的 TODO:
- [ ] 換接 graphql API  @peteranny 
- [ ] 資料排序與分頁 @peteranny 
- [ ] 權限區塊 @peteranny 
  - [ ] [單一公司薪資工時頁](https://o2geqq.axshare.com/#g=1&p=%E5%85%AC%E5%8F%B8%E8%96%AA%E8%B3%87%E5%B7%A5%E6%99%82%E9%A0%81) 
  - [ ] [單一職稱薪資工時頁](https://o2geqq.axshare.com/#g=1&p=%E8%81%B7%E6%A5%AD%E8%96%AA%E8%B3%87%E5%B7%A5%E6%99%82%E9%A0%81)
  - [ ] 薪資工時列表可以不用擋了
- [ ] 修改 helmet @barry800414

**Comment by peteranny** [comment]
@barry800414  資料排序與分頁不是已經做好了嗎？
