### ISSUE TITLE
註冊登入及驗證信驗證 詳細流程圖

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#611]
藍色是現有的功能，綠色是待開發的功能  
2019.03.05 更新
![email 2](https://user-images.githubusercontent.com/3805975/53773177-3c076180-3f24-11e9-80d5-9ab3582cfcf0.png)

原檔：[google drawing](https://docs.google.com/drawings/d/1L9WOgrlEYy0ASiEa-I07zDi1n7cnnA8FEa5D_YSvcCM/edit?usp=sharing)

**Comment by mark86092** [comment]
第二張圖：

信箱 --> 驗證網址 --> 後端檢查

這邊要記得處理：

A 帳號登入了，又從 email 收了 B 帳號，這時候會發生什麼事情？

1) 變成以 B 的身份登入？
2) 失敗？

**Comment by barry800414** [comment]
> A 帳號登入了，又從 email 收了 B 帳號，這時候會發生什麼事情？
> 1. 變成以 B 的身份登入？
> 2. 失敗？

根據我們（我和 @wutingy  @WendellLiu  ）討論的結果，會直接變成以 B 的身份的登入
也就是驗證成功後，直接發登入的 token 給該使用者，並覆蓋掉原本的 token
