### ISSUE TITLE
Email Template 製作

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#612]
設計 + 出 html

done:
- [x] email template 驗證信
- [x] 歡迎信（驗證成功信）[https://zpl.io/agzK3GD](https://zpl.io/agzK3GD)

先做：
- [ ] 留的面試經驗瀏覽次數達到指定數字
- [ ] 留的薪資工時資料瀏覽次數達到指定數字
- [ ] 留的工作心得瀏覽次數達到指定數字

後續：
- [ ] 有留言時，當天寄信
- [ ] 面試經驗邀請信

**Comment by barry800414** [comment]
@wutingy  我今天把 email template 的文案需求給 Yudi 了
她週末可以完成，我再請她給妳設計 ＆ 寫成 HTML 

文件： https://docs.google.com/document/d/1BRprVOZLUV4D1bFIGhKcC-SZGHlE3xMmgfDW4sHZ4S4/edit?usp=sharing

**Comment by wutingy** [comment]
@barry800414 這個是不是沒有要做了XD
我換成你上週說的：
「就是這次會動到網站的解鎖機制
給過去曾經留過資料的使用者，一個早期忠實用戶的獎勵

[https://hopk8t.axshare.com/#id=p6f9vb&p=%E6%9C%89%E6%9C%89%E6%95%88%E8%B3%87%E6%96%99%E8%80%85&g=1](https://hopk8t.axshare.com/?fbclid=IwAR3Oc_VQ_ZKh59KtU6GwZ4j7Cn1EtjGBKWhKdLil72Vfzq-VVwNoxPgXkBk#id=p6f9vb&p=%E6%9C%89%E6%9C%89%E6%95%88%E8%B3%87%E6%96%99%E8%80%85&g=1)

上面的連結是信件的內容，可以請妳協助設計的更好看，然後是以 email 相容的 html 給我嗎？」

**Comment by barry800414** [comment]
@wutingy 這個確實沒有要做了，我先 close 這張，另開一張

**Comment by barry800414** [comment]
@wutingy 我另開在這邊：https://github.com/goodjoblife/GoodJobShare/issues/1092

**Comment by wutingy** [comment]
ＯＫ！
