### ISSUE TITLE
ESLint加上prop-types相關檢查

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/GoodJobShare#614]
想加上`react/prop-types`, `react/no-unused-prop-types`
不知道是不是之前被拿掉，不過還是覺得加一下是不是比較好

**Comment by mark86092** [comment]
@barry800414 這張我先開一個開發用 branch (#1327)，把這張 issue 的功能加上去時，勢必會有大量的改動，開發用 branch 比較好追蹤
