### ISSUE TITLE
薪資工時頁面改版 Bug 回報

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#622]

**Comment by barry800414** [comment]
### Major
- [ ] 進到薪資工時頁面的 route 是 /salary-work-times
- [ ] 搜尋空白沒有擋，應該要進到預設的頁面
- [ ] 沒有排序的選單了，預設就是照時間排
- [ ] 單一公司/職業的薪資工時頁面上方搜尋 bar 移除
- [ ] table 中間 inject 的 row 拔掉
- [ ] 搜尋結果要按照資料數排序

### Minor
- [ ] 表定實際工時欄位出現 null 
- [ ] 後端還是需要分頁

### UI
- [ ] 上一頁按鈕

**Comment by mark86092** [comment]
UI

- [ ] TimeAndSalary 底下的 style 需要重新整理

**Comment by mark86092** [comment]
- [ ] SalaryWorkTime / SearchScreen 的連結 盡可能使用 `<Link>` 而不是 `history.push`

**Comment by peteranny** [comment]
> Major

這些都是確定要這樣改的了嗎？是的話有些看不太懂，到時再麻煩語音詳細跟我說一下~

**Comment by mark86092** [comment]
@peteranny 哪個不確定，我在補充詳細一點

**Comment by barry800414** [comment]
@mark86092  剛我有跟 @peteranny  語音 sync 了，他應該都知道我們說的是什麼了

其中單一公司/職業的頁面如果是從搜尋頁點進來的話，網址會長的類似像這樣
http://localhost:3000/companies/DJA/salary-work-times?q=DJ&s_by=company

後面的 query string 是為了讓上方的搜尋 bar 保留一樣的字
我覺得這個可以保留～

**Comment by mark86092** [comment]
@barry800414 有結論就好，因為我的考慮只有 page 這個參數不要帶過去就好

**Comment by barry800414** [comment]
@peteranny  看起來主要是剩
- [ ] 進到薪資工時頁面的 route 是 /salary-work-times/latest
- [ ] /salary-work-times/latest 沒有排序的選單了，預設就是照時間排 

對嗎？

**Comment by barry800414** [comment]
沒事我誤會了，主要的 issue 都已經解了！

**Comment by barry800414** [comment]
差幾個要 enhance 的地方，我明天可送 PR 
- [ ] 單一職稱的薪資工時排序，建議預設是最新到最舊
<img width="835" alt="螢幕快照 2019-04-05 上午1 16 45" src="https://user-images.githubusercontent.com/3805975/55575136-c3710c00-5740-11e9-8dd8-85bdbfb42cb9.png">

- [ ] 表訂工時 / 實際工時出現 null 
<img width="809" alt="螢幕快照 2019-04-05 上午1 17 25" src="https://user-images.githubusercontent.com/3805975/55575137-c409a280-5740-11e9-9332-abb1d59e80f9.png">
