### ISSUE TITLE
整理 style，讓小教室能提前上線

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#63]
- [x] Header-desktop
- [x] Header-mobile
- [x] Footer-desktop&mobile
- [x]  加上 new tag 在小教室上
- [x]  小教室 menu style
- [x]  小教室單篇 style
- [x]  小教室單篇 contentful 示範
- [x] add Loader component
- [x]  所有圖片 resize，全部要用 [imageOptim](https://imageoptim.com/mac) 縮過，放到 [Google Dive](https://drive.google.com/drive/folders/0B3qik8BMBitbRkJCV2lfV28xOXM) 上
- [x]  [小教室文章說明補充](https://docs.google.com/presentation/d/16dpxuk3RmZ9sdwgfxbtqUxrcDHivptChypQ_8hI3mhs/edit#slide=id.p)（我加了一些編輯注意事項）
- [x]  小教室作者權限
- [x]  回到上方
- [x]  用 `order` 調整順序，從小到大
- [ ] error msg component >> if not found go to 404

**Comment by wutingy** [comment]
Q: header 登入是否可以先不做？

**Comment by mark86092** [comment]
是指把 登入 功能在 header 移除嗎？

**Comment by peteranny** [comment]
如果 #60 有要merge的話，那麼還會多loading和error的style，不過我不知道彥齊目前有沒有打算要merge

**Comment by mark86092** [comment]
@peteranny 我還沒看它，原則上會 merge

不過你那邊還有一個東西要做，針對 列表頁 與 單篇小教室 打不同的 API

**Comment by wutingy** [comment]
@mark86092 恩恩，因為在小教室這邊登入沒有什麼用
