### ISSUE TITLE
RWD

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#631]
https://github.com/goodjoblife/GoodJobShare/pull/624
這個 PR 的 rwd 需要製作

**Comment by barry800414** [comment]
想請 @wutingy  協助確認

- [ ] 預設的薪資工時頁  RWD style
- [ ] 以公司 / 職稱搜尋薪資工時頁 RWD style
- [ ] 單一公司 ／職稱的薪資工時頁 RWD style 
- [ ] 單一公司 ／職稱的薪資工時頁沒權限被擋住時的權限區塊  RWD style
