### ISSUE TITLE
單一公司/職業的薪資工時頁面上方搜尋 bar 移除

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#632]
![image](https://user-images.githubusercontent.com/1908007/54704060-ffb74080-4b74-11e9-80c1-4bb5aaa7a5a8.png)

上方的搜尋 bar 要移除

## 目前這個功能有 bug

重現：

1. 搜尋 工程師，並切換到第 n 頁

![image](https://user-images.githubusercontent.com/1908007/54704132-25444a00-4b75-11e9-94dc-785b4d6e2d7f.png)

2. 隨意點入其中一個

![image](https://user-images.githubusercontent.com/1908007/54704236-4efd7100-4b75-11e9-8a8e-cf96d1bcef2a.png)

點入後頁碼沒有重設為 1

**Comment by peteranny** [comment]
> 上方的搜尋 bar 要移除

這是新討論出來的spec嗎？是因為希望使用者在這一頁專心看搜尋結果，不要讓他在這頁進行搜尋？

**Comment by barry800414** [comment]
@mark86092  我仔細想了一下，因為可能有不少人會是從 google 直接進到單一公司 / 職稱的薪資工時頁，沒有搜尋 bar 的話，會不知道要去哪邊查詢

我的想法是
1. 把職業薪資工時大募集先移除
2. 進到單一薪資工時的頁面之後，`q`, `s_by` 這兩個參數就可以移除了

cc @wutingy

**Comment by mark86092** [comment]
@barry800414 OK，結論看起來就是把 bug 解掉就好

**Comment by mark86092** [comment]
@peteranny 

> 進到單一薪資工時的頁面之後，q, s_by 這兩個參數就可以移除了

再麻煩你 update 你的 PR 了

**Comment by barry800414** [comment]
done by https://github.com/goodjoblife/GoodJobShare/pull/635
