### ISSUE TITLE
React Router 奇怪的路由問題

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#638]
![image](https://user-images.githubusercontent.com/1908007/55092381-790ee000-50ed-11e9-837b-f97e5f7b6536.png)

如圖，當網址參數是 `音樂教室%2F樂器行` 時，應該要取出 `音樂教室/樂器行`

![image](https://user-images.githubusercontent.com/1908007/55092413-8926bf80-50ed-11e9-8962-71c490bcab40.png)

但神奇的是：網址參數是 `音樂教室%25樂器行`，會正確取出 `音樂教室%樂器行`

這個問題在 master / dev 上都有，影響只有搜尋的字串含有 "/" 才會怪怪的

**Comment by mark86092** [comment]
看起來是 https://github.com/ReactTraining/history/issues/ 689

的問題，等待未來它們發新版處理

**Comment by mark86092** [comment]
整理網址處理應該的流程

1. 伺服器 (`req.url`) / client (`window.location`) 會收到這樣的網址： `/companies/%E7%99%BB%E9%A8%8F%E7%A7%91%E6%8A%80%2F%E6%A5%AD%E5%8B%99/salary-work-times?q=%E7%99%BB%E9%A8%8F%E7%A7%91%E6%8A%80%2F%E6%A5%AD%E5%8B%99&s_by=company`

2. history.createLocation 會 parse 成： 
```
{ pathname: '/companies/%E7%99%BB%E9%A8%8F%E7%A7%91%E6%8A%80%2F%E6%A5%AD%E5%8B%99/salary-work-times',
  search: '?q=%E7%99%BB%E9%A8%8F%E7%A7%91%E6%8A%80%2F%E6%A5%AD%E5%8B%99&s_by=company',
  hash: '' }
```

3. react router 的 matchPath 會給出：

```
{ params: { companyName: '音樂教室/樂器行' }
}
```

目前官方修復第二步中

**Comment by barry800414** [comment]
剛剛測試，看起來已經解掉了，我就先關掉了
