### ISSUE TITLE
react 跟可以同時偵測螢幕寬度 ＆ 又不破壞 server-side rendering 的方法

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#645]
需求來源：
單一公司/職稱薪資工時頁面的權限區塊，在不同螢幕大小下，要能 render 不一樣的內容

嘗試用 [react-responsive](https://github.com/contra/react-responsive) 不能 work
need help

**Comment by mark86092** [comment]
這問題能描述清楚一點嗎？不是很懂想做到的點

**Comment by barry800414** [comment]
就是說，component 要能夠根據目前螢幕的寬度，去 render 出不一樣的內容
（因為用 css 做不到想做的事情）

**Comment by peteranny** [comment]
什麼樣的內容？為何CSS做不到？可能要描述清楚一點才知道為何你會說做不到（我想像的CSS是可以做得到的）

**Comment by barry800414** [comment]
@peteranny  就是薪資工時的權限區塊 

大螢幕的情況下，我們要 render 一個大的 td (with rowSpan=2 colSpan=N)
<img width="957" alt="螢幕快照 2019-03-31 下午1 32 51" src="https://user-images.githubusercontent.com/3805975/55290225-268e3600-5403-11e9-81d9-439355079805.png">

小螢幕的情況下，每個 row 的 td 都要 render 出來
<img width="689" alt="螢幕快照 2019-03-31 下午7 28 19" src="https://user-images.githubusercontent.com/3805975/55290226-268e3600-5403-11e9-949d-5552153216cd.png">

**Comment by barry800414** [comment]
@peteranny  你現在的寫法，在手機上面會只有第一筆資料有黃色的權限區塊～

**Comment by mark86092** [comment]
看起來要 render 的是 `每個 row 的 td 都要 render 出來` + ` render 一個大的 td`

然後，每個 row 的在大螢幕 `display: none`
大 td 的在小螢幕是 `display: none`

這樣應該行吧？

**Comment by mark86092** [comment]
BTW, 權限機制的檢查並沒有在 SSR 有參與到喔
