### ISSUE TITLE
表單拆頁 + 點數制 UI

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#649]
wireframe: https://o2geqq.axshare.com/

- [x] 面試表單
- [x] 單篇經驗分享介面調整
- [x] 其他表單
- [ ] 點數制

**Comment by barry800414** [comment]
我把面試表單獨立拆出來一個 issue 喔

**Comment by wutingy** [comment]
@barry800414 
[單篇經驗分享介面調整](https://zpl.io/bo8D1gX)
