### ISSUE TITLE
合併查詢改版 UI

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#650]
## 需要設計的頁面

- [x] 公司總覽：[上鎖](https://zpl.io/aRxyRlE)、[解鎖](https://zpl.io/aBWgB8p)
- [x] 搜尋頁面：[search bar](https://zpl.io/2pkDPNr)：要看工程是否可以合併查詢，否則有公司職稱的選項很難放在 header
- [x] 首頁（查詢區塊、公司職業 carousel）
- [x] 將網站所有的表格都改成卡片式

- 注意解鎖前後設計以及不同卡片的欄位差異
- 薪資工時看看要不要有底色

- [ ] 薪資福利單篇
- [x] 薪資工時頁面：上方改成圓餅圖看看（位置在下方） [先做上面的chart](https://zpl.io/VQvrJlR)
- [ ] 單篇導回公司職稱

## Wireframe
首頁：https://o2geqq.axshare.com/#g=1&p=%E9%A6%96%E9%A0%81
公司總覽：https://o2geqq.axshare.com/#g=1&p=%E5%85%AC%E5%8F%B8%E7%B8%BD%E8%A6%BD%E9%A0%81
資料整合後的搜尋頁面：https://o2geqq.axshare.com/#g=1&p=%E7%B6%9C%E5%90%88%E6%90%9C%E5%B0%8B%E7%B5%90%E6%9E%9C%E9%A0%81
薪資福利單篇：
https://o2geqq.axshare.com/#g=1&p=%E8%96%AA%E8%B3%87%E7%A6%8F%E5%88%A9%E5%96%AE%E7%AF%87
資料卡片有解鎖、沒解鎖：
https://o2geqq.axshare.com/#g=1&p=%E8%B3%87%E6%96%99%E5%8D%80%E5%A1%8A%E8%AA%AA%E6%98%8E

**Comment by barry800414** [comment]
這個是部落格 header + logo 的 issue 嗎？

**Comment by wutingy** [comment]
單篇導回公司、職稱的方法：
https://o2geqq.axshare.com/#g=1&p=%E5%96%AE%E7%AF%87%E5%B0%8E%E5%9B%9E%E5%85%AC%E5%8F%B8%E8%81%B7%E7%A8%B1%E7%A4%BA%E6%84%8F_2_%EF%BC%88%E6%96%87%E6%9C%AB%EF%BC%89

**Comment by wutingy** [comment]
chart 參考：http://recharts.org/
https://jsfiddle.net/alidingling/xqjtetw0/

**Comment by barry800414** [comment]
### 公司的薪資圖表（範例）
<img width="537" alt="螢幕快照 2019-08-31 下午9 46 05" src="https://user-images.githubusercontent.com/3805975/64064785-c52ff480-cc38-11e9-9aa4-277cc6c1c563.png">

https://jsfiddle.net/barry800414/9468wgek/2/

### 公司的工時圖表、職業的工時圖表（範例）
<img width="520" alt="螢幕快照 2019-08-31 下午9 44 49" src="https://user-images.githubusercontent.com/3805975/64064770-9580ec80-cc38-11e9-88a4-7ab77143a151.png">
https://jsfiddle.net/barry800414/fpewotzh/8/


### 職業的薪水圖表（範例）
<img width="518" alt="螢幕快照 2019-08-31 下午9 49 13" src="https://user-images.githubusercontent.com/3805975/64064828-32dc2080-cc39-11e9-951f-e88e574ff8fa.png">

https://jsfiddle.net/barry800414/o1ap7rw3/3/

**Comment by barry800414** [comment]
DONE
