### ISSUE TITLE
職場經驗單篇、薪資工時預設列表頁 API 換 GraphQL 

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#660]
因為之後要算瀏覽次數，前端要把 API 換成 graphQL 的 API

**Comment by peteranny** [comment]
預設列表頁說的是`/salary-work-times/latest`這一頁嗎？
我看不太出來是要用哪個API
<img width="319" alt="螢幕快照 2019-04-30 上午12 38 52" src="https://user-images.githubusercontent.com/7566586/56911769-5868ea00-6ae0-11e9-9915-6f0b5d30ac2c.png">

**Comment by peteranny** [comment]
職場經驗單篇指的是像這頁對嗎`/experiences/5cba9522e9eb050011b06d1d`
計算瀏覽次數，是把`fetchExperience`和`fetchReplies`一併換成graghql API對嗎

**Comment by barry800414** [comment]
> 預設列表頁說的是 /salary-work-times/latest 這一頁嗎？

是的，用這個 query https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/master/schema/salary_work_time.js#L100

**Comment by barry800414** [comment]
> 職場經驗單篇指的是像這頁/experiences/5cba9522e9eb050011b06d1d嗎

是的

> 然後要計算瀏覽次數，是說我需要換掉fetchExperience，那我想問同一頁的fetchReplies是否就可以不用換？

我剛看了一下 GraphQL schema，好像少寫 experience 去拿到 reply ，這個會再補上
照理說從 experience 要能拿到 reply

**Comment by mark86092** [comment]
Done !
