### ISSUE TITLE
職場經驗單篇 UI 修改

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#669]
https://zpl.io/bo8D1gX

**Comment by barry800414** [comment]
@WendellLiu  我想問這個 issue 的進度如何，應該有過幾週了，想要跟你抓個明確的時程喔！

**Comment by WendellLiu** [comment]
因為貓的事，我這兩週可能沒什麼時間。我抓個五月底給你，抱歉。

**Comment by barry800414** [comment]
好的，非常抱歉，我沒注意到這件事
我瞭解了～
如果時間上允許我會先做或重新分配，如果有調動我會跟你說

**Comment by WendellLiu** [comment]
@barry800414 
@@ 沒關係，我沒有特別提出是我的問題，再麻煩你安排了。

**Comment by barry800414** [comment]
這個 issue 我先撿來做了～

**Comment by barry800414** [comment]
@wutingy 這個 issue 差 RWD style 須確認
應該要改的部分很少，我錄了一個 GIF demo 一下：

![Y52uUBXoOX](https://user-images.githubusercontent.com/3805975/59617174-6b9b4c00-9158-11e9-8f44-5b1822b9466c.gif)

覺得應該只有螢幕 < 550 的時候，樣式需要小調整一下
