### ISSUE TITLE
經驗單篇、薪時搜尋：從黃色block登入失敗

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/GoodJobShare#680]
有點大條

如圖，從下方黃色的框登入都不會成功，但上方header可以

![http://g.recordit.co/Ap8JuPp2Du.gif](http://g.recordit.co/Ap8JuPp2Du.gif)

**Comment by peteranny** [comment]
有點嚴重

@barry800414  @WendellLiu @mark86092

**Comment by barry800414** [comment]
@peteranny  你方便回報：
1. 作業系統、瀏覽器版本
2. localStorage 裡面有關登入的資料嗎 （我記得是 persist:goodjob）
3. devtools 裡面 console 、network 的錯誤訊息

盡可能把重現步驟都告訴我們

**Comment by peteranny** [comment]
> 作業系統、瀏覽器版本

Mac

Firefox, Safari有問題
Chrome沒問題

> localStorage 裡面有關登入的資料嗎 （我記得是 persist:goodjob）

```
{"auth":"\"{\\\"data\\\":{\\\"status\\\":\\\"unknown\\\",\\\"token\\\":null,\\\"user\\\":{\\\"data\\\":{\\\"name\\\":null,\\\"_id\\\":null},\\\"__serializedType__\\\":\\\"ImmutableMap\\\"}},\\\"__serializedType__\\\":\\\"ImmutableMap\\\"}\"","_persist":"\"{\\\"version\\\":-1,\\\"rehydrated\\\":true}\""}
```

> devtools 裡面 console 、network 的錯誤訊息

Safari
<img width="1280" alt="螢幕快照 2019-05-09 上午10 52 47" src="https://user-images.githubusercontent.com/7566586/57423971-9e445180-7248-11e9-8887-3db330a73901.png">

Firefox
<img width="1280" alt="螢幕快照 2019-05-09 上午10 53 10" src="https://user-images.githubusercontent.com/7566586/57423984-a8fee680-7248-11e9-85e5-81b7d2b941d6.png">

**Comment by mark86092** [comment]
你可以做一次 Header 登入成功的嗎？我看到你給出的 error 是 Network error，很奇怪

**Comment by peteranny** [comment]
![http://g.recordit.co/jCoc2Sqp8V.gif](http://g.recordit.co/jCoc2Sqp8V.gif)

**Comment by WendellLiu** [comment]
https://github.com/goodjoblife/GoodJobShare/blob/dev/src/actions/auth.js#L73

我在local (branch dev)用firefox 也會有類似錯誤，錯誤在這

**Comment by mark86092** [comment]
但是 @peteranny  回報的是 www (master)

@WendellLiu  你的是 dev

**Comment by mark86092** [comment]
找到原因了：

https://github.com/goodjoblife/GoodJobShare/blob/master/src/components/common/PermissionBlock/CallToLoginShareButton.js#L23

```js
window.location.reload();
```

當登入時，`loginWithFB` 會依序完成 FB 登入，換取 token 後，最後把控制權交給 component (L20)

但是，L23 觸發了 reload()，導致有些瀏覽器(我測到 firefox)，**store 沒有及時 sync 至 localStorage**（猜跟 persist 套件有關），於是不會登入完成。

**Comment by mark86092** [comment]
NetworkError 是因為 reload，所以一堆 request 被取消發送
