### ISSUE TITLE
email 驗證信 dialog 沒有自動帶入 email 

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#693]
目前 email 驗證信的 dialog 不會自動帶入 graphql 回傳的 email 
![H93lOhx7rc](https://user-images.githubusercontent.com/3805975/58528231-5d68a880-8208-11e9-8a3c-26737ec94450.gif)

graphql 有回傳
<img width="351" alt="螢幕快照 2019-05-29 上午11 54 38" src="https://user-images.githubusercontent.com/3805975/58528326-ae789c80-8208-11e9-8028-71a6c6064c92.png">

**Comment by mark86092** [comment]
Done
