### ISSUE TITLE
面試經驗表單小修改

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#697]
Zeplin：https://zpl.io/awJLpgn

有修改的地方列表：
<img width="651" alt="螢幕快照 2019-06-02 下午7 02 56" src="https://user-images.githubusercontent.com/3805975/58760396-c08c6f00-8569-11e9-9d9d-6acec16ff9b1.png">
<img width="628" alt="螢幕快照 2019-06-03 下午9 09 29" src="https://user-images.githubusercontent.com/3805975/58808440-a1b2d900-864c-11e9-97a6-8c8acb369d2d.png">
<img width="623" alt="螢幕快照 2019-06-03 下午9 09 45" src="https://user-images.githubusercontent.com/3805975/58808441-a1b2d900-864c-11e9-8e84-b9eddbd87f12.png">

**Comment by barry800414** [comment]
8. 上方 progress bar 不需要可以點
9. 面試過程、中肯建議要加上必填 *

**Comment by barry800414** [comment]
@peteranny  這個 issue ready 了！
詳細的還是看 zeplin 哦！

**Comment by peteranny** [comment]
好，我這週比較忙，下週才會開工

**Comment by peteranny** [comment]
QA把A移掉，那麼API要打`answer:''`嗎
