### ISSUE TITLE
[公司/職稱頁面] Empty State

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/GoodJobShare#735]
1. https://zpl.io/2j51qAW
2. 各分頁可以復用這個元件

**Comment by WendellLiu** [comment]
@peteranny 
我猜你已經在做了，我想應該可以把empty state 獨立出來，所以獨立開一張issue

**Comment by peteranny** [comment]
對，已經在做了，不過還沒移到common
等PR再討論怎麼移到common
