### ISSUE TITLE
Production Google Tag Manager 設定錯誤

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#739]

**Comment by barry800414** [comment]
fixed ，這個只是因為第一個版本的 GTM 沒發布，已修復
<img width="155" alt="螢幕快照 2019-07-07 下午11 22 25" src="https://user-images.githubusercontent.com/3805975/60770520-1aa2c600-a10e-11e9-8b12-67bf877dba99.png">
