### ISSUE TITLE
整合薪資工時與經驗區塊

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/GoodJobShare#756]
主要是我記得做「公司/職稱頁面」這個功能有個目的是要整合薪資工時與經驗區塊，我剛稍微跑了一下流程，發現在我們這個功能上線之後，應該還差一些事情就能做到單純把header 上面的連結做調整（可能很多事情，但我是以最小改動限度來想）。

我想到有幾件要做的事
1. 當然就是要更改header ，合併「薪資工時」與「職場經驗」
2. search bar 目前還是只有搜尋薪資工時資訊，這裡可能需要薪資工時與經驗都搜尋，否則目前狀況是，如果公司僅有經驗，會搜尋不到。
3. https://www.goodjob.life/salary-work-times/latest 的表格可以多個欄位是有幾篇經驗，看要工作與面試分開還是加總都好

我覺得完成這些對於我們把專頁做出來的意義會更高，但當然可能會需要比上面多更多改動就了，看看大家的想法。

@wutingy, @barry800414, @mark86092, @peteranny 可以一起討論這塊

**Comment by peteranny** [comment]
4. https://www.goodjob.life/salary-work-times/latest 的公司/職稱點進去我覺得要default to /overview (目前是/salary-work-times)

**Comment by WendellLiu** [comment]
阿我沒說是因為，我正在做了 ＸＤＤＤ Sorry

**Comment by WendellLiu** [comment]
> 1. https://www.goodjob.life/salary-work-times/latest 的公司/職稱點進去我覺得要default to /overview (目前是/salary-work-times)

ref to #757

**Comment by barry800414** [comment]
@wutingy  @WendellLiu  @peteranny  我可以跟你們約個線上語音，討論嗎？
我整個看過了，覺得超棒，超謝謝你們，我覺得有些部分我當初沒有設計好，可能需要小動 UI

主要想討論的是：
1. header 上面的進入點有哪些、以及點進去之後的樣子
2. 公司、職稱點下去，要到哪邊
3. 首頁或 header 是否要有 search bar

**Comment by barry800414** [comment]
我先截圖，到時候比較好討論

### Header
- 會把薪資、面試、工作心得拆開，未來工作心得會被移除掉，轉成薪資資料，只剩薪資＆面試
- 可能可以有個搜尋 bar ，預設是搜公司或職稱的總覽
- 查薪資點下去，就是到現在的 `/salary-work-times/latest` ，搜尋結果頁也是現在的 `/salary-work-times?q={q}&s_by=company` 
- 查面試 ＆ 查心得，則是把原本的職場經驗列表頁拆開

<img width="807" alt="螢幕快照 2019-08-15 下午11 25 49" src="https://user-images.githubusercontent.com/3805975/63105755-0aef8a80-bfb4-11e9-9a57-fa65dcd04903.png">

### 面試經驗搜尋預設頁面
- 跟現在的職場經驗長得很像，只是沒有左邊面試、工作、實習的 filter
<img width="802" alt="螢幕快照 2019-08-15 下午11 24 43" src="https://user-images.githubusercontent.com/3805975/63105725-fe6b3200-bfb3-11e9-9bc2-55a94b9d7f42.png">

### 面試經驗搜尋結果頁
- 點下去會直接進到公司或職業的面試頁
<img width="805" alt="螢幕快照 2019-08-15 下午11 25 00" src="https://user-images.githubusercontent.com/3805975/63105727-ff03c880-bfb3-11e9-95b9-2916390cbc4f.png">

### 工作心得預設搜尋頁
- 基本上同面試經驗
<img width="803" alt="螢幕快照 2019-08-15 下午11 25 16" src="https://user-images.githubusercontent.com/3805975/63105728-ff03c880-bfb3-11e9-9c85-293a01480eba.png">

### 工作心得搜尋結果頁
- 基本上同面試經驗
<img width="807" alt="螢幕快照 2019-08-15 下午11 25 27" src="https://user-images.githubusercontent.com/3805975/63105729-ff03c880-bfb3-11e9-83c8-e9dd6eeec05d.png">

**Comment by mark86092** [comment]
@barry800414  please add me in, tks
