### ISSUE TITLE
[公司/職稱頁面] Final Review

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/GoodJobShare#759]
https://www-dev.goodjob.life

@mark86092 @barry800414 @peteranny @wutingy 
有空的話再麻煩你們稍微繞繞現狀，沒問題的話，Project 就完成了，然後再安排上到production。

**Comment by peteranny** [comment]
有個問題是經驗的「返回列表」都是回到職場經驗，而非真的上一頁

**Comment by wutingy** [comment]
不知道是不是因為這次改動，首頁的「最新經驗分享」區塊內容不見了
<img width="879" alt="Screen Shot 2019-08-15 at 10 45 20 PM" src="https://user-images.githubusercontent.com/8353239/63102853-746c9a80-bfae-11e9-8df1-a97ebc266c16.png">

**Comment by wutingy** [comment]
@peteranny 我後來有出總覽頁面的 empty state: https://zpl.io/ameRM9r
有空再麻煩調整～

**Comment by wutingy** [comment]
@barry800414 下次見面想問你一下，之後職場經驗是不是也要公司、職稱可以點？
然後我覺得列表有公司名稱但是點進去沒有有點怪（雖然標題預設是公司名稱，但是標題可以改）

**Comment by peteranny** [comment]
> 不知道是不是因為這次改動，首頁的「最新經驗分享」區塊內容不見了

好像是 https://api-dev.goodjob.life/graphql 沙盒API的資料那邊怪怪的，撈不出東西

```
{
  popular_experiences(returnNumber: 3) {
    id
    type
    created_at
    title
    preview
    job_title {
      name
    }
    company {
      name
    }
    like_count
    reply_count
  }
}
```

回傳的是

```
{
  "data": {
    "popular_experiences": []
  }
}
```

**Comment by mark86092** [comment]
> 不知道是不是因為這次改動，首頁的「最新經驗分享」區塊內容不見了

api 的資料是計算一個月內，所以如果沒有測試資料，就會空的 XD

**Comment by WendellLiu** [comment]
@wutingy,
https://www-dev.goodjob.life/job-titles/nonono/overview

@peteranny 改好了。

**Comment by barry800414** [comment]
有一個小小的地方要修改
<img width="374" alt="螢幕快照 2019-08-17 下午5 54 50" src="https://user-images.githubusercontent.com/3805975/63209783-25427900-c118-11e9-851d-7c324d347650.png">

就是擋的區塊是薪資＆估計時薪，而不是估計時薪＆參考時間

---

不過，我覺得不急著馬上改，可以線上語音會議之後再改。
主要是之後薪資工時會有單篇的連結，樣式會長這樣：
<img width="887" alt="螢幕快照 2019-08-17 下午5 57 44" src="https://user-images.githubusercontent.com/3805975/63209830-98e48600-c118-11e9-929e-6f8ef5578e18.png">

這個是後來才加上去的 UI 調整 🙏

**Comment by barry800414** [comment]
@peteranny @WendellLiu  我剛稍微繞了一下

- [ ] 首頁 [Zeplin](https://zpl.io/V1zDny5) 沒有 `現在就留下你的資料` 的那個區塊（三種資料的選擇的區塊），然後區塊的排序有誤。
- [ ] 公司/職業頁面 RWD 版 [zeplin](https://zpl.io/VDdo403) ， @wutingy  有出了。想麻煩你們協助開發。目前只有出手機版的介面，其他螢幕大小的部分，可能要直接排排看，不行再問 @wutingy 。
- [ ] 公司/職業頁面的 Tab （總覽、薪水＆加班狀況.. 那四個按鈕）UI 有修改，介面[在這](https://zpl.io/aRxyRlE)，主要是我認為原本的按鈕，不易知道是按鈕。
- [ ] 為了要讓爬蟲爬到所有頁面，新增兩個頁面，所有公司頁、所有職業頁。 #802 
- [ ] footer 修改

最後兩項是新增的，如果可能的話，也是想再麻煩你們

**Comment by WendellLiu** [comment]
> * [ ]  首頁 [Zeplin](https://zpl.io/V1zDny5) 沒有 `現在就留下你的資料` 的那個區塊（三種資料的選擇的區塊），然後區塊的排序有誤。
> * [ ]  公司/職業頁面 RWD 版 [zeplin](https://zpl.io/VDdo403) ， @wutingy  有出了。想麻煩你們協助開發。目前只有出手機版的介面，其他螢幕大小的部分，可能要直接排排看，不行再問 @wutingy 。

@barry800414 @peteranny 你們還沒做的話，我做一下這兩個

**Comment by barry800414** [comment]
> > * [x]   首頁 [Zeplin](https://zpl.io/V1zDny5) 沒有 `現在就留下你的資料` 的那個區塊（三種資料的選擇的區塊），然後區塊的排序有誤。
> > * [ ]   公司/職業頁面 RWD 版 [zeplin](https://zpl.io/VDdo403) ， @wutingy  有出了。想麻煩你們協助開發。目前只有出手機版的介面，其他螢幕大小的部分，可能要直接排排看，不行再問 @wutingy 。
> 
> @barry800414 @peteranny 你們還沒做的話，我做一下這兩個

我這邊少列了一件事，可以請你一起做嗎？
- [ ] 首頁的 RWD https://zpl.io/2vo9Ey7

其他的部分可以負責沒問題！

**Comment by WendellLiu** [comment]
@barry800414 @wutingy 
https://zpl.io/V1zDny5

這頁的
![image](https://user-images.githubusercontent.com/8898129/70863337-19f64180-1f82-11ea-9b4c-2e1c9f86894c.png)

在沒有hover 作用的環境（也就是mobile），我感覺不太像是按鈕。
這裡我先把原本的排成2x2 ，未來如果要符合現在的樣子，並且解決我說的問題，再修改吧。

**Comment by barry800414** [comment]
> @barry800414 @wutingy
> https://zpl.io/V1zDny5
> 
> 這頁的
> ![image](https://user-images.githubusercontent.com/8898129/70863337-19f64180-1f82-11ea-9b4c-2e1c9f86894c.png)
> 
> 在沒有hover 作用的環境（也就是mobile），我感覺不太像是按鈕。
> 這裡我先把原本的排成2x2 ，未來如果要符合現在的樣子，並且解決我說的問題，再修改吧。

想問，你覺得這樣 style 的按鈕，排成 2x2 ，會更像按鈕嗎？
<img width="685" alt="螢幕快照 2019-12-15 下午10 57 45" src="https://user-images.githubusercontent.com/3805975/70864584-60519d80-1f8e-11ea-87cf-2d58701ca243.png">

我自己是覺得不論桌面或手機，上述的設計，使用者都有機會不知道是按鈕，所以才跟 @wutingy 討論改成這樣
不過確實，在手機上仍然有點不像按鈕

**Comment by barry800414** [comment]
@WendellLiu @wutingy
我剛稍微搜尋了一下手機上通常怎麼做 tab 的

覺得這篇好像可以參考：
https://uxplanet.org/tabs-for-mobile-ux-design-d4cc4d9410d1

![1_AljcbprL9U6Lnuwwh3PObw](https://user-images.githubusercontent.com/3805975/70864651-259c3500-1f8f-11ea-8e3b-dafce2822b94.png)

![1_P2Wv8zxIo0DAukLk3Vr7ZA](https://user-images.githubusercontent.com/3805975/70864644-0ac9c080-1f8f-11ea-90fe-afcbdb37f302.png)
![1_z5yoW88YnJRGLSsJK30w6g](https://user-images.githubusercontent.com/3805975/70864645-0ac9c080-1f8f-11ea-8043-d5a4c5a8de8c.jpeg)

其中最後一個，其實跟 Tin 設計的樣式是類似的。感覺差別只在於它會固定在上方？

**Comment by WendellLiu** [comment]
原本黃色的那個比較像是按鈕一點
所以我現在就先把那個排成2x2

**Comment by wutingy** [comment]
hmmmm 我覺得其實都可以，兩種都是目前常見的，因為手機版本的圖片沒辦法出成跟真的一樣比例，所以看圖會不太準，而且我們的文字本身就比較多，沒有辦法縮到成為一整排，依據整個網站的 giudeline 其實原本黃色的是比較好的，之前有用過。

後來設計有加上 `(2)` 篇數的字樣，是希望可以吸引人去點，再加上如果是 (0) 他就不用費心點進 empty state 了。

**Comment by barry800414** [comment]
這個完成了！ 就先關掉了
Thanks @WendellLiu  @peteranny  @mark86092  @wutingy  for contribution :)
