### ISSUE TITLE
[公司/職稱頁面] 需要有 SSR

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#763]
SSR 的原理是解析 static route，等待 fetchData 後，將更新後的 redux state 跟 react component mount & render，但是由於

https://github.com/goodjoblife/GoodJobShare/blob/master/src/server.js#L52-L65

所以 SSR 的 fetchData 在公司職稱頁是無法運作的 ><"

這個一開始沒有注意到，但有 SSR 對於檢索是有幫助的，所以列出成 TODO

**Comment by barry800414** [comment]
糟糕，這個 issue 我沒有全懂
為什麼 fetchData 在公司職稱頁是無法運作的?

**Comment by mark86092** [comment]
因為 SSR 這邊（L52~L65）會根據 url 去解析 route tree，然後取得 批配中的 route 的 `component`

但是如果看公司職稱頁，以 `/companies/:companyName/overview` 來說
會批配中的 route，是用 render (https://github.com/goodjoblife/GoodJobShare/blob/dev/src/routes.js#L218)
所以 SSR 的機制就無作用

**Comment by mark86092** [comment]
以結果論來說：`view-source:https://www-dev.goodjob.life/job-titles/%E6%9C%83%E8%A8%88%E5%B8%AB/overview`

這個 source 的 html 裡面是沒有 preload 好的資料

**Comment by barry800414** [comment]
我大概理解的問題了
是因為 `CompanyPageProvider` 在 componentDidMount 才拿資料

有找到一些可能相關的討論，先放著 https://github.com/facebook/react/issues/12495 https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#fetching-external-data
