### ISSUE TITLE
黃色Mobile Header

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/GoodJobShare#77]

**Comment by wutingy** [comment]
https://github.com/goodjoblife/WorkTimeSurvey/tree/master/src/css/layout/header

**Comment by wutingy** [comment]
可以把
 `@media (max-width: $below-small) ` 理解為 `@media (max-width: 850)`
 `@media (min-width: $above-small) ` 理解為 `@media (min-width: 851)`
