### ISSUE TITLE
[公司/職稱頁面] 修改搜尋結果頁面

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/GoodJobShare#771]
https://zpl.io/aXXWkgX

1. 更改query string 使用規則，以符合一次搜尋公司與職稱
2. GraphQL SQL 增加一次搜尋公司與職稱
3. search bar 調整
4. result card 調整

**Comment by peteranny** [comment]
Waiting for API (autocomplete)

**Comment by WendellLiu** [comment]
@peteranny 
隨著 #799 結束
我對著這張的說明，應該是結束了？
包括後來說的autocomplete
我也能被推薦到包括職稱與公司了（例如關鍵字為「工程」會有xx工程師也會有xx工程有限公司）

如果沒有意見，就關掉這張吧。

**Comment by peteranny** [comment]
嚴格說起來，還有SSR還沒弄。

**Comment by barry800414** [comment]
這一頁暫時可以不用 SSR 沒關係，除非我們用這個方式讓 google 爬
但目前不是，所以我關票囉！
