### ISSUE TITLE
[公司/職稱頁面] 總覽的資訊圖與總體統計呈現區塊

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/GoodJobShare#773]
https://zpl.io/aRxyRlE

1. 確認API 進度與介面 cc. @barry800414 
2. 長條圖
3. 平均工時、加班狀況
4. 請考慮任一一塊都會在其他地方呈現的情境，please design an appropriate props interface and component hierarchy

**Comment by peteranny** [comment]
@barry800414 

<img width="292" alt="螢幕快照 2019-10-14 上午9 32 48" src="https://user-images.githubusercontent.com/7566586/66725532-a80c5980-ee65-11e9-9d62-28876f81e060.png">

這個區塊的資料要從哪裡拿呢？

**Comment by barry800414** [comment]
> @barry800414
> 
> <img alt="螢幕快照 2019-10-14 上午9 32 48" width="292" src="https://user-images.githubusercontent.com/7566586/66725532-a80c5980-ee65-11e9-9d62-28876f81e060.png">
> 
> 這個區塊的資料要從哪裡拿呢？

平均每週工時的部分，可以從 company, job-title 底下的 salary_work_time_statistics 取得 average_week_work_time 
https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/9cb28ea257a303219854e945c0b1eecace901110/src/schema/salary_work_time.js#L28

加班頻率的統計，我發現目前還沒有，我再補給你～

**Comment by peteranny** [comment]
Waiting for API
https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/635
