### ISSUE TITLE
[首頁改版] 資訊圖表區塊

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/GoodJobShare#775]
https://zpl.io/V1zDny5
1. Carousel 
2. 新增直長條圖
3. 確認API 進度與介面 cc. @barry800414

**Comment by barry800414** [comment]
@peteranny @WendellLiu 

## 公司的薪資圖表
https://jsfiddle.net/barry800414/t7feu6jk/4/

以下是規則，不過前端不用管，後端會負責回傳對的資料：
- 最少兩個職業，最多四個職業
- 單一職業薪資資料 >= 3 筆才顯示


## 職業的薪資圖表
https://jsfiddle.net/barry800414/o1ap7rw3/6/

以下是規則，不過前端不用管，後端會負責回傳對的資料：
- 範圍至少要有兩個分類


## TODO 
- [ ] graphql endpoint （ assign to @barry800414 )

**Comment by peteranny** [comment]
Waiting for API

**Comment by barry800414** [comment]
@peteranny 
API schema：https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/627

請參考：
- `資料前 N 多的公司，不同職業的平均薪資`
- `資料前 N 多的職業的薪資分布` 

這兩個 query 的下法，以及回傳的資料格式
目前是假資料，已經進 dev branch
