### ISSUE TITLE
[首頁改版] Call To Action（分享捷徑）區塊

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/GoodJobShare#777]
https://zpl.io/V1zDny5
1. 分享UI
2. 讓三個分享介面都能吃個query string 已填滿公司、職稱 兩個欄位
3. 連結至填寫頁面並且帶query string （承上）

**Comment by peteranny** [comment]
那麼先在這邊討論一下querystring的key好了，例如可以叫做`companyName`嗎

另外還要討論，如果填了companyName進到表單，碰上儲存的draft，要怎麼解？我想的幾種做法：
1. 以draft優先，不理會companyName
2. 以companyName優先，捨棄draft，改換成空白只有companyName的draft
可能2.會比較合理？怕的是捨棄draft會不會讓使用者的重要數據。

**Comment by WendellLiu** [comment]
以companyName 與jobTitle 優先，草稿次之。原因是，會發生這種情況使用者已經有意識到自己在「新填寫」一個表單，因為捨去草稿也是合理。

**Comment by peteranny** [comment]
This is just about pure components. This can be closed.

CC @WendellLiu
