### ISSUE TITLE
[點數制頁面] UI Design

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#778]
@wutingy  我把點數要畫 UI 的頁面整理好了！

總共五個部分
- 點數說明頁
- 解鎖內容頁
- Header
- 文章類的遮罩說明
- 表格類的遮罩說明

## 點數說明頁
![screencapture-127-0-0-1-32767-start-html-2019-09-15-17_03_07](https://user-images.githubusercontent.com/3805975/64919326-064d0a80-d7dc-11e9-9161-3af48df6a9a9.png)

## 解鎖內容頁
![screencapture-127-0-0-1-32767-start-html-2019-09-15-17_03_49](https://user-images.githubusercontent.com/3805975/64919327-064d0a80-d7dc-11e9-89ca-82f2b1c1e1cf.png)

## Header
<img width="1030" alt="螢幕快照 2019-09-15 下午5 10 12" src="https://user-images.githubusercontent.com/3805975/64919331-0f3ddc00-d7dc-11e9-97c4-bab7a1a2053f.png">

## 文章類的遮罩說明
![screencapture-127-0-0-1-32767-start-html-2019-09-15-17_19_24](https://user-images.githubusercontent.com/3805975/64919427-13b6c480-d7dd-11e9-80cd-56599c24a96f.png)

## 表格類的遮罩說明
![screencapture-127-0-0-1-32767-start-html-2019-09-15-17_09_47](https://user-images.githubusercontent.com/3805975/64919329-06e5a100-d7dc-11e9-8f5f-a2536e0d6165.png)

**Comment by wutingy** [comment]
好XD 你其實可以直接貼網址就好啦

**Comment by barry800414** [comment]
這個改掉了，先關掉
