### ISSUE TITLE
首頁推薦文章顯示問題

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#779]
1. css 要下 word break
2. 後端抓取資料要避免這種亂寫的

<img width="1029" alt="Screen Shot 2019-09-28 at 5 00 25 PM" src="https://user-images.githubusercontent.com/8353239/65814251-d48f6700-e211-11e9-8626-c8d6cc7d92a7.png">

**Comment by barry800414** [comment]
改版後就會修掉，所以關掉
