### ISSUE TITLE
RWD UI Design

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#801]
- [x] 首頁 [zeplin](https://zpl.io/V1zDny5) 的手機版：https://app.zeplin.io/project/5c316d528cc2d146a73dfc59/screen/5df45722401ade498a8dd980
- [ ] 薪資福利表單 [zeplin](https://zpl.io/brvKg8D) 的手機版
- [ ] 面試心得表單 [zeplin](https://zpl.io/awJLpgn) 的手機版

**Comment by wutingy** [comment]
## 補充手機版文字大小的問題（之前韋銘問的）
<img width="248" alt="Screen Shot 2019-12-14 at 11 31 19 AM" src="https://user-images.githubusercontent.com/8353239/70842957-6a2bb180-1e65-11ea-9be2-213c576dbfd8.png">
設計裡的所有文字與標題都會是 component，裡面定義該文字的 line-height, font, mobile font 等等。
Wrapper 也都定義好整個頁面的大小了。
[命名規則](https://app.zeplin.io/project/5c316d528cc2d146a73dfc59/screen/5df45852c1d807ae7b4ef3c7)

**Comment by wutingy** [comment]
如果有發現設計稿跟 guideline 不符合的情況（會發生這種情況就是設一頭暈了，請在 zepline 留言告訴他），就找最接近的 component 使用，勁量不要自己創一個 font-size 的 css 會很難管理。

**Comment by barry800414** [comment]
這個也是先不用了
