### ISSUE TITLE
手機版 圖表 UI

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#810]
<img width="307" alt="螢幕快照 2019-12-20 下午11 47 31" src="https://user-images.githubusercontent.com/3805975/71267212-046b8800-2385-11ea-98fb-cc78e243dd36.png">
<img width="303" alt="螢幕快照 2019-12-20 下午11 47 36" src="https://user-images.githubusercontent.com/3805975/71267214-046b8800-2385-11ea-8fa7-2baf07fcc641.png">

這樣其實無法閱讀，有點棘手

**Comment by mark86092** [comment]
補兩個怪點：

1) 人數的軸應該只需要整數（可能要設定最小 scale = 1）
2) 級距的文字怪怪的：2萬～2萬，雖然可以理解是指 2萬~2萬xxx

2) 的問題可以用直方圖解決（不是長條圖）
