### ISSUE TITLE
工會頁面 UI Design

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#820]
### 放到網站裡面的示意
![screencapture-127-0-0-1-32767-start-html-2019-12-30-17_36_11](https://user-images.githubusercontent.com/3805975/71578565-ad5b7500-2b33-11ea-86a5-f8519e867d6e.png)

**Comment by wutingy** [comment]
收到
需要附上 axure 連結我才能複製文字

**Comment by wutingy** [comment]
https://o2geqq.axshare.com/#id=1nla5w&p=%E5%B7%A5%E6%9C%83%E5%BC%95%E5%B0%8E_block&g=1

**Comment by barry800414** [comment]
no longer needed, close it
