### ISSUE TITLE
換 graphql API

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#840]
把一些 Restful API 換成 graphql API，有些還在 PR 中，要切到指定 branch

- [x] PATCH /workings/:id -> changeSalaryWorkTimeStatus  （已進 master）
- [x] POST /auth/facebook -> facebookLogin （已進 master）
- [x] POST /auth/google -> googleLogin （已進 master）
- [x] GET /jobs/search -> -> job_titles （已進 master）
- [x] POST /replies/:id/likes -> mutation createReplyLike https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/693
- [x] DELETE /replies/:id/likes -> mutation deleteReplyLike https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/693

**Comment by peteranny** [comment]
Resolved
