### ISSUE TITLE
新版表單 UI Design

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#845]
https://o2geqq.axshare.com/#id=41fl3m&p=%E8%A1%A8%E5%96%AE%E6%A1%86%E6%9E%B6&g=1 

Deadline: 2/29

**Comment by wutingy** [comment]
1. 所有必填的題目建議都放在前面，可以送出時才出現送出按鈕
2. 

https://app.zeplin.io/project/5c316d528cc2d146a73dfc59/dashboard?seid=5e5c4f920f4a1b773ab16eb3

**Comment by peteranny** [comment]
有沒有全部完成的頁面呢？

**Comment by barry800414** [comment]
@wutingy comment 我都留在 zeplin 了！

@peteranny  我有補成功的 modal 範例，請 @wutingy 畫或用現成的了

**Comment by peteranny** [comment]
Since the design is done, close the issue

**Comment by peteranny** [comment]
Since the design is done, close the issue
