### ISSUE TITLE
Footer 加上 g0v grant logo

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#86]
這個是領g0v grant必須要做的事情，在網站可見的地方加上 powered by g0v 的字樣，並且連回獎助金頁面。

* powered by g0v 圖檔： https://grants.g0v.tw/power/  最下方有好幾種，挑一個即可
* 要連過去的連結： https://councils.g0v.tw/

範例：[議員投票指南](https://councils.g0v.tw/)

**Comment by mark86092** [comment]
有亂碼

**Comment by barry800414** [comment]
我就正常打字他就有亂碼捏，有解嗎

**Comment by mark86092** [comment]
就刪掉就好了？

**Comment by barry800414** [comment]
![2017-05-09 11 33 22](https://cloud.githubusercontent.com/assets/3805975/25834562/61d63326-34ab-11e7-9545-8b629a7240eb.png)

能刪掉我早就刪掉了齁

**Comment by mark86092** [comment]
我刪掉了耶XD

**Comment by mark86092** [comment]
幸好圖片有 https

**Comment by barry800414** [comment]
g0v的人有小催一下這件事，如果人力上允許，看能不能跟著小教室一起上線。不行的話也沒關係。

**Comment by mark86092** [comment]
舊網站需要放上  powered by g0v 的字樣 嗎？

現在要上線的網站首頁是由舊網站提供的

**Comment by barry800414** [comment]
我的理解是受g0v贊助這段時間的產出都要放，要放至少一年。
所以應該是要。

**Comment by wutingy** [comment]
ok 我週末可以用

**Comment by mark86092** [comment]
這邊要補上 g0v grant 的 footer

**Comment by mark86092** [comment]
Done
