### ISSUE TITLE
新版表單 RWD UI Design

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#870]
比想像中的再難一點，以下自己試玩的半成品 XD，請 @wutingy  幫忙了

<img width="803" alt="截圖 2020-03-26 上午9 05 19" src="https://user-images.githubusercontent.com/3805975/77600174-032c9700-6f42-11ea-89ea-406fdbe49047.png">

預期時程：3/29

**Comment by wutingy** [comment]
https://zpl.io/2pA5zZJ
@barry800414 傳上去囉

**Comment by barry800414** [comment]
@wutingy  因為 zeplin 上無法留圖片，我 comment 在這邊

1. 我想問題目可以讓它置中嗎？  我認為這樣可以容易專注在問題上面

範例：
<img width="732" alt="截圖 2020-03-29 下午7 15 04" src="https://user-images.githubusercontent.com/3805975/77847724-dc948780-71f1-11ea-833b-8bb3495de0e5.png">

2. 每一個問題的本身的 title & description 的字體，可以放大嗎？  主要是讓要填寫的題目，成為視覺上的焦點。認為題目的 title，甚至可以比 header 區的字體大。

3. 最上方資訊將受永久匿名保護，顏色可能要深一點，或者字體要稍大。在相對大螢幕的情況下，會看不太清楚
<img width="623" alt="截圖 2020-03-29 下午7 20 51" src="https://user-images.githubusercontent.com/3805975/77847862-bfac8400-71f2-11ea-8d42-521089ff57ba.png">


4. 最下方「完成解鎖全站ＯＯ筆資料ＸＸ小時」，也認為區塊要稍大、文字稍大一些，因為這是給予使用者的最大動機
<img width="621" alt="截圖 2020-03-29 下午7 21 16" src="https://user-images.githubusercontent.com/3805975/77847860-bc18fd00-71f2-11ea-864c-f8e2a43361f0.png">

#### 如果要排這個頁面視覺重要性：
我認為會是：`問題 title＆ description ＆ 填答的 input 或選項空間` > `最下方獎勵區` = ` 送出按鈕` > `header 的標題` = `資訊受永久匿名保護`

**Comment by barry800414** [comment]
Done
