### ISSUE TITLE
Google Analytics 埋設

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#89]
需要埋事件點，先暫時分成幾大部分

1. GA script 的引用
2. router 觸發 GA 的相關事件
3. 其它客製事件

**Comment by wutingy** [comment]
參考這個 package：
https://github.com/react-ga/react-ga
Initializing GA and Tracking Pageviews with react-router

**Comment by mark86092** [comment]
是的！想要用這個埋設

**Comment by barry800414** [comment]
這邊整理要埋ＧＡ的地方

- [x] 每一頁的 pageview

Header：
- [ ] click goodjob logo
- [ ] click 薪資工時
- [ ] click 面試、工作經驗
- [ ] click 勞動小教室
- [ ] click 留下資料

Footer：
- [ ] click 使用者條款
- [ ] click 隱私權政策
- [ ] click powered by g0v
- [ ] click github page
- [ ] click facebook fan page

首頁：
- [ ] click 立即參與的按鈕
- [ ] click 任一篇熱門分享 
- [ ] click 留下工時或薪資
- [ ] click 分享面試經驗
- [ ] click 分享工作經驗

勞動小教室頁： `/labor-rights/:id` 
- [ ] click上一篇
- [ ] click下一篇
- [ ] click返回列表

分享選項頁： `/share`
- [ ] click 留下工時或薪資
- [ ] click 分享面試經驗
- [ ] click 分享工作經驗
- [ ] click 右上角 x 

面試經驗填寫頁： `/share/interview`
- [ ] 對表單做第一個操作 (e.g. focus input, 按按鈕, 拉開選單）開始計時，到成功送出為止，花的時間。
- [ ] click section 的 ＋ 按鈕
- [ ] QA的 ＋ 按鈕

工作經驗填寫頁： `/share/work-experience`
- [ ] 對表單做第一個操作 (e.g. focus input, 按按鈕, 拉開選單）開始計時，到成功送出為止，花的時間。
- [ ] click section 的 ＋ 按鈕

面試及工作經驗查詢頁： `/experiences/search` 
- [ ] click 最新
- [ ] click 熱門
- [ ] toggle on/off 面試經驗
- [ ] toggle on/off 工作經驗
- [ ] 搜尋時，紀錄以 "公司" / "職稱" 搜尋，以及關鍵字內容
- [ ] 向下捲動讀取新的面試經驗時觸發事件

單篇經驗顯示頁： `/experiences/:id`
- [ ] 點文章讚 
- [ ] 取消文章讚

登入狀態：
- [ ] FB登入成功
- [ ] FB登入失敗


Ｑ：有沒有辦法記錄使用者一個session內，看了幾篇文章？

**Comment by mark86092** [comment]
有的單純只是 link 的，我沒看懂為什麼要 trace，router change 就會有了

要注意 ga 的 quota 喔

**Comment by barry800414** [comment]
重新整理一下要埋的地方：
這邊整理要埋ＧＡ的地方

- [x] 每一頁的 pageview

### 面試經驗填寫頁： `/share/interview`  category: `SHARE_INTERVIEW`
- [ ] `enter_page`：一進到 `/share/interview` 頁面，就發送事件
- [ ] `start_writing`：對表單做第一個操作 (e.g. focus input, 按按鈕, 拉開選單）後，就發送事件（只發送一次）
- [ ] `end_writing`：成功上傳面試經驗分享後，發送事件

* 為什麼要發送以上三個事件？
打開這個分類後，就可以快速的知道 `進來這一頁`, `開始嘗試填寫`, `成功填寫完成` 的比例

### 工作經驗填寫頁： `/share/work-experience`  category: `SHARE_WORK`
- [ ] `enter_page`：一進到 `/share/work-experience` 頁面，就發送事件
- [ ] `start_writing`：對表單做第一個操作 (e.g. focus input, 按按鈕, 拉開選單）後，就發送事件（只發送一次）
- [ ] `end_writing`：成功上傳工作經驗分享後，發送事件

* 為什麼要發送以上三個事件？   同上

### 填寫時間長短： `/share/interview` & `/share/work-experience`  category: `FORM_TIME`
- [ ] 對表單做第一個操作 (e.g. focus input, 按按鈕, 拉開選單）後，開始計時，到成功上傳面試經驗分享為止的時間。 （這個會用ga timing )

目的主要是記錄使用者從開始寫到填寫完所花的時間。

### 面試及工作經驗查詢頁： `/experiences/search`   category: `EXPERIENCE_SEARCH`
- [ ] click 最新 / click 熱門
- [ ] toggle on/off 面試經驗
- [ ] toggle on/off 工作經驗
- [ ] 搜尋時，紀錄以 "公司" / "職稱" 搜尋，以及關鍵字內容
- [ ] 向下捲動讀取新的面試經驗時觸發事件

以上事件的目的是瞭解使用者的查詢行為，作為之後優化的依據。

### 登入行為：  category: `LOGIN`
- [ ] `ask_to_login`：跳出 FB login 視窗，即發送事件
- [ ] `reject_to_login`：使用者不願意登入FB 或 不願意授權  （這個不一定能做）
- [ ] `login_fail`：FB 登入失敗，不管原因是什麼
- [ ] `login_success`：FB登入成功

這個分類的目標是了解使用者拒絕登入的比例有多高。
有些項目還要確定可行性，不一定能做。

舊站reference issue: 
https://github.com/goodjoblife/WorkTimeSurvey/issues/455
https://github.com/goodjoblife/WorkTimeSurvey/issues/279

@mark86092  @wutingy

**Comment by wutingy** [comment]
上面的我沒問題～
補充一個：
### Header 行為：`HEADER`
- [ ] `time_salary` 薪資工時
- [ ]  `experience` 面試 / 工作經驗
- [ ] `labor_rights` 勞動小教室
- [ ] `share` 留下資料

目的：提供 UI 設計參考用，看設計上是否清楚明瞭，並且看「留下資料」按鈕在上方是否有發揮其作用。

**Comment by mark86092** [comment]
LGTM
