### ISSUE TITLE
一頁一題式表單 tickets

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#892]
盤點一下現在還沒完成的部分
- [x] 面試經驗表單按下 submit 後要打 API 
- [x] 完成FormBuilder 的 RWD design ，詳見：[zeplin](https://app.zeplin.io/project/5c316d528cc2d146a73dfc59/dashboard?seid=5e68ef9e17354312222e1192)
- [x] 職場經驗單篇、薪資工時頁面，阻擋的區塊要加上新的 Interview Form Modal 
- [x] A/B testing ，A 版本是原本三頁式的表單，B 版本是一頁一題式的表單 @barry800414 

最後一個我可處理，上述其他的，會想請 @peteranny  幫忙
會先把面試經驗表單整個成功換上去，做實驗。再做其他表單！

**Comment by peteranny** [comment]
@barry800414 想問一下，這個表單需要有cache的功能嗎？原本表單有

**Comment by peteranny** [comment]
剩下A/B testing要麻煩 @barry800414

**Comment by barry800414** [comment]
ok ，等 #905  merge

**Comment by barry800414** [comment]
@peteranny 你還有想到其他地方要改的嗎？
我今天會再測一次

**Comment by peteranny** [comment]
改完了！

**Comment by barry800414** [comment]
謝謝你～～～
今天我會再手動測一次，沒問題的話就讓它上去跑 A/B testing 了
文章字數的實驗會先 close
