### ISSUE TITLE
手機螢幕大小的表單樣式調整

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#912]
#### 1. 表單上下有 10px 的空隙要去掉，外圍陰影部分也要去掉，只留中間 header 的陰影
<img width="742" alt="截圖 2020-05-31 下午10 24 46" src="https://user-images.githubusercontent.com/3805975/83354799-a4dec300-a38d-11ea-999e-89b6c97f8daa.png">

#### 2. 手機版本的表單，最下方黃色區塊高度不夠
應該要高 35px
 
#### 3. 手機螢幕更小的時候，會跑版
iphone 5 的時候會長這樣
<img width="354" alt="截圖 2020-05-31 下午10 14 03" src="https://user-images.githubusercontent.com/3805975/83354570-20d80b80-a38c-11ea-9740-6a9e231e721d.png">

iphone 6/7/8 Plus 會長這樣
<img width="403" alt="截圖 2020-05-31 下午10 14 10" src="https://user-images.githubusercontent.com/3805975/83354572-233a6580-a38c-11ea-9365-ec4402cf1734.png">

目前的想法是建議 550px 以下的情況，就 max-width: 360px ，讓寬度可以隨著螢幕縮小

**Comment by peteranny** [comment]
> 1. 表單上下有 10px 的空隙

想問一下如果上下沒空隙，那麼陰影就會變成只有左右，這樣會不會看起來怪怪的？

**Comment by barry800414** [comment]
如果是根據 [zepline](https://zpl.io/awDvGrD) 上面畫的，陰影看起來是只有 header 才有
左右兩邊看起來不會有陰影～

**Comment by peteranny** [comment]
不過我們實作用的是現有的Modal，這樣變成要刻意去掉陰影qq
