### ISSUE TITLE
私訊原作者按鈕移除

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#917]
暫時還不會實作，先移除

<img width="1792" alt="Screen Shot 2020-06-16 at 9 45 57 AM" src="https://user-images.githubusercontent.com/7566586/84722619-4aad4700-afb6-11ea-9530-bf37a80d3909.png">

**Comment by peteranny** [comment]
應該只要關掉實驗就沒有按鈕了吧？

**Comment by barry800414** [comment]
沒有，我的實驗是改字而已
按鈕是預設在的

**Comment by peteranny** [comment]
那我先問問 @elsawaston1316 能不能做這個
