### ISSUE TITLE
職場經驗單篇優化 UI Design

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#918]
- [ ] 麵包屑
- [ ] 可以點擊的連結
- [ ] 下方相關的文章區
- [ ] 下方相關薪資、工時區
- [ ] 下方相關工會區

**Comment by peteranny** [comment]
設計出來之後由 @elsawaston1316 實作

**Comment by wutingy** [comment]
ok, 預計 6/28 之前可以完成設計

**Comment by wutingy** [comment]
-  麵包屑
-  新增可以點擊的連結：公司、職稱
-  相關的文章區
-  相關薪資、工時區
-  相關工會區
https://zpl.io/aRJr9oz

**Comment by wutingy** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<svg width="201px" height="109px" viewBox="0 0 201 109" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
        <polygon id="path-1" points="0 1.0003 200.339 1.0003 200.339 108.297 0 108.297"></polygon>
    </defs>
    <g id="/experience/:id" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g transform="translate(-537.000000, -2332.000000)">
            <g id="Group-14" transform="translate(537.000000, 2332.000000)">
                <path d="M139.195,77.7255 L136.83,77.7255 C136.689,77.7365 136.545,77.7485 136.401,77.7485 L119.17,77.7485 C116.387,77.7485 114.11,75.4715 114.11,72.6895 C114.11,69.9085 116.387,67.6315 119.17,67.6315 L117.167,67.6315 C114.074,67.6315 111.543,65.1005 111.543,62.0085 C111.543,58.9165 114.074,56.3835 117.167,56.3835 L115.779,56.3835 C112.687,56.3835 110.155,53.8535 110.155,50.7625 L110.155,50.7605 C110.155,47.6685 112.687,45.1375 115.779,45.1375 L117.63,45.1375 C114.536,45.1375 112.006,42.6055 112.006,39.5145 C112.006,36.4205 114.536,33.8895 117.63,33.8895 L126.01,33.8895 C126.895,32.9225 128.161,32.3105 129.567,32.3105 C129.721,32.3105 129.872,32.3205 130.021,32.3325 L138.548,32.3325 C138.837,32.3185 139.129,32.3105 139.421,32.3105 C145.362,32.3105 150.676,34.9905 154.228,39.2035 L180.383,39.2035 L191.806,11.7545 C192.255,10.3205 192.335,9.5605 192.335,9.1975 C192.054,9.1175 191.516,9.0165 190.583,9.0165 L52.535,9.0165 C48.089,9.0165 45.635,9.5215 44.554,12.2875 L44.522,12.3715 L33.354,39.2035 L46.319,39.2035 C49.871,34.9905 55.184,32.3105 61.127,32.3105 C61.418,32.3105 61.71,32.3185 61.998,32.3325 L70.526,32.3325 C70.675,32.3205 70.826,32.3105 70.98,32.3105 C72.386,32.3105 73.652,32.9225 74.537,33.8895 L82.917,33.8895 C86.011,33.8895 88.541,36.4205 88.541,39.5145 C88.541,42.6055 86.011,45.1375 82.917,45.1375 L84.767,45.1375 C87.86,45.1375 90.39,47.6685 90.39,50.7605 L90.39,50.7625 C90.39,53.8535 87.86,56.3835 84.767,56.3835 L83.38,56.3835 C86.473,56.3835 89.003,58.9165 89.003,62.0085 C89.003,65.1005 86.473,67.6315 83.38,67.6315 L81.377,67.6315 C84.16,67.6315 86.436,69.9085 86.436,72.6895 C86.436,75.4715 84.16,77.7485 81.377,77.7485 L64.146,77.7485 C64.002,77.7485 63.859,77.7365 63.716,77.7255 L61.351,77.7255 C61.062,77.7405 60.772,77.7485 60.479,77.7485 C54.537,77.7485 49.223,75.0685 45.672,70.8535 L20.18,70.8535 L8.714,98.4065 C8.377,99.2215 8.2,99.8145 8.109,100.2255 C8.761,100.2835 9.63,100.2835 10.231,100.2835 L142.942,100.2835 C153.089,100.2835 154.786,97.7195 157.6,93.4735 C157.772,93.2115 157.947,92.9495 158.124,92.6845 L167.21,70.8535 L154.875,70.8535 C151.324,75.0685 146.009,77.7485 140.068,77.7485 C139.776,77.7485 139.485,77.7405 139.195,77.7255 Z" id="Fill-1" fill="#FCD406"></path>
                <path d="M152.5103,60.3794 C147.2123,60.3794 142.4483,58.1044 139.1383,54.4774 C136.8083,51.9264 135.2013,48.7054 134.6323,45.1374 C134.5593,44.6824 134.4993,44.2234 134.4613,43.7564 L134.3943,43.7564 L134.3943,45.1374 L134.3943,53.1624 C134.3943,54.3994 133.9183,55.5274 133.1473,56.3834 L134.9343,56.3834 L136.3223,56.3834 C139.4143,56.3834 141.9443,58.9164 141.9443,62.0084 C141.9443,65.1004 139.4143,67.6314 136.3223,67.6314 L136.4003,67.6314 C139.1823,67.6314 141.4593,69.9084 141.4593,72.6904 C141.4593,75.3264 139.4133,77.5064 136.8303,77.7254 L139.1953,77.7254 C139.4853,77.7404 139.7753,77.7484 140.0683,77.7484 C146.0093,77.7484 151.3233,75.0684 154.8753,70.8544 C157.3893,67.8714 159.0163,64.1174 159.3553,60.0004 C157.5343,60.2744 153.8733,60.3794 152.5103,60.3794" id="Fill-3" fill="#000000"></path>
                <path d="M124.7398,37.1372 C124.7398,35.8892 125.2248,34.7502 126.0098,33.8892 L117.6298,33.8892 C114.5358,33.8892 112.0058,36.4202 112.0058,39.5142 C112.0058,42.6062 114.5358,45.1372 117.6298,45.1372 L115.7798,45.1372 C112.6868,45.1372 110.1558,47.6682 110.1558,50.7602 L110.1558,50.7622 C110.1558,53.8542 112.6868,56.3832 115.7798,56.3832 L117.1668,56.3832 L125.9868,56.3832 C125.2158,55.5282 124.7398,54.3992 124.7398,53.1622 L124.7398,45.1372 L124.7398,37.1372 Z" id="Fill-5" fill="#000000"></path>
                <path d="M84.7672,45.1372 L82.9172,45.1372 C86.0112,45.1372 88.5412,42.6062 88.5412,39.5142 C88.5412,36.4202 86.0112,33.8892 82.9172,33.8892 L74.5372,33.8892 C75.3222,34.7502 75.8062,35.8892 75.8062,37.1372 L75.8062,45.1372 L75.8062,53.1622 C75.8062,54.3992 75.3312,55.5282 74.5592,56.3832 L83.3802,56.3832 L84.7672,56.3832 C87.8592,56.3832 90.3902,53.8542 90.3902,50.7622 L90.3902,50.7602 C90.3902,47.6682 87.8592,45.1372 84.7672,45.1372" id="Fill-7" fill="#000000"></path>
                <path d="M66.1519,45.1372 L66.1519,43.7562 L66.0859,43.7562 C66.0479,44.2232 65.9869,44.6822 65.9149,45.1372 C65.3449,48.7052 63.7379,51.9262 61.4079,54.4772 C58.0969,58.1042 53.3349,60.3792 48.0369,60.3792 C46.6729,60.3792 43.0129,60.2742 41.1909,60.0002 C41.5309,64.1172 43.1569,67.8712 45.6719,70.8542 C49.2229,75.0692 54.5369,77.7482 60.4789,77.7482 C60.7719,77.7482 61.0619,77.7412 61.3509,77.7252 L63.7159,77.7252 C61.1329,77.5062 59.0879,75.3262 59.0879,72.6902 C59.0879,69.9082 61.3639,67.6312 64.1459,67.6312 L64.2249,67.6312 C61.1319,67.6312 58.6019,65.1002 58.6019,62.0082 C58.6019,58.9162 61.1319,56.3832 64.2249,56.3832 L65.6119,56.3832 L67.3999,56.3832 C66.6279,55.5282 66.1519,54.3992 66.1519,53.1622 L66.1519,45.1372 Z" id="Fill-9" fill="#000000"></path>
                <mask id="mask-2" fill="white">
                    <use xlink:href="#path-1"></use>
                </mask>
                <g id="Clip-12"></g>
                <path d="M125.9864,56.3833 L117.1674,56.3833 C114.0734,56.3833 111.5434,58.9163 111.5434,62.0083 C111.5434,65.1003 114.0734,67.6313 117.1674,67.6313 L119.1704,67.6313 C116.3874,67.6313 114.1104,69.9083 114.1104,72.6903 C114.1104,75.4713 116.3874,77.7483 119.1704,77.7483 L136.4004,77.7483 C136.5454,77.7483 136.6884,77.7373 136.8304,77.7253 C139.4134,77.5063 141.4594,75.3263 141.4594,72.6903 C141.4594,69.9083 139.1824,67.6313 136.4004,67.6313 L136.3214,67.6313 C139.4144,67.6313 141.9444,65.1003 141.9444,62.0083 C141.9444,58.9163 139.4144,56.3833 136.3214,56.3833 L134.9344,56.3833 L133.1474,56.3833 C133.9184,55.5283 134.3944,54.3993 134.3944,53.1623 L134.3944,45.1373 L134.3944,43.7563 L134.4614,43.7563 C134.4994,44.2233 134.5594,44.6823 134.6324,45.1373 C135.2014,48.7053 136.8084,51.9263 139.1384,54.4773 C142.4484,58.1043 147.2124,60.3793 152.5104,60.3793 C153.8734,60.3793 157.5344,60.2743 159.3554,60.0003 C159.0164,64.1173 157.3894,67.8713 154.8754,70.8543 L167.2094,70.8543 L158.1244,92.6843 C157.9464,92.9493 157.7724,93.2113 157.6004,93.4733 C154.7864,97.7193 153.0884,100.2833 142.9424,100.2833 L17.1214,100.2833 C8.1094,100.2833 11.5914,91.4923 11.5914,91.4923 L20.1804,70.8543 L45.6724,70.8543 C43.1574,67.8713 41.5304,64.1173 41.1914,60.0003 C43.0124,60.2743 46.6734,60.3793 48.0364,60.3793 C53.3344,60.3793 58.0974,58.1043 61.4084,54.4773 C63.7384,51.9263 65.3454,48.7053 65.9144,45.1373 C65.9874,44.6823 66.0474,44.2233 66.0854,43.7563 L66.1524,43.7563 L66.1524,45.1373 L66.1524,53.1623 C66.1524,54.3993 66.6274,55.5283 67.3994,56.3833 L65.6114,56.3833 L64.2254,56.3833 C61.1324,56.3833 58.6014,58.9163 58.6014,62.0083 C58.6014,65.1003 61.1324,67.6313 64.2254,67.6313 L64.1464,67.6313 C61.3644,67.6313 59.0874,69.9083 59.0874,72.6903 C59.0874,75.3263 61.1334,77.5063 63.7164,77.7253 C63.8584,77.7373 64.0014,77.7483 64.1464,77.7483 L81.3774,77.7483 C84.1594,77.7483 86.4354,75.4713 86.4354,72.6903 C86.4354,69.9083 84.1594,67.6313 81.3774,67.6313 L83.3804,67.6313 C86.4734,67.6313 89.0034,65.1003 89.0034,62.0083 C89.0034,58.9163 86.4734,56.3833 83.3804,56.3833 L74.5594,56.3833 C75.3314,55.5283 75.8064,54.3993 75.8064,53.1623 L75.8064,45.1373 L75.8064,37.1373 C75.8064,35.8893 75.3214,34.7503 74.5374,33.8893 C73.6524,32.9223 72.3864,32.3113 70.9794,32.3113 C70.8264,32.3113 70.6754,32.3213 70.5254,32.3323 L61.9984,32.3323 C61.7094,32.3193 61.4184,32.3113 61.1264,32.3113 C55.1834,32.3113 49.8704,34.9903 46.3194,39.2033 L33.3544,39.2033 L44.5224,12.3713 L44.5544,12.2873 C45.6344,9.5223 48.0894,9.0163 52.5354,9.0163 L185.6624,9.0163 C193.1994,9.0163 189.4524,17.4103 189.4524,17.4103 L180.3824,39.2033 L154.2274,39.2033 C150.6764,34.9903 145.3624,32.3113 139.4204,32.3113 C139.1284,32.3113 138.8374,32.3193 138.5484,32.3323 L130.0214,32.3323 C129.8714,32.3213 129.7204,32.3113 129.5674,32.3113 C128.1604,32.3113 126.8944,32.9223 126.0094,33.8893 C125.2254,34.7503 124.7394,35.8893 124.7394,37.1373 L124.7394,45.1373 L124.7394,53.1623 C124.7394,54.3993 125.2154,55.5283 125.9864,56.3833 M198.8884,4.3933 C197.2454,2.1413 194.4504,1.0003 190.5834,1.0003 L52.5354,1.0003 C48.8974,1.0003 40.3874,1.0003 37.1054,9.3283 L1.3094,95.3363 C0.6864,96.8443 -1.2106,101.4383 1.1574,104.9793 C3.3794,108.2973 7.5024,108.2973 10.2304,108.2973 L142.9424,108.2973 C157.3934,108.2973 161.0534,102.7743 164.2824,97.8993 C164.5134,97.5513 164.7474,97.1993 164.9874,96.8443 L165.2154,96.5083 L199.2744,14.6743 L199.3914,14.3563 C200.2764,11.5883 201.1884,7.5453 198.8884,4.3933" id="Fill-11" fill="#4D4D4D" mask="url(#mask-2)"></path>
            </g>
        </g>
    </g>
</svg>`

**Comment by wutingy** [comment]
(工會的 icon  svg)

**Comment by peteranny** [comment]
TODO 只剩下工會的部分還沒做

**Comment by barry800414** [comment]
@peteranny 工會的功能，暫時還不會有，如果確定有，我再另外開 issue
