### ISSUE TITLE
工會頁面時程

### ISSUE THREAD

**Issue by YongChenSu** [goodjoblife/GoodJobShare#920]
#### 109.07.23
carousell 完成

## 其他問題
若方便的話想麻煩稍微講解一下，若沒空的話，我也可自己先摸索。
1. 馬上加入的按鈕，該導引到哪個頁面？
2. 在聯絡我們的 block，關於留下資料的欄位，我應該怎麼存資料？還有把資料存到哪裡？
3. 若還沒有要做上述兩點，還有哪個頁面我可以先做？

**Comment by barry800414** [comment]
> 1. 馬上加入的按鈕，該導引到哪個頁面？

先留著空白即可

> 2. 在聯絡我們的 block，關於留下資料的欄位，我應該怎麼存資料？還有把資料存到哪裡？

那邊我移除了，覺得不會有人用，沒有必要做

> 3. 若還沒有要做上述兩點，還有哪個頁面我可以先做？

這一頁對你來說最挑戰的會是 carousell 照片輪播的部分，想麻煩你做完，用套件或自己做都可（建議自己做，可練功）
然後整個頁面的資料，你試著把它整理起來，變成一個物件，獨立成一個檔案

其他頁面的部分，我們約個線上語音！

**Comment by barry800414** [comment]
no longer needed, close it
