### ISSUE TITLE
研究 newsletter 服務

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#93]
目前傾向用 https://mailchimp.com/ 搜集使用者資訊，會設計一個類似下圖的區塊：

![screen shot 2017-05-11 at 21 44 54](https://cloud.githubusercontent.com/assets/8353239/25954088/cd13c386-3697-11e7-8648-45b876db40ee.png)

研究一下是否要錢？怎麼收費？有沒有免費但是跟 mailchimp 一樣好用的？

需要功能：
- 將之前蒐集到到 mail list 匯入
- 系統發做好的 email template 發送
- 可以讓使用者 unsubscribe 功能

**Comment by wutingy** [comment]
@peteranny：
@barry800414 有提到想要搜集 email 發送消息給使用者，
這部分交給你研究，有問題、有結論可以在這邊討論。

cc @mark86092

**Comment by barry800414** [comment]
如果能有以下功能更好：
- [ ] 讓使用者可以 subscribe 的 widget （前端就只需要把code嵌進去），目前我看mailchimp是有這個功能

**Comment by mark86092** [comment]
我就技術上的來說，應用上 Tin & weiming 已經補充

* 發信方的 email 地址是什麼
* 使用者如果回信會到哪個 email （寄信跟回郵可以不同地址，比較細節，這行較不重要）

**Comment by peteranny** [comment]
https://docs.google.com/presentation/d/1ZvSXWM9Gd1IS8LB42pprR4wIHSc4PT8tCdttkFPgzWo/edit?usp=sharing

結論：MailChimp很好上手

**Comment by barry800414** [comment]
讚讚讚
不過可以麻煩 @peteranny 幫忙看看定價的部分嗎？
免費版的限制、不同價格方案的內容

如果官方有淺顯易懂的頁面，直接貼上來即可

**Comment by peteranny** [comment]
免費版的說明（重點：免費版最多寄12000封信）
http://kb.mailchimp.com/accounts/billing/about-the-forever-free-plan?_ga=2.51189161.1692503367.1495119552-29405208.1494546518

免費版和付費版的服務差異
https://mailchimp.com/features/all/?_ga=2.187753256.1605706980.1495119874-29405208.1494546518#paid

付費版的價格
https://mailchimp.com/pricing/all/?_ga=2.4302321.374542397.1495119938-29405208.1494546518

**Comment by barry800414** [comment]
補個免費版的限制： up to 2,000 subscriber,  12,000 mails per month

**Comment by mark86092** [comment]
而且還蠻貴的

**Comment by barry800414** [comment]
這個價格真的是有點過高...
如果有到5000人留下email，每個月就要50美金了
以目前的需求來說，只是單純要提早蒐集email名單，讓我們的行銷可以傳遞訊息給使用者，如小教室、網站功能發布。一年下來可能沒幾封信，覺得這樣成本太高。

未來才有可能做transactional email (個人化、以API自動發送），但MailChimp價格還是太高，應該考慮AWS SES或MailGun。

**Comment by barry800414** [comment]
這樣子，組長群會議會再討論。有詳細的需求再說明。

**Comment by mark86092** [comment]
不如組長會議前先了解行銷對於 email 宣傳的作法與評估，我們這邊再給幾個方向

**Comment by mark86092** [comment]
完成
