### ISSUE TITLE
Header 小教室 的 New badge 有小問題

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/GoodJobShare#94]
![image](https://cloud.githubusercontent.com/assets/1908007/25956794/4591581c-369f-11e7-9f64-e46be6384f66.png)

NEW badge 是一個方形的 svg，會覆蓋底下的 a 連結

不確定要怎麼修正 svg 的 style，所以先丟 issue 出來

**Comment by wutingy** [comment]
收到～應該是要把 svg 包到 a 裡面，週日會來修這個

**Comment by mark86092** [comment]
感謝
