### ISSUE TITLE
更多和ＯＯＯ公司、ＸＸＸ的面試及工作心得... 區塊要做 SSR

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#952]

**Comment by peteranny** [comment]
想問一下，更多經驗的SSR目的是什麼呢？理論上有麵包屑應該就可以爬到全站，更多經驗的部分感覺可以動態載入沒關係？
如果要SSR的話，要等拉到目前的經驗知道公司和職稱之後，才能打更多經驗的API，這樣latency會變高一點

**Comment by barry800414** [comment]
因為 google 在決定搜尋結果排序的時候，會看那頁的「內容」與「標題」的相關性
讓該頁面充滿與標題相關的內容，排名就有機會往上排
所以才會希望做 SSR，讓 google 抓得到

**Comment by peteranny** [comment]
但放相關經驗感覺不太一定符合這個需求欸？
因為一次也只會render五個，內容也非本頁的內容，只是要增加關鍵字數量的話用相關文章也沒有保證一定加到什麼，因為相關文章是動態的

是可以做啦，但我不太同意就是了
想問問 @mark86092 意見

**Comment by mark86092** [comment]
做 SSR 的確蠻吃的，如果想要放公司/職稱相關的經驗（為了 SEO，這個未實驗我也無法確定成效），那或許可以考慮做比較輕量的 api，例如 從公司找相關經驗 可以加上 limit

**Comment by barry800414** [comment]
@peteranny 

> 但放相關經驗感覺不太一定符合這個需求欸？

為什麼會這麼覺得呢～？
我舉實例就是這個內容農場：https://kknews.cc/zh-tw/fashion/xgbev8.html 一篇文章下面會有大量相關文章

> 因為一次也只會render五個，內容也非本頁的內容，只是要增加關鍵字數量的話用相關文章也沒有保證一定加到什麼，因為相關文章是動態的

五個確實可能不夠，但目的不是要增加關鍵字數量，而是與ＯＯ公司、ＸＸ職位相關的內容。
動態的沒差。

**Comment by barry800414** [comment]
@mark86092 

> 做 SSR 的確蠻吃的，如果想要放公司/職稱相關的經驗（為了 SEO，這個未實驗我也無法確定成效），那或許可以考慮做比較輕量的 api，例如 從公司找相關經驗 可以加上 limit

SEO 很難做 A/B testing 測試，比較簡單的做法是放上去隔一段時間看有沒有成長

**Comment by barry800414** [comment]
然後打完一個再打一個，確實會影響 latency，可能要直接做一個後端 Api ，傳 experience id 給相關內容
這個 issue 先 pending 吧！

**Comment by mark86092** [comment]
Graphql 是可以一起打：https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/master/src/schema/experience.js#L192 ＋ https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/master/src/schema/company.js#L12

interview_experiences 也可以 limit 數量

不確定距離拿到 `公司/職稱相關的經驗` 有多遠？

**Comment by peteranny** [comment]
可是一開始只有experienceID沒辦法query by company name & job title

**Comment by mark86092** [comment]
我以為這樣是可以的？

```gql
query($id:ID!) {
  experience(id:$id) {
    id
    company {
      name

      interview_experiences {
        id
      }
    }
    job_title {
      name
    }
  }
}
```

**Comment by peteranny** [comment]
已經上dev

**Comment by barry800414** [comment]
@peteranny 我剛測現在的 dev branch ，“更多ＯＯＯ公司、ＸＸＸ的面試及工作心得...”
還是沒有在原始碼內，看起來這塊 SSR 還是沒有出來
但下面的薪資區塊是有的
可以麻煩你確認一下嗎？

**Comment by peteranny** [comment]
我剛剛測是有的耶，你可以再檢查看看嗎？

**Comment by peteranny** [comment]
![螢幕快照 2020-09-20 下午11 58 48](https://user-images.githubusercontent.com/7566586/93715672-42f4d400-fb9d-11ea-8c2d-4eeb67e28ba3.png)

**Comment by barry800414** [comment]
找到了，原來是中間有自動生成的 `<!-- -->`
