### ISSUE TITLE
[前端] 移除職場經驗搜尋頁

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/GoodJobShare#967]
目前已經把公司與職稱的所有階層頁面都做好了
是否應該開始考慮移除職場搜尋的頁面？

**Comment by barry800414** [comment]
可以移除，但也沒有什麼太大的必要移除（留著不會有壞處）
如果你想移除的話，可以移除

**Comment by peteranny** [comment]
主要是怕會造成困惑@@

**Comment by barry800414** [comment]
想知道為什麼你會覺得造成困惑～～

我想得到唯一的問題是他從 footer 進去，逛完之後沒有用到 header 或首頁的搜尋框
但我覺得這情況不會太常見

**Comment by peteranny** [comment]
對，我主要就是想footer的這件事~ 這應該要解？

**Comment by peteranny** [comment]
以下可以拿掉

- https://www.goodjob.life/salary-work-times/latest
- https://www.goodjob.life/experiences/search

**Comment by peteranny** [comment]
https://www.goodjob.life/salary-work-times/latest
這個「最新薪資工時」的頁面會被舊版的一頁式薪資工時表單使用（送出資料時後的「查看最新薪資、工時」按鈕）。

在我們確認捨棄舊版一頁式薪資工時表單之前，沒辦法刪除「最新薪資工時」。

![截圖 2024-06-05 凌晨12 12 36](https://github.com/goodjoblife/GoodJobShare/assets/7566586/74548f0f-f954-422d-9493-dff9d8cf9f2d)

**Comment by peteranny** [comment]
https://www.goodjob.life/experiences/search
這個「搜尋面試」頁面，會被首頁的「看更多」連結。

在確認這個「看更多」要怎麼變更之前，沒辦法移除「搜尋面試」的頁面。

![截圖 2024-06-05 凌晨12 15 23](https://github.com/goodjoblife/GoodJobShare/assets/7566586/30989d61-e48a-45ef-9644-46f547edd0d8)

**Comment by barry800414** [comment]
> https://www.goodjob.life/salary-work-times/latest 這個「最新薪資工時」的頁面會被舊版的一頁式薪資工時表單使用（送出資料時後的「查看最新薪資、工時」按鈕）。
> 
> 在我們確認捨棄舊版一頁式薪資工時表單之前，沒辦法刪除「最新薪資工時」。
> 
> ![截圖 2024-06-05 凌晨12 12 36](https://private-user-images.githubusercontent.com/7566586/336528347-74548f0f-f954-422d-9493-dff9d8cf9f2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NDc1MjMsIm5iZiI6MTcxNzk0NzIyMywicGF0aCI6Ii83NTY2NTg2LzMzNjUyODM0Ny03NDU0OGYwZi1mOTU0LTQyMmQtOTQ5My1kZmY5ZDhjZjlmMmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDlUMTUzMzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTE2OTY5Y2EzYTIzZGRlZWU3MjFkZTNlODNlZmRlZGM2M2YxODU4NjM2MmRhYjA2YzY4OWFkNzBkMzRiNDUxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CmX6QKSGpXY--2PCWgEiFoGDxierzDCLmaOyNZTC77A)

這個 case ，請協助導到該公司的薪資頁面 `/companies/{company_name}/salary-work-times`

**Comment by barry800414** [comment]
> https://www.goodjob.life/experiences/search 這個「搜尋面試」頁面，會被首頁的「看更多」連結。
> 
> 在確認這個「看更多」要怎麼變更之前，沒辦法移除「搜尋面試」的頁面。
> 
> ![截圖 2024-06-05 凌晨12 15 23](https://private-user-images.githubusercontent.com/7566586/336529346-30989d61-e48a-45ef-9644-46f547edd0d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NDc1MjMsIm5iZiI6MTcxNzk0NzIyMywicGF0aCI6Ii83NTY2NTg2LzMzNjUyOTM0Ni0zMDk4OWQ2MS1lNDhhLTQ1ZWYtOTY0NC00NmY1NDdlZGQwZDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDlUMTUzMzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzdmZDI1YzE4Yjc0NjFlMjk4ZjA0YmJmZDY4NDY1ZDRmMjc2MTZiZjZmNzdiOTY5NDM3NWFkMjUyMTNiNjdmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6v10r8ZAH1OOR-uepyexZ7DkQg-oXHSqVBUGyF-qIxc)

這個 case ，請把看更多，換成搜尋框

![Screenshot 2024-06-09 at 11 36 48 PM](https://github.com/goodjoblife/GoodJobShare/assets/3805975/6d122b65-a16e-4f02-af04-27829560a6ff)

這算是暫時解，之後會有提案，可能會一起改首頁
