### ISSUE TITLE
立即分享按鈕無作用、無href

### ISSUE THREAD

**Issue by jason1004156** [goodjoblife/GoodJobShare#991]
![image](https://user-images.githubusercontent.com/32699556/128453421-7342d821-3282-40de-a2c7-42e94aa446a5.png)

**Comment by barry800414** [comment]
@jason1004156 Thank you for your reporting :) . We will fix it. Or if you are interested in, you can also directly create a PR for it.

**Comment by jason1004156** [comment]
@barry800414 是蠻有興趣，但沒有開發過這種專案，也沒有參與過這種開源，我研究看看><

**Comment by jason1004156** [comment]
@barry800414 不好意思，我已找到錯誤並修正，但我第一次參與這種開源專案，可否請教您如何提交pull request呢?
是否需要權限之類的

**Comment by jason1004156** [comment]
拍謝，第一次參與開源，這樣發PR到MASTER是對的嗎QAQ

**Comment by mark86092** [comment]
沒問題，我們是以 master 為主的 git flow
